#SessionConfig -- FILL IN YOUR VALUES
IL3.TraderId = AKLL  #<<-- ensure this ends in "L"
IL3.FirmId = AKL #was 2MN
IL3.SessionId = ALU
IL3.SecretKey = 8YwCj9pAq3mq2XmnXLg2nim4k3hWx_eUhTqBQ6NXrkE
IL3.AccessKey = wQFPyeK6NAdOWnlp14fM
IL3.SelfMatchId = 5676347
IL3.Port = 12345
IL3.BackupPort = 12345