#SessionConfig -- FILL IN YOUR VALUES
IL3.TraderId = AKLL  #<<-- ensure this ends in "L"
IL3.FirmId = AKL #was 2MN
IL3.SessionId = HRP
IL3.SecretKey = kLKlvGFYr4IubnzI75GNUVPb0yPOvNqXF6Vm0UQBRvA
IL3.AccessKey = rrxvl9L8D1yAam4kFUWg
IL3.SelfMatchId = 3923092
IL3.Port = 42408
IL3.BackupPort = 42408