#SessionConfig -- FILL IN YOUR VALUES
IL3.TraderId = AKLL  #<<-- ensure this ends in "L"
IL3.FirmId = AKL #was 2MN
IL3.SessionId = MLE
IL3.SecretKey = R_QSt3DmxzB5ndY7nuZjb26ThrBE-5B1ERLa4Ofpu84
IL3.AccessKey = MMyaIKnFOGDPiAo9fsYV
IL3.SelfMatchId = 1274575
IL3.Port = 42391
IL3.BackupPort = 42391
