NamedThread Class Reference
Represents a named thread with affinity to a specific core.
#include <NamedThread.hpp>
Public Member Functions
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
Represents a named thread with affinity to a specific core.
Constructor & Destructor Documentation
NamedThread()
NamedThread::NamedThread ()
Default constructor.
~NamedThread()
NamedThread::~NamedThread () [virtual]
Destructor.
References Join().
Member Function Documentation
CreateAndRun()
void NamedThread::CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
Parameters
name The name of the thread.
core The core to which the thread should be affinitized.
Referenced by KTN::AlgoServiceBrokerV3::AlgoServiceBrokerV3(), StandardMenu::DisplayAndWait(), ZmqMenu::DisplayAndWait(), KTN::ExchangeManager::ExchangeManager(), KTN::notify::Slacker::InitAndRun(), KTN::notify::NotifierRest::NotifierRest(), AuditTrailWriter::Start(), AuditTrailWriterV3::Start(), KTN::ALGO::IntervalTimer::Start(), KTN::ALGO::SimpleTimer::Start(), KTN::Core::HeartbeatMonitor::Start(), KtnCmeMbo::Start(), KtnCmeMdpV4::Start(), OrderManagerV5::UpdateMetaParams(), ZmqLogger::ZmqLogger(), ZmqSubscriberV5::ZmqSubscriberV5(), and ZmqSubscriberV5::ZmqSubscriberV5().
Join()
void NamedThread::Join ()
Joins the named thread.
Referenced by ~NamedThread().
The documentation for this class was generated from the following files:
Core/NamedThread.hpp
Core/NamedThread.cpp