KTN::AlgoServiceBrokerV3 Class Reference
The AlgoServiceBrokerV3 class routes messages to and from child instances of AlgoBaseV3.
#include <AlgoServiceBrokerV3.hpp>
Public Member Functions
AlgoServiceBrokerV3 (IExchangeSender *sess)
Constructs an instance of AlgoServiceBrokerV3 with the given exchange sender.
virtual ~AlgoServiceBrokerV3 ()
Destroys the AlgoServiceBrokerV3 instance.
void initZmq (std::string ArgoServer, int ArgoPort)
Initializes ZeroMQ with the specified server and port.
void Print ()
Prints information about the broker.
void StopAllAlgos ()
Stops all running algorithms.
void ResetPositions ()
Resets all positions.
void ResetPositionSingle (string uniqueid)
Resets the position for a single algorithm with the specified unique ID.
void SendCommand (int id)
Sends a command to the broker with the specified ID.
void onAlgoCommand (const Instruction &cmd)
Handles an algorithm command.
void onAlgoOrder (const Instruction &cmd)
Handles an algorithm order.
Public Member Functions inherited from IZmqSubscriber
virtual void onPubMsg (string topic, string payload)=0
Called when a message is received.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The AlgoServiceBrokerV3 class routes messages to and from child instances of AlgoBaseV3.
This class provides functionality for initializing ZeroMQ, printing information, stopping all algorithms, resetting positions, sending commands, and handling algorithm commands and orders.
Constructor & Destructor Documentation
AlgoServiceBrokerV3()
KTN::AlgoServiceBrokerV3::AlgoServiceBrokerV3 (IExchangeSender * sess) [explicit]
Constructs an instance of AlgoServiceBrokerV3 with the given exchange sender.
Parameters
sess The exchange sender to be used by the broker.
References NamedThread::CreateAndRun(), Settings::get(), Settings::getInteger(), and initZmq().
~AlgoServiceBrokerV3()
KTN::AlgoServiceBrokerV3::~AlgoServiceBrokerV3 () [virtual]
Destroys the AlgoServiceBrokerV3 instance.
Member Function Documentation
initZmq()
void KTN::AlgoServiceBrokerV3::initZmq (std::string ArgoServer, int ArgoPort)
Initializes ZeroMQ with the specified server and port.
Parameters
ArgoServer The server address for ZeroMQ.
ArgoPort The port number for ZeroMQ.
Referenced by AlgoServiceBrokerV3().
onAlgoCommand()
void KTN::AlgoServiceBrokerV3::onAlgoCommand (const Instruction & cmd)
Handles an algorithm command.
Parameters
cmd The instruction representing the algorithm command.
References IExchangeSender::AlgoJson(), AlgoFactory::LaunchAlgo(), AlgoFactory::ParseAlgoHeader(), AlgoFactory::ParseAlgoOrder(), and AlgoFactory::ParseEngineCommand().
onAlgoOrder()
void KTN::AlgoServiceBrokerV3::onAlgoOrder (const Instruction & cmd)
Handles an algorithm order.
Parameters
cmd The instruction representing the algorithm order.
Print()
void KTN::AlgoServiceBrokerV3::Print ()
Prints information about the broker.
ResetPositionSingle()
void KTN::AlgoServiceBrokerV3::ResetPositionSingle (string uniqueid)
Resets the position for a single algorithm with the specified unique ID.
Parameters
uniqueid The unique ID of the algorithm to reset.
SendCommand()
void KTN::AlgoServiceBrokerV3::SendCommand (int id)
Sends a command to the broker with the specified ID.
Parameters
id The ID of the command to send.
StopAllAlgos()
void KTN::AlgoServiceBrokerV3::StopAllAlgos ()
Stops all running algorithms.
Referenced by Raptor2::Stop().
The documentation for this class was generated from the following files:
Algos/AlgoServiceBrokerV3.hpp
Algos/AlgoServiceBrokerV3.cpp