WeightedAverageCalculator Class Reference
Calculates the weighted average based on price and size.
#include <WeightedAverageCalculator.hpp>
Public Member Functions
WeightedAverageCalculator (TimerCallback &cb)
Constructs a WeightedAverageCalculator object.
void Test ()
Performs a test.
void Start ()
Starts the calculation.
void Stop ()
Stops the calculation.
bool setStartEndTime (const std::string &startTime, const std::string &endTime)
Sets the start and end time for the calculation.
void calculate (int index, int64_t price, int32_t size)
Calculates the weighted average based on the given index, price, and size.
std::string getCurrentTime ()
Gets the current time.
double getWavg (int index)
Gets the weighted average based on the given index.
double getVolume (int index)
Gets the volume based on the given index.
double getCount (int index)
Gets the count based on the given index.
bool Triggered ()
Checks if the timer is triggered.
bool Started ()
Checks if the calculation is started.
Detailed Description
Calculates the weighted average based on price and size.
Constructor & Destructor Documentation
WeightedAverageCalculator()
WeightedAverageCalculator::WeightedAverageCalculator (TimerCallback & cb)
Constructs a WeightedAverageCalculator object.
Parameters
cb The TimerCallback object.
Member Function Documentation
calculate()
void WeightedAverageCalculator::calculate (int index, int64_t price, int32_t size)
Calculates the weighted average based on the given index, price, and size.
Parameters
index The index.
price The price.
size The size.
getCount()
double WeightedAverageCalculator::getCount (int index)
Gets the count based on the given index.
Parameters
index The index.
Returns
The count.
getCurrentTime()
std::string WeightedAverageCalculator::getCurrentTime ()
Gets the current time.
Returns
The current time in string format.
getVolume()
double WeightedAverageCalculator::getVolume (int index)
Gets the volume based on the given index.
Parameters
index The index.
Returns
The volume.
getWavg()
double WeightedAverageCalculator::getWavg (int index)
Gets the weighted average based on the given index.
Parameters
index The index.
Returns
The weighted average.
setStartEndTime()
bool WeightedAverageCalculator::setStartEndTime (const std::string & startTime, const std::string & endTime)
Sets the start and end time for the calculation.
Parameters
startTime The start time in string format.
endTime The end time in string format.
Returns
True if the start and end time are successfully set, false otherwise.
References Start().
Referenced by Test().
Start()
void WeightedAverageCalculator::Start ()
Starts the calculation.
References Started().
Referenced by setStartEndTime(), and Test().
Started()
bool WeightedAverageCalculator::Started ()
Checks if the calculation is started.
Returns
True if the calculation is started, false otherwise.
Referenced by Start().
Stop()
void WeightedAverageCalculator::Stop ()
Stops the calculation.
Test()
void WeightedAverageCalculator::Test ()
Performs a test.
References setStartEndTime(), and Start().
Triggered()
bool WeightedAverageCalculator::Triggered ()
Checks if the timer is triggered.
Returns
True if the timer is triggered, false otherwise.
The documentation for this class was generated from the following files:
AlgoCalculators/WeightedAverageCalculator.hpp
AlgoCalculators/WeightedAverageCalculator.cpp