KTN::Core::SPSCRingBuffer< T > Class Template Reference
A single-producer, single-consumer ring buffer implementation.
#include <SPSCRingBuffer.hpp>
Public Member Functions
SPSCRingBuffer (size_t capacity)
Constructs a new SPSCRingBuffer object with the specified capacity.
~SPSCRingBuffer ()
Destroys the SPSCRingBuffer object.
bool enqueue (const T &item, bool warmup=false)
Enqueues an item into the ring buffer.
bool push (const T &item, bool warmup=false)
Pushes an item into the ring buffer.
bool dequeue (T &item)
Dequeues an item from the ring buffer.
bool try_dequeue (T &item)
Tries to dequeue an item from the ring buffer.
bool try_pop (T &item)
Tries to pop an item from the ring buffer.
size_t size () const
Gets the current size of the ring buffer.
size_t size_approx () const
Gets an approximate size of the ring buffer.
bool empty () const
Checks if the ring buffer is empty.
Detailed Description
template<typename T>
class KTN::Core::SPSCRingBuffer< T >
A single-producer, single-consumer ring buffer implementation.
This class provides a thread-safe ring buffer that can be used in a single-producer, single-consumer scenario. It supports enqueueing and dequeueing elements, as well as checking the size and emptiness of the buffer.
Template Parameters
T The type of elements stored in the ring buffer.
Constructor & Destructor Documentation
SPSCRingBuffer()
template<typename T >
KTN::Core::SPSCRingBuffer< T >::SPSCRingBuffer (size_t capacity) [inline]
Constructs a new SPSCRingBuffer object with the specified capacity.
Parameters
capacity The capacity of the ring buffer.
~SPSCRingBuffer()
template<typename T >
KTN::Core::SPSCRingBuffer< T >::~SPSCRingBuffer () [inline]
Destroys the SPSCRingBuffer object.
Member Function Documentation
dequeue()
template<typename T >
bool KTN::Core::SPSCRingBuffer< T >::dequeue (T & item) [inline]
Dequeues an item from the ring buffer.
Parameters
item The dequeued item.
Returns
true if an item was successfully dequeued, false otherwise.
Referenced by OrderNums::NextOrderId(), OrderNums::NextOrderId(), OrderNums::NextOrderId2(), OrderNums::NextReqId(), and OrderNums::NextReqIdEncoded().
empty()
template<typename T >
bool KTN::Core::SPSCRingBuffer< T >::empty () const [inline]
Checks if the ring buffer is empty.
Returns
true if the ring buffer is empty, false otherwise.
Referenced by KTN::REPORTER::AlgoPLReporter::DoWork(), KTN::REPORTER::AlgoV3Reporter::DoWork(), KTN::REPORTER::OrderReporterV5::DoWork(), and AuditTrailWriterV3::Size().
enqueue()
template<typename T >
bool KTN::Core::SPSCRingBuffer< T >::enqueue (const T & item, bool warmup = false) [inline]
Enqueues an item into the ring buffer.
Parameters
item The item to enqueue.
warmup Flag indicating whether this is a warmup enqueue.
Returns
true if the item was successfully enqueued, false otherwise.
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), LogSvc::LogMe(), OrderManagerV5::ProcessOrderId(), and ZmqLogger::WriteLine().
push()
template<typename T >
bool KTN::Core::SPSCRingBuffer< T >::push (const T & item, bool warmup = false) [inline]
Pushes an item into the ring buffer.
Parameters
item The item to push.
warmup Flag indicating whether this is a warmup push.
Returns
true if the item was successfully pushed, false otherwise.
Referenced by KTN::CME::CmeAlgo::Command(), KTN::CME::CmeGT5::Command(), KTN::REPORTER::AlgoPLReporter::Report(), KTN::REPORTER::AlgoV3Reporter::Report(), KTN::REPORTER::OrderReporterV5::Report(), KTN::CME::CmeAlgo::SendMassAction(), KTN::CME::CmeGT5::SendMassAction(), KTN::CME::CmeAlgo::Stop(), KTN::CME::CmeGT5::Stop(), and AuditTrailWriterV3::Write().
size()
template<typename T >
size_t KTN::Core::SPSCRingBuffer< T >::size () const [inline]
Gets the current size of the ring buffer.
Returns
The current size of the ring buffer.
Referenced by OrderNums::OrdIdSize(), and OrderNums::ReqIdSize().
size_approx()
template<typename T >
size_t KTN::Core::SPSCRingBuffer< T >::size_approx () const [inline]
Gets an approximate size of the ring buffer.
Returns
An approximate size of the ring buffer.
Referenced by ZmqLogger::Run().
try_dequeue()
template<typename T >
bool KTN::Core::SPSCRingBuffer< T >::try_dequeue (T & item) [inline]
Tries to dequeue an item from the ring buffer.
Parameters
item The dequeued item.
Returns
true if an item was successfully dequeued, false otherwise.
Referenced by ZmqLogger::Run().
try_pop()
template<typename T >
bool KTN::Core::SPSCRingBuffer< T >::try_pop (T & item) [inline]
Tries to pop an item from the ring buffer.
Parameters
item The popped item.
Returns
true if an item was successfully popped, false otherwise.
Referenced by KTN::REPORTER::AlgoPLReporter::DoWork(), KTN::REPORTER::AlgoV3Reporter::DoWork(), KTN::REPORTER::OrderReporterV5::DoWork(), QuoterV3::Get(), QuoterV3::NextMod(), and QuoterV3::NextNew().
The documentation for this class was generated from the following file:
Maps/SPSCRingBuffer.hpp