LimitOrderBook Class Reference
Represents a limit order book.
#include <circular_book_array.hpp>
Public Member Functions
LimitOrderBook (int precision, int depth)
Constructor for LimitOrderBook.
virtual void add_order (const MdOrder &order, bool is_bid)
Adds an order to the order book.
void update_order (const MdOrder &order, bool is_bid)
Updates an order in the order book.
void delete_order (const MdOrder &order, bool is_bid)
Deletes an order from the order book.
MdOrder find_order_by_id (int order_id)
Finds an order in the order book by its ID.
virtual MdOrder get_best_bid ()
Gets the best bid order in the order book.
MdOrder get_lowest_bid ()
Gets the lowest bid order in the order book.
MdOrder get_best_offer ()
Gets the best offer order in the order book.
MdOrder get_highest_offer ()
Gets the highest offer order in the order book.
void print_bids ()
Prints the bid orders in the order book.
void print_offers ()
Prints the offer orders in the order book.
Protected Member Functions
int price_to_index (int32_t price, bool is_bid, bool update_pointers=true)
Converts a price to its corresponding index in the order book.
int order_id_to_index (int order_id, bool is_bid)
Converts an order ID to its corresponding index in the order book.
Protected Attributes
MdOrder * ptr_bid_ini
MdOrder * ptr_bid_end
MdOrder * ptr_offer_ini
MdOrder * ptr_offer_end
Detailed Description
Represents a limit order book.
Constructor & Destructor Documentation
LimitOrderBook()
LimitOrderBook::LimitOrderBook (int precision, int depth) [inline]
Constructor for LimitOrderBook.
Parameters
precision The precision of the order prices.
depth The depth of the order book.
References ptr_bid_end, ptr_bid_ini, ptr_offer_end, and ptr_offer_ini.
Member Function Documentation
add_order()
virtual void LimitOrderBook::add_order (const MdOrder & order, bool is_bid) [inline], [virtual]
Adds an order to the order book.
Parameters
order The order to add.
is_bid Flag indicating if the order is a bid order.
References MdOrder::price, and price_to_index().
delete_order()
void LimitOrderBook::delete_order (const MdOrder & order, bool is_bid) [inline]
Deletes an order from the order book.
Parameters
order The order to delete.
is_bid Flag indicating if the order is a bid order.
References MdOrder::price, and price_to_index().
find_order_by_id()
MdOrder LimitOrderBook::find_order_by_id (int order_id) [inline]
Finds an order in the order book by its ID.
Parameters
order_id The ID of the order to find.
Returns
The order with the given ID, or a default order if not found.
References order_id_to_index().
get_best_bid()
virtual MdOrder LimitOrderBook::get_best_bid () [inline], [virtual]
Gets the best bid order in the order book.
Returns
The best bid order.
References ptr_bid_end.
get_best_offer()
MdOrder LimitOrderBook::get_best_offer () [inline]
Gets the best offer order in the order book.
Returns
The best offer order.
References ptr_offer_ini.
get_highest_offer()
MdOrder LimitOrderBook::get_highest_offer () [inline]
Gets the highest offer order in the order book.
Returns
The highest offer order.
References ptr_offer_end.
get_lowest_bid()
MdOrder LimitOrderBook::get_lowest_bid () [inline]
Gets the lowest bid order in the order book.
Returns
The lowest bid order.
References ptr_bid_ini.
order_id_to_index()
int LimitOrderBook::order_id_to_index (int order_id, bool is_bid) [inline], [protected]
Converts an order ID to its corresponding index in the order book.
Parameters
order_id The order ID to convert.
is_bid Flag indicating if the order is a bid order.
Returns
The index of the order ID in the order book.
Referenced by find_order_by_id().
price_to_index()
int LimitOrderBook::price_to_index (int32_t price, bool is_bid, bool update_pointers = true) [inline], [protected]
Converts a price to its corresponding index in the order book.
Parameters
price The price to convert.
is_bid Flag indicating if the price is for a bid order.
update_pointers Flag indicating if the order book pointers should be updated.
Returns
The index of the price in the order book.
Referenced by add_order(), delete_order(), and update_order().
print_bids()
void LimitOrderBook::print_bids () [inline]
Prints the bid orders in the order book.
References MdOrder::price, ptr_bid_end, and ptr_bid_ini.
print_offers()
void LimitOrderBook::print_offers () [inline]
Prints the offer orders in the order book.
References MdOrder::price, ptr_offer_end, and ptr_offer_ini.
update_order()
void LimitOrderBook::update_order (const MdOrder & order, bool is_bid) [inline]
Updates an order in the order book.
Parameters
order The order to update.
is_bid Flag indicating if the order is a bid order.
References MdOrder::price, and price_to_index().
Member Data Documentation
ptr_bid_end
MdOrder* LimitOrderBook::ptr_bid_end [protected]
Pointer to the end bid order.
Referenced by get_best_bid(), LimitOrderBook(), and print_bids().
ptr_bid_ini
MdOrder* LimitOrderBook::ptr_bid_ini [protected]
Pointer to the initial bid order.
Referenced by get_lowest_bid(), LimitOrderBook(), and print_bids().
ptr_offer_end
MdOrder* LimitOrderBook::ptr_offer_end [protected]
Pointer to the end offer order.
Referenced by get_highest_offer(), LimitOrderBook(), and print_offers().
ptr_offer_ini
MdOrder* LimitOrderBook::ptr_offer_ini [protected]
Pointer to the initial offer order.
Referenced by get_best_offer(), LimitOrderBook(), and print_offers().
The documentation for this class was generated from the following file:
Core/circular_book_array.hpp