SessionStateManager Class Reference
Manages the state of a session.
#include <SessionStateManager.hpp>
Public Member Functions
SessionStateManager ()
Default constructor.
virtual ~SessionStateManager ()
Destructor.
void Init (string sessionid, string firmid, int segid, int hbsecs, int hbbuffms)
Initializes the session state manager.
void Stop ()
Stops the session state manager.
void Update ()
Updates the session state manager.
const bool Connected () const
Checks if the session is connected.
void onStateChange (EnumSessionState::Enum newState)
Handles the state change of the session.
const string & Firmid () const
Gets the firm ID.
void SetFirmid (const string &firmid)
Sets the firm ID.
uint64_t Prevuuid () const
Gets the previous UUID.
void SetPrevuuid (uint64_t prevuuid)
Sets the previous UUID.
int Segid () const
Gets the segment ID.
void SetSegid (int segid)
Sets the segment ID.
uint64_t SeqIn () const
Gets the incoming sequence number.
void SetSeqIn (uint64_t seqIn)
Sets the incoming sequence number.
uint64_t IncSeqIn (int numseqs)
Increments the incoming sequence number by a specified number of sequences.
uint64_t SeqOut () const
Gets the outgoing sequence number.
uint64_t SeqOutAndAdvance ()
Advances the outgoing sequence number and returns the previous value.
void SetSeqOut (uint64_t seqOut, bool persist)
Sets the outgoing sequence number.
uint64_t IncSeqOut (int numSeqs)
Increments the outgoing sequence number by a specified number of sequences.
const string & Sessid () const
Gets the session ID.
void SetSessid (const string &sessid)
Sets the session ID.
uint64_t Uuid () const
Gets the UUID.
void SetUuid (uint64_t uuid)
Sets the UUID.
uint64_t NewReqId ()
Generates a new request ID.
void SetReqId (uint64_t id)
Sets the request ID.
uint64_t LastReqId ()
Gets the last request ID.
bool HbTriggered ()
Checks if a heartbeat has been triggered.
void HbSent ()
Marks a heartbeat as sent.
uint64_t LastHb () const
Gets the timestamp of the last heartbeat.
void SetLastHb (uint64_t hb)
Sets the timestamp of the last heartbeat.
uint64_t HbCount () const
Gets the heartbeat count.
Public Attributes
EnumSessionState::Enum CurrentState
Detailed Description
Manages the state of a session.
Constructor & Destructor Documentation
SessionStateManager()
SessionStateManager::SessionStateManager ()
Default constructor.
~SessionStateManager()
SessionStateManager::~SessionStateManager () [virtual]
Destructor.
Member Function Documentation
Connected()
const bool SessionStateManager::Connected () const
Checks if the session is connected.
Returns
True if connected, false otherwise
Firmid()
const string & SessionStateManager::Firmid () const
Gets the firm ID.
Returns
The firm ID
HbCount()
uint64_t SessionStateManager::HbCount () const
Gets the heartbeat count.
Returns
The heartbeat count
HbSent()
void SessionStateManager::HbSent ()
Marks a heartbeat as sent.
References KTN::Core::HeartbeatMonitor::Reset().
HbTriggered()
bool SessionStateManager::HbTriggered ()
Checks if a heartbeat has been triggered.
Returns
True if a heartbeat has been triggered, false otherwise
References KTN::Core::HeartbeatMonitor::IsFlagSet().
IncSeqIn()
uint64_t SessionStateManager::IncSeqIn (int numseqs = 1)
Increments the incoming sequence number by a specified number of sequences.
Parameters
numseqs The number of sequences to increment by
Returns
The new incoming sequence number
IncSeqOut()
uint64_t SessionStateManager::IncSeqOut (int numSeqs = 1)
Increments the outgoing sequence number by a specified number of sequences.
Parameters
numSeqs The number of sequences to increment by
Returns
The new outgoing sequence number
Init()
void SessionStateManager::Init (string sessionid, string firmid, int segid, int hbsecs, int hbbuffms)
Initializes the session state manager.
Parameters
sessionid The session ID
firmid The firm ID
segid The segment ID
hbsecs The heartbeat interval in seconds
hbbuffms The heartbeat buffer in milliseconds
References Settings::get(), Settings::getBoolean(), Settings::getInteger(), Settings::getLong(), KTN::Core::HeartbeatMonitor::Start(), and Update().
LastHb()
uint64_t SessionStateManager::LastHb () const
Gets the timestamp of the last heartbeat.
Returns
The timestamp of the last heartbeat
LastReqId()
uint64_t SessionStateManager::LastReqId ()
Gets the last request ID.
Returns
The last request ID
NewReqId()
uint64_t SessionStateManager::NewReqId ()
Generates a new request ID.
Returns
The new request ID
onStateChange()
void SessionStateManager::onStateChange (EnumSessionState::Enum newState)
Handles the state change of the session.
Parameters
newState The new state of the session
References KTN::CME::IL3::EnumSessionState::Disconnected, KTN::CME::IL3::EnumSessionState::Established, and Segid().
Referenced by Stop().
Prevuuid()
uint64_t SessionStateManager::Prevuuid () const
Gets the previous UUID.
Returns
The previous UUID
Segid()
int SessionStateManager::Segid () const
Gets the segment ID.
Returns
The segment ID
Referenced by onStateChange().
SeqIn()
uint64_t SessionStateManager::SeqIn () const
Gets the incoming sequence number.
Returns
The incoming sequence number
SeqOut()
uint64_t SessionStateManager::SeqOut () const
Gets the outgoing sequence number.
Returns
The outgoing sequence number
SeqOutAndAdvance()
uint64_t SessionStateManager::SeqOutAndAdvance ()
Advances the outgoing sequence number and returns the previous value.
Returns
The previous outgoing sequence number
Referenced by KTN::CME::CmeAlgo::Send(), and KTN::CME::CmeGT5::Send().
Sessid()
const string & SessionStateManager::Sessid () const
Gets the session ID.
Returns
The session ID
SetFirmid()
void SessionStateManager::SetFirmid (const string & firmid)
Sets the firm ID.
Parameters
firmid The firm ID
References Update().
SetLastHb()
void SessionStateManager::SetLastHb (uint64_t hb)
Sets the timestamp of the last heartbeat.
Parameters
hb The timestamp of the last heartbeat
SetPrevuuid()
void SessionStateManager::SetPrevuuid (uint64_t prevuuid)
Sets the previous UUID.
Parameters
prevuuid The previous UUID
References Update().
SetReqId()
void SessionStateManager::SetReqId (uint64_t id)
Sets the request ID.
Parameters
id The request ID
SetSegid()
void SessionStateManager::SetSegid (int segid)
Sets the segment ID.
Parameters
segid The segment ID
References Update().
SetSeqIn()
void SessionStateManager::SetSeqIn (uint64_t seqIn)
Sets the incoming sequence number.
Parameters
seqIn The incoming sequence number
References Update().
SetSeqOut()
void SessionStateManager::SetSeqOut (uint64_t seqOut, bool persist)
Sets the outgoing sequence number.
Parameters
seqOut The outgoing sequence number
persist Flag indicating whether to persist the sequence number
References Update().
SetSessid()
void SessionStateManager::SetSessid (const string & sessid)
Sets the session ID.
Parameters
sessid The session ID
References Update().
SetUuid()
void SessionStateManager::SetUuid (uint64_t uuid)
Sets the UUID.
Parameters
uuid The UUID
References Update().
Stop()
void SessionStateManager::Stop ()
Stops the session state manager.
References KTN::CME::IL3::EnumSessionState::Disconnected, onStateChange(), and KTN::Core::HeartbeatMonitor::Stop().
Update()
void SessionStateManager::Update ()
Updates the session state manager.
References SessSvc::Persist().
Referenced by Init(), SetFirmid(), SetPrevuuid(), SetSegid(), SetSeqIn(), SetSeqOut(), SetSessid(), and SetUuid().
Uuid()
uint64_t SessionStateManager::Uuid () const
Gets the UUID.
Returns
The UUID
Member Data Documentation
CurrentState
EnumSessionState::Enum SessionStateManager::CurrentState
The documentation for this class was generated from the following files:
exchsupport/cme/il3/SessionStateManager.hpp
exchsupport/cme/il3/SessionStateManager.cpp