OrderManagerV5 Class Reference
The OrderManagerV5 class is responsible for managing orders and their execution. It implements the IOrderHandler interface and inherits from the NamedThread class.
#include <OrderManagerV5.hpp>
Public Member Functions
OrderManagerV5 (int core, string owner)
Constructs an OrderManagerV5 object.
virtual ~OrderManagerV5 ()
Destroys the OrderManagerV5 object.
void Stop ()
Stops the order manager.
void LoadTemplate (const KTN::Order &ord)
Loads a template order.
string NewId (const string &prefix)
Generates a new order ID with the given prefix.
KTN::OrderPod GetOrder (uint64_t reqid)
Gets the order with the specified request ID.
bool Exists (uint64_t reqid)
Checks if an order with the specified request ID exists.
void Clear ()
Clears all orders.
void ClearDeadOrders ()
Clears all dead orders.
int Count ()
Gets the count of orders.
void Print ()
Prints the orders.
void UpdateMetaParams (const algometa &meta, bool certnr)
Updates the meta parameters with the given algorithm metadata.
void EnableOrderReporter (bool value)
Enables or disables the order reporter.
void ProcessSpreadLegs (bool value)
Sets whether to process spread legs.
void onBankedOrder (KTN::Order &ord)
Handles a banked order.
void onSentOrderNew (KTN::OrderPod &ord)
Handles a new sent order.
void onSentOrderMod (KTN::OrderPod &ord)
Handles a modified sent order.
void onSentOrderCxl (KTN::OrderPod &ord)
Handles a canceled sent order.
void onSentOrderFast (KTN::OrderPod &ord)
Handles a fast sent order.
void onSentOrderOrdbook (KTN::OrderPod &ord, UserInfo &info)
Handles an order book sent order.
int UpdateOrder (uint64_t reqid, uint64_t exchordid, KOrderStatus::Enum status, KOrderState::Enum state, uint32_t qty, uint64_t timestamp)
Updates an order with the specified request ID.
void minOrderAck (KTN::OrderPod &ord)
Handles a minimum order acknowledgment.
void minOrderCancel (KTN::OrderPod &ord)
Handles a minimum order cancellation.
void minOrderModify (KTN::OrderPod &ord)
Handles a minimum order modification.
void UpdateExecution (uint64_t reqid, uint64_t exchordid, KOrderStatus::Enum status, KOrderState::Enum state, KOrderFillType::Enum filltype, int64_t lastpx, uint32_t lastqty, uint32_t lvs, uint64_t timestamp, string execid)
Updates the execution of an order with the specified request ID.
void UpdateSpreadLegExecution (uint64_t exchordid, KOrderSide::Enum side, int32_t secid, int64_t lastpx, uint32_t lastqty, uint64_t timestamp, string execid)
Updates the execution of a spread leg order with the specified CME ID.
void minOrderExecution (KTN::OrderPod &ord, bool hedgeSent)
Handles the execution of a minimum order.
void minOrderExecSpreadLeg (KTN::OrderPod &ord)
Handles the execution of a minimum order spread leg.
void minOrderReject (KTN::OrderPod &ord, const string &text)
Handles the rejection of a minimum order.
void minOrderCancelReject (KTN::OrderPod &ord, const string &text)
Handles the rejection of a minimum order cancellation.
void minOrderCancelReplaceReject (KTN::OrderPod &ord, const string &text)
Handles the rejection of a minimum order cancel/replace.
virtual void ProcessOrderId (uint64_t ordid)
Process the order ID.
virtual void ProcessOrder (OrderPod &ord)
Process the order.
virtual void ProcessFill (OrderPod &ord)
Process the fill.
virtual void ProcessSentOrder (OrderPod &ord)
Process the sent order.
virtual void ProcessRejectedOrder (OrderPod &ord, const string &text)
Process the rejected order.
virtual void RegisterOrderTemplate (Order &ord)
bool GetByOrdernum (KTN::OrderPod &ord, const string &ordernum)
bool GetByExchId (KTN::OrderPod &ord, uint64_t exchordid)
void Get (KTN::OrderPod &ord, uint64_t reqid)
vector< KTN::OrderPod > GetAll ()
vector< KTN::OrderPod > GetWorking ()
void GetBySecIdSideStrat (vector< KTN::OrderPod > &ords, int32_t secid, const KOrderSide::Enum side, int stratid)
bool GetBySecIdSideStrat (KTN::OrderPod &ord, int32_t secid, const KOrderSide::Enum side, int stratid)
void GetByStratId (vector< KTN::OrderPod > &ords, int stratid)
void GetByAlgoTrigger (vector< KTN::OrderPod > &ords, const KOrderAlgoTrigger::Enum trig)
void GetByAlgoTriggerSecId (vector< KTN::OrderPod > &ords, const KOrderAlgoTrigger::Enum trig, int32_t secid)
void GetByAlgoTriggerPrice (vector< KTN::OrderPod > &ords, const KOrderAlgoTrigger::Enum trig, int32_t secid, int32_t price)
bool GetAtPrice (vector< KTN::OrderPod > &orders, int32_t secid, KOrderSide::Enum side, int32_t price, KOrderAlgoTrigger::Enum trig)
int GetSideExposure (int32_t secid, KOrderSide::Enum side, KOrderAlgoTrigger::Enum trig)
bool HasInflight (const string &tag)
bool HasInflight ()
void ClearInflight ()
Public Member Functions inherited from KTN::ORD::IOrderHandler
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The OrderManagerV5 class is responsible for managing orders and their execution. It implements the IOrderHandler interface and inherits from the NamedThread class.
Constructor & Destructor Documentation
OrderManagerV5()
OrderManagerV5::OrderManagerV5 (int core, string owner)
Constructs an OrderManagerV5 object.
Parameters
core The core number.
owner The owner of the order manager.
~OrderManagerV5()
OrderManagerV5::~OrderManagerV5 () [virtual]
Destroys the OrderManagerV5 object.
Member Function Documentation
Clear()
void OrderManagerV5::Clear ()
Clears all orders.
References CustomHFTMap::clear().
ClearDeadOrders()
void OrderManagerV5::ClearDeadOrders ()
Clears all dead orders.
References CustomHFTMap::cleardead().
Referenced by KTN::MultiSpreaderV3::Enable(), KTN::Skewer::Enable(), KTN::SkewTrader::Enable(), KTN::Stacker::Enable(), KTN::StackerTimer::Enable(), and KTN::Twap::Enable().
ClearInflight()
void OrderManagerV5::ClearInflight ()
Count()
int OrderManagerV5::Count ()
Gets the count of orders.
Returns
The count of orders.
References CustomHFTMap::size().
Referenced by Print().
EnableOrderReporter()
void OrderManagerV5::EnableOrderReporter (bool value) [inline]
Enables or disables the order reporter.
Parameters
value True to enable the order reporter, false to disable it.
Exists()
bool OrderManagerV5::Exists (uint64_t reqid)
Checks if an order with the specified request ID exists.
Parameters
reqid The request ID of the order.
Returns
True if an order with the specified request ID exists, false otherwise.
References CustomHFTMap::find().
Get()
void OrderManagerV5::Get (KTN::OrderPod & ord, uint64_t reqid)
GetAll()
vector< KTN::OrderPod > OrderManagerV5::GetAll ()
GetAtPrice()
bool OrderManagerV5::GetAtPrice (vector< KTN::OrderPod > & orders, int32_t secid, KOrderSide::Enum side, int32_t price, KOrderAlgoTrigger::Enum trig)
GetByAlgoTrigger()
void OrderManagerV5::GetByAlgoTrigger (vector< KTN::OrderPod > & ords, const KOrderAlgoTrigger::Enum trig)
GetByAlgoTriggerPrice()
void OrderManagerV5::GetByAlgoTriggerPrice (vector< KTN::OrderPod > & ords, const KOrderAlgoTrigger::Enum trig, int32_t secid, int32_t price)
GetByAlgoTriggerSecId()
void OrderManagerV5::GetByAlgoTriggerSecId (vector< KTN::OrderPod > & ords, const KOrderAlgoTrigger::Enum trig, int32_t secid)
GetByExchId()
bool OrderManagerV5::GetByExchId (KTN::OrderPod & ord, uint64_t exchordid)
GetByOrdernum()
bool OrderManagerV5::GetByOrdernum (KTN::OrderPod & ord, const string & ordernum)
GetBySecIdSideStrat() [1/2]
bool OrderManagerV5::GetBySecIdSideStrat (KTN::OrderPod & ord, int32_t secid, const KOrderSide::Enum side, int stratid)
GetBySecIdSideStrat() [2/2]
void OrderManagerV5::GetBySecIdSideStrat (vector< KTN::OrderPod > & ords, int32_t secid, const KOrderSide::Enum side, int stratid)
GetByStratId()
void OrderManagerV5::GetByStratId (vector< KTN::OrderPod > & ords, int stratid)
GetOrder()
KTN::OrderPod OrderManagerV5::GetOrder (uint64_t reqid)
Gets the order with the specified request ID.
Parameters
reqid The request ID of the order.
Returns
The order with the specified request ID.
References CustomHFTMap::get().
GetSideExposure()
int OrderManagerV5::GetSideExposure (int32_t secid, KOrderSide::Enum side, KOrderAlgoTrigger::Enum trig)
GetWorking()
vector< KTN::OrderPod > OrderManagerV5::GetWorking ()
HasInflight() [1/2]
bool OrderManagerV5::HasInflight ()
HasInflight() [2/2]
bool OrderManagerV5::HasInflight (const string & tag)
LoadTemplate()
void OrderManagerV5::LoadTemplate (const KTN::Order & ord)
Loads a template order.
Parameters
ord The template order to load.
minOrderAck()
void OrderManagerV5::minOrderAck (KTN::OrderPod & ord)
Handles a minimum order acknowledgment.
Parameters
ord The minimum order to acknowledge.
References KTN::OrderPod::exchordid, KTN::OrderPod::leavesqty, KTN::OrderPod::orderReqId, ProcessOrder(), and KTN::OrderPod::timestamp.
Referenced by KTN::AlgoBaseV3::minOrderAck().
minOrderCancel()
void OrderManagerV5::minOrderCancel (KTN::OrderPod & ord)
Handles a minimum order cancellation.
Parameters
ord The minimum order to cancel.
References KTN::OrderPod::orderReqId, ProcessOrder(), and KTN::OrderPod::timestamp.
Referenced by KTN::AlgoBaseV3::minOrderCancel(), and KTN::Stacker::minOrderCancel().
minOrderCancelReject()
void OrderManagerV5::minOrderCancelReject (KTN::OrderPod & ord, const string & text)
Handles the rejection of a minimum order cancellation.
Parameters
ord The minimum order cancellation to reject.
text The rejection text.
References ProcessRejectedOrder().
minOrderCancelReplaceReject()
void OrderManagerV5::minOrderCancelReplaceReject (KTN::OrderPod & ord, const string & text)
Handles the rejection of a minimum order cancel/replace.
Parameters
ord The minimum order cancel/replace to reject.
text The rejection text.
References ProcessRejectedOrder().
minOrderExecSpreadLeg()
void OrderManagerV5::minOrderExecSpreadLeg (KTN::OrderPod & ord)
Handles the execution of a minimum order spread leg.
Parameters
ord The minimum order spread leg to execute.
References KTN::OrderPod::exchordid, KTN::OrderPod::execid, CustomHFTMap::get(), KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdState, KTN::OrderPod::OrdTif, KTN::OrderPod::OrdType, KTN::OrderPod::price, ProcessFill(), KTN::OrderPod::quantity, KTN::OrderPod::secid, and KTN::OrderPod::stratid.
Referenced by KTN::MultiSpreaderV3::minOrderExecution(), KTN::Skewer::minOrderExecution(), KTN::SkewTrader::minOrderExecution(), KTN::Stacker::minOrderExecution(), KTN::StackerTimer::minOrderExecution(), and KTN::Twap::minOrderExecution().
minOrderExecution()
void OrderManagerV5::minOrderExecution (KTN::OrderPod & ord, bool hedgeSent)
Handles the execution of a minimum order.
Parameters
ord The minimum order to execute.
hedgeSent The flag indicating whether the hedge order was sent.
References KTN::OrderPod::exchordid, CustomHFTMap::get(), KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, KTN::OrderPod::leavesqty, KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdState, KTN::OrderPod::OrdStatus, KTN::OrderPod::price, ProcessFill(), KTN::OrderPod::secid, KTN::OrderPod::stratid, and KTN::OrderPod::timestamp.
Referenced by KTN::AutoHedgeOB::minOrderExecution(), KTN::MultiSpreaderV3::minOrderExecution(), KTN::PLWatcher::minOrderExecution(), KTN::Skewer::minOrderExecution(), KTN::SkewTrader::minOrderExecution(), KTN::SqueezerOB::minOrderExecution(), KTN::Stacker::minOrderExecution(), KTN::StackerTimer::minOrderExecution(), KTN::Twap::minOrderExecution(), and KTN::Waves::minOrderExecution().
minOrderModify()
void OrderManagerV5::minOrderModify (KTN::OrderPod & ord)
Handles a minimum order modification.
Parameters
ord The minimum order to modify.
References KTN::OrderPod::leavesqty, KTN::OrderPod::orderReqId, ProcessOrder(), and KTN::OrderPod::timestamp.
Referenced by KTN::AlgoBaseV3::minOrderModify().
minOrderReject()
void OrderManagerV5::minOrderReject (KTN::OrderPod & ord, const string & text)
Handles the rejection of a minimum order.
Parameters
ord The minimum order to reject.
text The rejection text.
References ProcessRejectedOrder().
Referenced by KTN::Stacker::minOrderCancelReject(), KTN::Stacker::minOrderCancelReplaceReject(), and KTN::AlgoBaseV3::minOrderReject().
NewId()
std::string OrderManagerV5::NewId (const string & prefix)
Generates a new order ID with the given prefix.
Parameters
prefix The prefix for the new order ID.
Returns
The new order ID.
onBankedOrder()
void OrderManagerV5::onBankedOrder (KTN::Order & ord)
Handles a banked order.
Parameters
ord The banked order to handle.
onSentOrderCxl()
void OrderManagerV5::onSentOrderCxl (KTN::OrderPod & ord)
Handles a canceled sent order.
Parameters
ord The canceled sent order to handle.
References KTN::OrderPod::orderReqId.
Referenced by KTN::PLWatcher::OrderReceived(), and KTN::Waves::OrderReceived().
onSentOrderFast()
void OrderManagerV5::onSentOrderFast (KTN::OrderPod & ord)
Handles a fast sent order.
Parameters
ord The fast sent order to handle.
References KTN::OrderPod::orderReqId.
Referenced by KTN::MultiSpreaderV3::onHedgeOrderSent(), KTN::SkewTrader::onHedgeOrderSent(), KTN::Stacker::onHedgeOrderSent(), KTN::Waves::onHedgeOrderSent(), KTN::SqueezerOB::onJson(), KTN::MultiSpreaderV3::onOrderSent(), KTN::SkewTrader::onOrderSent(), KTN::Stacker::onOrderSent(), KTN::Waves::onOrderSent(), KTN::PLWatcher::onPL(), and KTN::PLWatcher::OrderReceived().
onSentOrderMod()
void OrderManagerV5::onSentOrderMod (KTN::OrderPod & ord)
Handles a modified sent order.
Parameters
ord The modified sent order to handle.
References KTN::OrderPod::orderReqId.
Referenced by KTN::PLWatcher::OrderReceived(), and KTN::Waves::OrderReceived().
onSentOrderNew()
void OrderManagerV5::onSentOrderNew (KTN::OrderPod & ord)
Handles a new sent order.
Parameters
ord The new sent order to handle.
References KTN::OrderPod::orderReqId.
onSentOrderOrdbook()
void OrderManagerV5::onSentOrderOrdbook (KTN::OrderPod & ord, UserInfo & info)
Handles an order book sent order.
Parameters
ord The order book sent order to handle.
info The user info associated with the order.
References KTN::OrderPod::orderReqId.
Referenced by KTN::ORD::OrderHandlerZmqV6::LoadTasOrders().
Print()
void OrderManagerV5::Print ()
Prints the orders.
References Count().
Referenced by KTN::AlgoBaseV3::Print(), KTN::MultiSpreaderV3::Print(), KTN::ORD::OrderHandlerZmqV6::Print(), KTN::Skewer::Print(), KTN::SkewTrader::Print(), KTN::Stacker::Print(), KTN::StackerTimer::Print(), KTN::Twap::Print(), KTN::CME::CmeAlgo::PrintLatencies(), KTN::AlgoBaseV3::ToggleCommand(), and KTN::Waves::ToggleCommand().
ProcessFill()
void OrderManagerV5::ProcessFill (OrderPod & ord) [virtual]
Process the fill.
Parameters
ord The fill to process.
Implements KTN::ORD::IOrderHandler.
Referenced by minOrderExecSpreadLeg(), minOrderExecution(), UpdateExecution(), and UpdateSpreadLegExecution().
ProcessOrder()
void OrderManagerV5::ProcessOrder (OrderPod & ord) [virtual]
Process the order.
Parameters
ord The order to process.
Implements KTN::ORD::IOrderHandler.
Referenced by minOrderAck(), minOrderCancel(), and minOrderModify().
ProcessOrderID()
void OrderManagerV5::ProcessOrderId (uint64_t ordid) [virtual]
Process the order ID.
Parameters
ordid The order ID to process.
Implements KTN::ORD::IOrderHandler.
References KTN::Core::SPSCRingBuffer< T >::enqueue().
Referenced by UpdateOrder().
ProcessRejectedOrder()
void OrderManagerV5::ProcessRejectedOrder (OrderPod & ord, const string & text) [virtual]
Process the rejected order.
Parameters
ord The rejected order to process.
text The rejection text.
Implements KTN::ORD::IOrderHandler.
Referenced by minOrderCancelReject(), minOrderCancelReplaceReject(), and minOrderReject().
ProcessSentOrder()
void OrderManagerV5::ProcessSentOrder (OrderPod & ord) [virtual]
Process the sent order.
Parameters
ord The sent order to process.
Implements KTN::ORD::IOrderHandler.
ProcessSpreadLegs()
void OrderManagerV5::ProcessSpreadLegs (bool value) [inline]
Sets whether to process spread legs.
Parameters
value True to process spread legs, false otherwise.
RegisterOrderTemplate()
void OrderManagerV5::RegisterOrderTemplate (Order & ord) [virtual]
This function is new in V5 to handle OrderPod conversion. Going forward we will only use the large format order for reporting back to database/monitoring systems that are not critical path
Implements KTN::ORD::IOrderHandler.
Stop()
void OrderManagerV5::Stop ()
Stops the order manager.
Referenced by KTN::AlgoBaseV3::Shutdown(), and KTN::ORD::OrderHandlerZmqV6::~OrderHandlerZmqV6().
UpdateExecution()
void OrderManagerV5::UpdateExecution (uint64_t reqid, uint64_t exchordid, KOrderStatus::Enum status, KOrderState::Enum state, KOrderFillType::Enum filltype, int64_t lastpx, uint32_t lastqty, uint32_t lvs, uint64_t timestamp, string execid)
Updates the execution of an order with the specified request ID.
Parameters
reqid The request ID of the order.
exchordid The CME ID of the order.
status The status of the order.
state The state of the order.
filltype The fill type of the order.
lastpx The last price of the order.
lastqty The last quantity of the order.
lvs The leaves quantity of the order.
timestamp The timestamp of the execution update.
execid The execution ID of the order.
References CustomHFTMap::get(), and ProcessFill().
UpdateMetaParams()
void OrderManagerV5::UpdateMetaParams (const algometa & meta, bool certnr)
Updates the meta parameters with the given algorithm metadata.
Parameters
meta The algorithm metadata.
certnr The flag indicating whether the algorithm is certified.
References NamedThread::CreateAndRun().
Referenced by KTN::ORD::OrderHandlerZmqV6::OrderHandlerZmqV6().
UpdateOrder()
int OrderManagerV5::UpdateOrder (uint64_t reqid, uint64_t exchordid, KOrderStatus::Enum status, KOrderState::Enum state, uint32_t qty, uint64_t timestamp)
Updates an order with the specified request ID.
Parameters
reqid The request ID of the order.
exchordid The CME ID of the order.
status The status of the order.
state The state of the order.
qty The quantity of the order.
timestamp The timestamp of the order update.
Returns
The number of orders updated.
References ProcessOrderId().
UpdateSpreadLegExecution()
void OrderManagerV5::UpdateSpreadLegExecution (uint64_t exchordid, KOrderSide::Enum side, int32_t secid, int64_t lastpx, uint32_t lastqty, uint64_t timestamp, string execid)
Updates the execution of a spread leg order with the specified CME ID.
Parameters
exchordid The CME ID of the order.
side The side of the order.
secid The security ID of the order.
lastpx The last price of the order.
lastqty The last quantity of the order.
timestamp The timestamp of the execution update.
execid The execution ID of the order.
References KTN::OrderPod::execid, KTN::OrderPod::fillqty, CustomHFTMap::get(), KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, KTN::OrderPod::leavesqty, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdState, KTN::OrderPod::OrdStatus, ProcessFill(), KTN::OrderPod::secid, and KTN::OrderPod::timestamp.
The documentation for this class was generated from the following files:
Orders/OrderManagerV5.hpp
Orders/OrderManagerV5.cpp