ZmqLogger Class Reference
The ZmqLogger class is responsible for logging messages using ZeroMQ.
#include <ZmqLogger.hpp>
Public Member Functions
ZmqLogger ()
Default constructor for the ZmqLogger class.
virtual ~ZmqLogger ()
Destructor for the ZmqLogger class.
void WriteLine (const std::string &msg, const std::string &topic, int color)
Writes a log message with the specified topic and color.
void Run () override
Runs the ZmqLogger thread.
void Replay (int count)
Replays a specified number of log messages.
void Replay (int count, const string &owner)
Replays a specified number of log messages for a specific owner.
Public Member Functions inherited from ILogger
virtual ~ILogger ()=default
Destructor for the ILogger class.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The ZmqLogger class is responsible for logging messages using ZeroMQ.
Constructor & Destructor Documentation
ZmqLogger()
ZmqLogger::ZmqLogger ()
Default constructor for the ZmqLogger class.
References NamedThread::CreateAndRun(), and Settings::get().
~ZmqLogger()
ZmqLogger::~ZmqLogger () [virtual]
Destructor for the ZmqLogger class.
Member Function Documentation
Replay() [1/2]
void ZmqLogger::Replay (int count)
Replays a specified number of log messages.
Parameters
count The number of log messages to replay.
Replay() [2/2]
void ZmqLogger::Replay (int count, const string & owner)
Replays a specified number of log messages for a specific owner.
Parameters
count The number of log messages to replay.
owner The owner of the log messages.
Run()
void ZmqLogger::Run () [override], [virtual]
Runs the ZmqLogger thread.
Implements NamedThread.
References Settings::get(), Settings::getInteger(), KTN::Core::SPSCRingBuffer< T >::size_approx(), and KTN::Core::SPSCRingBuffer< T >::try_dequeue().
WriteLine()
void ZmqLogger::WriteLine (const std::string & msg, const std::string & topic, int color) [virtual]
Writes a log message with the specified topic and color.
Parameters
msg The log message to write.
topic The topic of the log message.
color The color of the log message.
Implements ILogger.
References LogMsg::color, KTN::Core::SPSCRingBuffer< T >::enqueue(), LogLevel::ERROR, LogLevel::INFO, LogMsg::loglevel, LogMsg::msg, and LogMsg::topic.
The documentation for this class was generated from the following files:
Loggers/ZmqLogger.hpp
Loggers/ZmqLogger.cpp