KTN::AlgoBaseV3 Class Reference
The base class for algos, implementing market data callbacks and session management.
#include <AlgoBaseV3.hpp>
Public Member Functions
AlgoBaseV3 (AlgoInitializer params)
Constructs a new AlgoBaseV3 object.
virtual ~AlgoBaseV3 ()
Destructor for AlgoBaseV3.
virtual void Print ()
Prints information about the algorithm instance.
std::string GUID ()
Returns the globally unique identifier (GUID) of the algorithm.
void Poll ()
Polls the system for events.
virtual void onJson (std::string json)=0
Processes a JSON-formatted string.
virtual void onEngineJson (EngineCommand &cmd)
Processes algo engine-specific commands.
virtual void onLaunch (std::string json)=0
Triggered when the algorithm is launched.
virtual void onCalculate ()=0
Performs calculation logic for the algorithm.
virtual void onTrade (int index, double price, double size, int aggressor)
Handles a trade event.
virtual void onMktData (int index)
Handles market data updates.
virtual void onHeartbeat (int msgseqnum)
Handles session heartbeat events.
virtual void onSessionStatus (std::string exch, int mktsegid, int protocol, std::string desc, std::string state)
Handles session status updates.
void onSpreadLegOrderExecution (KTN::Order &ord)
Executes spread leg orders.
virtual void minOrderAck (KTN::OrderPod &ord) override
This method is called when a minimum order acknowledgement is received.
virtual void minOrderCancel (KTN::OrderPod &ord) override
This method is called when a minimum order cancellation is received.
virtual void minOrderModify (KTN::OrderPod &ord) override
This method is called when a minimum order modification is received.
virtual void minOrderExecution (KTN::OrderPod &ord, bool hedgeSent) override
This method is called when a minimum order execution is received.
virtual void minOrderReject (KTN::OrderPod &ord, const std::string &text)
Handles order rejection events.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const std::string &text)
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const std::string &text)
virtual void onHedgeOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price9, uint16_t instindex)
Handles hedge order sent events.
virtual void onOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig)
Handles order sent events.
virtual void Enable (bool bEnable)=0
Enables or disables the algorithm.
virtual void ResetPosition ()
Resets the algorithm's position.
virtual void ToggleCommand (int id)
Toggles a specific command by ID.
virtual void Shutdown ()
Shuts down the algorithm.
virtual void Restart ()
Restarts the algorithm.
virtual void CancelAllOrders ()
Cancels all orders.
virtual void OrderReceived (KTN::Order &ord, int index)
Processes received order events.
virtual void OrderMinUpdate (KTN::OrderPod &ord)
Processes updates for an order. OrderMin is a minimal order object.
void shutdownHandler ()
Shuts down the algorithm handler.
virtual void onMktDataBidAsk (const algomd &md)
Handles bid-ask market data updates.
virtual void onMktDataTrade (const algomd &md)
Handles trade market data updates.
Public Member Functions inherited from KTN::AlgoMktDataCallback
AlgoMktDataCallback ()
Default constructor for AlgoMktDataCallback.
virtual ~AlgoMktDataCallback ()
Virtual destructor for AlgoMktDataCallback.
virtual void onStateChange (int state)
This method is called when the state of the algorithm changes.
Public Member Functions inherited from KTN::SessionCallback
virtual void onSessionStatus (string exch, int mktsegid, int protocol, string desc, string state)=0
This method is called when the session status changes.
virtual void minOrderReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order rejection is received.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancellation rejection is received.
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancel/replace rejection is received.
Public Attributes
std::vector< instrument > _LEGS
Protected Member Functions
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
void Notify (std::string msg, MsgLevel::Enum level, MsgType::Enum msgtype)
void PrintMdMap ()
void PrintBookMap ()
void PrintBook (instrument inst)
void UpdateMetaParams (algometa meta)
void ChangeQuoteState (const QuoteState::Enum &newstate)
void ChangeHedgeState (const HedgeState::Enum &newstate)
void RegisterCallbackId ()
void RegisterParams (std::string json)
void RegisterCmeSecId (instrument &inst)
algomd & GetQuote (const instrument &inst)
bool GetQuote (const instrument &inst, algomd &md)
bool GetQuoteByIndex (int index, algomd &md)
bookmd & GetBook (const instrument &inst)
bool GetBook (const instrument &inst, bookmd &book)
bool RiskCheckQty (int qty, int totalqty, int execqty, KOrderSide::Enum side)
void SendOrder (KTN::OrderPod &ord, instrument &inst)
void SendOrderWithHedge (OrderWithHedge &oh, instrument &inst)
int GetBid (int index)
int GetAsk (int index)
void GetBid (int index, atomicquote &qt)
void GetAsk (int index, atomicquote &qt)
bool isValidSecId (uint32_t secid)
const algomd & findBySecId (int id) const
int indexBySecId (int id)
void GenIds (std::string prefix)
void AddReportingMsg (std::string msg, std::string msgtype)
void AddCmeSymbol (std::string symbol)
std::string getCertSymbol (long secid)
int32_t getCertSecId (std::string symbol)
int32_t getProdSecIdFromCert (long secid)
Protected Attributes
std::atomic< bool > _ACTIVE
IExchangeSender * _ordersender
KtnCmeMdpV4 * _mdh
CmeMsgw _msgw
OrderManagerV5 _Ords
PerformanceTracker _trk
AlgoHelpers helpers
Slacker _SLACK
AlgoV3Reporter * _algorpt
genericstats _mystats
LogMsg _LOG
algometa _PARAMS
int _NUMLEGS
algomd _MD [8]
std::unordered_map< std::string, instrument > _LEGMAP
std::unordered_map< int, instrument > _SECIDMAP
std::unordered_map< long, std::string > _certIdMap
std::unordered_map< std::string, long > _certIdSymbolMap
QuoteState::Enum _QuotingState
HedgeState::Enum _HedgingState
Settings settings_
volatile bool stopped_
int _EXCH_CALLBACK_ID
bool _CME_BY_SECID
bool _bQuoteInFlight
std::string _GUID
std::string _ORG
bool _MEASURE
bool _CERTNR
int _MKT_DATA_CPU
bool _MKT_DATA_OK
bool _GOT_DATA
long _DATA_TRIES
bool _WATCH_TRADES
bool _WATCH_VOLUME
bool _USEAUDIT
bool _ENABLED
bool _CAN_TRADE
bool _HANDLER_STARTED
double _NETPOS
double _TOTALEXEC
bool _USE_REPORTING_MSGS
volatile bool _RPT_ACTIVE
bool _USE_STOPS
bool _CME_MKT_DATA_STARTED
bool _ALLSYMBOLS
std::string _BASE
int _CNT
int _TESTID
int _GROUPCNT
std::string _SPRDID
int _CORE
bool _VERBOSE
std::string m_Name
Detailed Description
The base class for algos, implementing market data callbacks and session management.
This class handles common aspects of algos such as market data callbacks, order management, and session status updates. It is designed to be extended with specific implementations of algorithmic logic.
Constructor & Destructor Documentation
AlgoBaseV3()
KTN::AlgoBaseV3::AlgoBaseV3 (AlgoInitializer params) [explicit]
Constructs a new AlgoBaseV3 object.
Parameters
params Initialization parameters for the algorithm.
References Settings::get(), CmeSettingsHelper::GetBool(), Settings::getInteger(), AlgoInitializer::guid, KT01::MSGW::CmeMsgw::LoadProductGatewayFile(), algometa::Source, KtnCmeMdpV4::Start(), and KtnCmeMdpV4::Subscribe().
~AlgoBaseV3()
KTN::AlgoBaseV3::~AlgoBaseV3 () [virtual]
Destructor for AlgoBaseV3.
Member Function Documentation
AddReportingMsg()
void KTN::AlgoBaseV3::AddReportingMsg (std::string msg, std::string msgtype) [protected]
CancelAllOrders()
void KTN::AlgoBaseV3::CancelAllOrders () [virtual]
Cancels all orders.
ChangeHedgeState()
void KTN::AlgoBaseV3::ChangeHedgeState (const HedgeState::Enum & newstate) [protected]
ChangeQuoteState()
void KTN::AlgoBaseV3::ChangeQuoteState (const QuoteState::Enum & newstate) [protected]
Enable()
virtual void KTN::AlgoBaseV3::Enable (bool bEnable) [pure virtual]
Enables or disables the algorithm.
Parameters
bEnable A boolean indicating whether to enable or disable.
Implemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
Referenced by minOrderReject().
findBySecId()
const algomd & KTN::AlgoBaseV3::findBySecId (int id) const [protected]
GenIds()
void KTN::AlgoBaseV3::GenIds (std::string prefix) [protected]
GetBook() [1/2]
bookmd & KTN::AlgoBaseV3::GetBook (const instrument & inst) [protected]
GetBook() [2/2]
bool KTN::AlgoBaseV3::GetBook (const instrument & inst, bookmd & book) [protected]
GetQuote() [1/2]
algomd & KTN::AlgoBaseV3::GetQuote (const instrument & inst) [protected]
GetQuote() [2/2]
bool KTN::AlgoBaseV3::GetQuote (const instrument & inst, algomd & md) [protected]
GetQuoteByIndex()
bool KTN::AlgoBaseV3::GetQuoteByIndex (int index, algomd & md) [protected]
GUID()
std::string KTN::AlgoBaseV3::GUID () [inline]
Returns the globally unique identifier (GUID) of the algorithm.
Returns
The unique identifier as a string.
indexBySecId()
int KTN::AlgoBaseV3::indexBySecId (int id) [protected]
isValidSecId()
bool KTN::AlgoBaseV3::isValidSecId (uint32_t secid) [protected]
LogMe()
void KTN::AlgoBaseV3::LogMe (std::string szMsg, int iColor = LOG_WHITE) [protected]
minOrderAck()
void KTN::AlgoBaseV3::minOrderAck (KTN::OrderPod & ord) [override], [virtual]
This method is called when a minimum order acknowledgement is received.
Parameters
ord The order details.
Implements KTN::SessionCallback.
References OrderManagerV5::minOrderAck(), and OrderMinUpdate().
minOrderCancel()
void KTN::AlgoBaseV3::minOrderCancel (KTN::OrderPod & ord) [override], [virtual]
This method is called when a minimum order cancellation is received.
Parameters
ord The order details.
Implements KTN::SessionCallback.
Reimplemented in KTN::Stacker.
References OrderManagerV5::minOrderCancel(), and OrderMinUpdate().
minOrderCancelReject()
void KTN::AlgoBaseV3::minOrderCancelReject (KTN::OrderPod & ord, const std::string & text) [virtual]
minOrderCancelReplaceReject()
void KTN::AlgoBaseV3::minOrderCancelReplaceReject (KTN::OrderPod & ord, const std::string & text) [virtual]
minOrderExecution()
void KTN::AlgoBaseV3::minOrderExecution (KTN::OrderPod & ord, bool hedgeSent) [override], [virtual]
This method is called when a minimum order execution is received.
Parameters
ord The order details.
hedgeSent Indicates whether a hedge order was sent.
Implements KTN::SessionCallback.
Reimplemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
minOrderModify()
void KTN::AlgoBaseV3::minOrderModify (KTN::OrderPod & ord) [override], [virtual]
This method is called when a minimum order modification is received.
Parameters
ord The order details.
Implements KTN::SessionCallback.
References OrderManagerV5::minOrderModify(), and OrderMinUpdate().
minOrderReject()
void KTN::AlgoBaseV3::minOrderReject (KTN::OrderPod & ord, const std::string & text) [virtual]
Handles order rejection events.
Parameters
ord The order object that was rejected.
text Reason for rejection.
References Enable(), OrderManagerV5::minOrderReject(), KTN::OrderPod::OrdAction, and OrderMinUpdate().
Notify()
void KTN::AlgoBaseV3::Notify (std::string msg, MsgLevel::Enum level, MsgType::Enum msgtype) [protected]
onCalculate()
virtual void KTN::AlgoBaseV3::onCalculate () [pure virtual]
Performs calculation logic for the algorithm.
Implemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
Referenced by onMktDataBidAsk(), and onMktDataTrade().
onEngineJson()
void KTN::AlgoBaseV3::onEngineJson (EngineCommand & cmd) [virtual]
Processes algo engine-specific commands.
Parameters
cmd The engine command to process.
Reimplemented in KTN::PLWatcher, and KTN::Waves.
onHeartbeat()
void KTN::AlgoBaseV3::onHeartbeat (int msgseqnum) [virtual]
Handles session heartbeat events.
Parameters
msgseqnum Message sequence number.
Implements KTN::SessionCallback.
onHedgeOrderSent()
void KTN::AlgoBaseV3::onHedgeOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price9, uint16_t instindex) [virtual]
Handles hedge order sent events.
Parameters
clordid Client order ID.
reqid Request ID.
secid Security ID.
side Order side.
qty Quantity.
price9 Price.
instindex Instrument index.
Implements KTN::SessionCallback.
Reimplemented in KTN::MultiSpreaderV3, KTN::SkewTrader, KTN::Stacker, and KTN::Waves.
onJson()
virtual void KTN::AlgoBaseV3::onJson (std::string json) [pure virtual]
Processes a JSON-formatted string.
Parameters
json A JSON-formatted string representing algo parameters.
Note
This is a pure virtual function that must be implemented by derived classes.
Implemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
onLaunch()
virtual void KTN::AlgoBaseV3::onLaunch (std::string json) [pure virtual]
Triggered when the algorithm is launched.
Parameters
json A JSON-formatted string representing launch data.
Implemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
onMktData()
void KTN::AlgoBaseV3::onMktData (int index) [virtual]
Handles market data updates.
Parameters
index Market data index.
Reimplemented in KTN::AutoHedgeOB, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, and KTN::Waves.
Referenced by onMktDataBidAsk().
onMktDataBidAsk()
void KTN::AlgoBaseV3::onMktDataBidAsk (const algomd & md) [virtual]
Handles bid-ask market data updates.
Parameters
md The market data structure.
Implements KTN::AlgoMktDataCallback.
References algomd::ask, algomd::bid, algomd::index, onCalculate(), and onMktData().
onMktDataTrade()
void KTN::AlgoBaseV3::onMktDataTrade (const algomd & md) [virtual]
Handles trade market data updates.
Parameters
md The market data structure.
Implements KTN::AlgoMktDataCallback.
References algomd::ask, algomd::bid, algomd::index, algomd::last, algomd::lastagressor, algomd::lastsize, onCalculate(), and onTrade().
onOrderSent()
void KTN::AlgoBaseV3::onOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) [virtual]
Handles order sent events.
Parameters
clordid Client order ID.
reqid Request ID.
secid Security ID.
side Order side.
qty Quantity.
price Price.
trig Order trigger.
Implements KTN::SessionCallback.
Reimplemented in KTN::MultiSpreaderV3, KTN::SkewTrader, KTN::Stacker, and KTN::Waves.
onSessionStatus()
void KTN::AlgoBaseV3::onSessionStatus (std::string exch, int mktsegid, int protocol, std::string desc, std::string state) [virtual]
Handles session status updates.
Parameters
exch Exchange name.
mktsegid Market segment ID.
protocol Protocol number.
desc Description of the session status.
state State of the session.
onSpreadLegOrderExecution()
void KTN::AlgoBaseV3::onSpreadLegOrderExecution (KTN::Order & ord)
Executes spread leg orders.
Parameters
ord Order object containing details of the spread leg.
onTrade()
void KTN::AlgoBaseV3::onTrade (int index, double price, double size, int aggressor) [virtual]
Handles a trade event.
Parameters
index Trade index.
price Trade price.
size Trade size.
aggressor Trade aggressor indicator.
Reimplemented in KTN::AutoHedgeOB, KTN::PLWatcher, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, and KTN::Waves.
Referenced by onMktDataTrade().
OrderMinUpdate()
void KTN::AlgoBaseV3::OrderMinUpdate (KTN::OrderPod & ord) [virtual]
Processes updates for an order. OrderMin is a minimal order object.
Parameters
ord The order pod containing order details.
Reimplemented in KTN::PLWatcher.
Referenced by minOrderAck(), minOrderCancel(), minOrderModify(), and minOrderReject().
OrderReceived()
void KTN::AlgoBaseV3::OrderReceived (KTN::Order & ord, int index = 0) [virtual]
Processes received order events.
Parameters
ord The received order.
index Order index.
Reimplemented in KTN::PLWatcher, and KTN::Waves.
Poll()
void KTN::AlgoBaseV3::Poll ()
Polls the system for events.
Print()
void KTN::AlgoBaseV3::Print () [virtual]
Prints information about the algorithm instance.
Reimplemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
References OrderManagerV5::Print(), and KtnCmeMdpV4::PrintStats().
Referenced by KTN::AutoHedgeOB::Print(), KTN::MultiSpreaderV3::Print(), KTN::PLWatcher::Print(), KTN::Skewer::Print(), KTN::SkewTrader::Print(), KTN::SqueezerOB::Print(), KTN::Twap::Print(), and KTN::Waves::Print().
PrintBook()
void KTN::AlgoBaseV3::PrintBook (instrument inst) [protected]
PrintBookMap()
void KTN::AlgoBaseV3::PrintBookMap () [protected]
PrintMdMap()
void KTN::AlgoBaseV3::PrintMdMap () [protected]
RegisterCallbackId()
void KTN::AlgoBaseV3::RegisterCallbackId () [protected]
RegisterCmeSecId()
void KTN::AlgoBaseV3::RegisterCmeSecId (instrument & inst) [protected]
RegisterParams()
void KTN::AlgoBaseV3::RegisterParams (std::string json) [protected]
ResetPosition()
void KTN::AlgoBaseV3::ResetPosition () [virtual]
Resets the algorithm's position.
Reimplemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
Restart()
void KTN::AlgoBaseV3::Restart () [virtual]
Restarts the algorithm.
Reimplemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
RiskCheckQty()
bool KTN::AlgoBaseV3::RiskCheckQty (int qty, int totalqty, int execqty, KOrderSide::Enum side) [protected]
SendOrder()
void KTN::AlgoBaseV3::SendOrder (KTN::OrderPod & ord, instrument & inst) [protected]
SendOrderWithHedge()
void KTN::AlgoBaseV3::SendOrderWithHedge (OrderWithHedge & oh, instrument & inst) [protected]
Shutdown()
void KTN::AlgoBaseV3::Shutdown () [virtual]
Shuts down the algorithm.
References OrderManagerV5::Stop().
ToggleCommand()
void KTN::AlgoBaseV3::ToggleCommand (int id) [virtual]
Toggles a specific command by ID.
Parameters
id Command ID to toggle.
Reimplemented in KTN::AutoHedgeOB, KTN::MultiSpreaderV3, KTN::PLWatcher, KTN::Skewer, KTN::SkewTrader, KTN::SqueezerOB, KTN::Stacker, KTN::StackerTimer, KTN::Twap, and KTN::Waves.
References OrderManagerV5::Print().
UpdateMetaParams()
void KTN::AlgoBaseV3::UpdateMetaParams (algometa meta) [protected]
Member Data Documentation
_ACTIVE
std::atomic<bool> KTN::AlgoBaseV3::_ACTIVE [protected]
_algorpt
AlgoV3Reporter* KTN::AlgoBaseV3::_algorpt [protected]
_ALLSYMBOLS
bool KTN::AlgoBaseV3::_ALLSYMBOLS [protected]
_BASE
std::string KTN::AlgoBaseV3::_BASE [protected]
_bQuoteInFlight
bool KTN::AlgoBaseV3::_bQuoteInFlight [protected]
_CAN_TRADE
bool KTN::AlgoBaseV3::_CAN_TRADE [protected]
_certIdMap
std::unordered_map<long, std::string> KTN::AlgoBaseV3::_certIdMap [protected]
_certIdSymbolMap
std::unordered_map<std::string, long> KTN::AlgoBaseV3::_certIdSymbolMap [protected]
_CERTNR
bool KTN::AlgoBaseV3::_CERTNR [protected]
_CME_BY_SECID
bool KTN::AlgoBaseV3::_CME_BY_SECID [protected]
_CME_MKT_DATA_STARTED
bool KTN::AlgoBaseV3::_CME_MKT_DATA_STARTED [protected]
_CNT
int KTN::AlgoBaseV3::_CNT [protected]
_CORE
int KTN::AlgoBaseV3::_CORE [protected]
_DATA_TRIES
long KTN::AlgoBaseV3::_DATA_TRIES [protected]
_ENABLED
bool KTN::AlgoBaseV3::_ENABLED [protected]
_EXCH_CALLBACK_ID
int KTN::AlgoBaseV3::_EXCH_CALLBACK_ID [protected]
_GOT_DATA
bool KTN::AlgoBaseV3::_GOT_DATA [protected]
_GROUPCNT
int KTN::AlgoBaseV3::_GROUPCNT [protected]
_GUID
std::string KTN::AlgoBaseV3::_GUID [protected]
_HANDLER_STARTED
bool KTN::AlgoBaseV3::_HANDLER_STARTED [protected]
_HedgingState
HedgeState::Enum KTN::AlgoBaseV3::_HedgingState [protected]
_LEGMAP
std::unordered_map<std::string, instrument> KTN::AlgoBaseV3::_LEGMAP [protected]
_LEGS
std::vector<instrument> KTN::AlgoBaseV3::_LEGS
_LOG
LogMsg KTN::AlgoBaseV3::_LOG [protected]
_MD
algomd KTN::AlgoBaseV3::_MD[8] [protected]
_mdh
KtnCmeMdpV4* KTN::AlgoBaseV3::_mdh [protected]
_MEASURE
bool KTN::AlgoBaseV3::_MEASURE [protected]
_MKT_DATA_CPU
int KTN::AlgoBaseV3::_MKT_DATA_CPU [protected]
_MKT_DATA_OK
bool KTN::AlgoBaseV3::_MKT_DATA_OK [protected]
_msgw
CmeMsgw KTN::AlgoBaseV3::_msgw [protected]
_mystats
genericstats KTN::AlgoBaseV3::_mystats [protected]
_NETPOS
double KTN::AlgoBaseV3::_NETPOS [protected]
_NUMLEGS
int KTN::AlgoBaseV3::_NUMLEGS [protected]
_ordersender
IExchangeSender* KTN::AlgoBaseV3::_ordersender [protected]
_Ords
OrderManagerV5 KTN::AlgoBaseV3::_Ords [protected]
_ORG
std::string KTN::AlgoBaseV3::_ORG [protected]
_PARAMS
algometa KTN::AlgoBaseV3::_PARAMS [protected]
_QuotingState
QuoteState::Enum KTN::AlgoBaseV3::_QuotingState [protected]
_RPT_ACTIVE
volatile bool KTN::AlgoBaseV3::_RPT_ACTIVE [protected]
_SECIDMAP
std::unordered_map<int, instrument> KTN::AlgoBaseV3::_SECIDMAP [protected]
_SLACK
Slacker KTN::AlgoBaseV3::_SLACK [protected]
_SPRDID
std::string KTN::AlgoBaseV3::_SPRDID [protected]
_TESTID
int KTN::AlgoBaseV3::_TESTID [protected]
_TOTALEXEC
double KTN::AlgoBaseV3::_TOTALEXEC [protected]
_trk
PerformanceTracker KTN::AlgoBaseV3::_trk [protected]
_USE_REPORTING_MSGS
bool KTN::AlgoBaseV3::_USE_REPORTING_MSGS [protected]
_USE_STOPS
bool KTN::AlgoBaseV3::_USE_STOPS [protected]
_USEAUDIT
bool KTN::AlgoBaseV3::_USEAUDIT [protected]
_VERBOSE
bool KTN::AlgoBaseV3::_VERBOSE [protected]
_WATCH_TRADES
bool KTN::AlgoBaseV3::_WATCH_TRADES [protected]
_WATCH_VOLUME
bool KTN::AlgoBaseV3::_WATCH_VOLUME [protected]
helpers
AlgoHelpers KTN::AlgoBaseV3::helpers [protected]
m_Name
std::string KTN::AlgoBaseV3::m_Name [protected]
settings_
Settings KTN::AlgoBaseV3::settings_ [protected]
stopped_
volatile bool KTN::AlgoBaseV3::stopped_ [protected]
The documentation for this class was generated from the following files:
Algos/AlgoBaseV3.hpp
Algos/AlgoBaseV3.cpp