IExchangeSender Class Reference
The interface for sending messages to the exchange.
#include <IExchangeSender.hpp>
Public Member Functions
IExchangeSender ()
Default constructor.
virtual ~IExchangeSender ()
Destructor.
virtual int Subscribe (SessionCallback *cb)=0
Subscribe to the exchange session.
virtual void Send (KTN::OrderPod &ord, int action)=0
Send an order to the exchange.
virtual void SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > &hdg)=0
Send a hedge instruction to the exchange.
virtual void SendOrderWithHedge (OrderWithHedge &oh)=0
Send an order with hedge to the exchange.
virtual void BankHedgeOrders (uint64_t ordereqid, const vector< KTN::OrderPod > &ords)=0
Bank hedge orders.
virtual void BankTas (std::string secgrp, vector< KTN::OrderPod > ords)=0
Bank TAS orders.
virtual void AlgoJson (std::string json, ExchCmd::Enum cmd)=0
Send an algorithm JSON command to the exchange.
Detailed Description
The interface for sending messages to the exchange.
Constructor & Destructor Documentation
IExchangeSender()
IExchangeSender::IExchangeSender ()
Default constructor.
~IExchangeSender()
IExchangeSender::~IExchangeSender () [virtual]
Destructor.
Member Function Documentation
AlgoJson()
virtual void IExchangeSender::AlgoJson (std::string json, ExchCmd::Enum cmd) [pure virtual]
Send an algorithm JSON command to the exchange.
Parameters
json The JSON string.
cmd The exchange command.
Implemented in Raptor2.
Referenced by KTN::AlgoServiceBrokerV3::onAlgoCommand().
BankHedgeOrders()
virtual void IExchangeSender::BankHedgeOrders (uint64_t ordereqid, const vector< KTN::OrderPod > & ords) [pure virtual]
Bank hedge orders.
Parameters
ordereqid The order request ID.
ords The order pod vector.
Implemented in Raptor2.
BankTas()
virtual void IExchangeSender::BankTas (std::string secgrp, vector< KTN::OrderPod > ords) [pure virtual]
Bank TAS orders.
Parameters
secgrp The security group.
ords The order pod vector.
Implemented in Raptor2.
Referenced by KTN::ORD::OrderHandlerZmqV6::LoadTasOrders().
Send()
virtual void IExchangeSender::Send (KTN::OrderPod & ord, int action) [pure virtual]
Send an order to the exchange.
Parameters
ord The order to send.
action The action to perform on the order.
Implemented in Raptor2.
Referenced by KTN::SqueezerOB::onJson(), KTN::PLWatcher::onPL(), KTN::PLWatcher::OrderReceived(), and KTN::Waves::OrderReceived().
SendHedgeInstruction()
virtual void IExchangeSender::SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > & hdg) [pure virtual]
Send a hedge instruction to the exchange.
Parameters
ordereqid The order request ID.
hdg The spread hedge vector.
Implemented in Raptor2.
SendOrderWithHedge()
virtual void IExchangeSender::SendOrderWithHedge (OrderWithHedge & oh) [pure virtual]
Send an order with hedge to the exchange.
Parameters
oh The order with hedge.
Implemented in Raptor2.
Subscribe()
virtual int IExchangeSender::Subscribe (SessionCallback * cb) [pure virtual]
Subscribe to the exchange session.
Parameters
cb The session callback object.
Returns
The result of the subscription.
Implemented in Raptor2.
The documentation for this class was generated from the following files:
ExchangeHandlers2/IExchangeSender.hpp
ExchangeHandlers2/IExchangeSender.cpp