PerformanceTracker Class Reference
Class for tracking performance measurements.
#include <PerformanceTracker.hpp>
Public Member Functions
void startMeasurement (const std::string &name)
Start a new performance measurement with the given name.
void stopMeasurement (const std::string &name)
Stop the performance measurement with the given name.
void printMeasurements ()
Print the stats for all measurements.
void clear ()
Clear all performance measurements.
Detailed Description
Class for tracking performance measurements.
Member Function Documentation
clear()
void PerformanceTracker::clear () [inline]
Clear all performance measurements.
Referenced by KTN::MultiSpreaderV3::Print(), KTN::Skewer::Print(), KTN::SkewTrader::Print(), KTN::Twap::Print(), KTN::CME::CmeAlgo::PrintLatencies(), KTN::CME::CmeGT5::PrintLatencies(), KTN::ExchangeBase2::PrintLatencies(), and KTN::TCP::EFVITcpV2::SendEFVI_Delegated().
printMeasurements()
void PerformanceTracker::printMeasurements () [inline]
Print the stats for all measurements.
Referenced by KTN::AutoHedgeOB::Print(), KTN::MultiSpreaderV3::Print(), KTN::Skewer::Print(), KTN::SkewTrader::Print(), KTN::SqueezerOB::Print(), KTN::Twap::Print(), KTN::CME::CmeAlgo::PrintLatencies(), KTN::CME::CmeGT5::PrintLatencies(), KTN::ExchangeBase2::PrintLatencies(), KtnCmeMbo::PrintStats(), KtnCmeMdpV4::PrintStats(), and KTN::TCP::EFVITcpV2::SendEFVI_Delegated().
startMeasurement()
void PerformanceTracker::startMeasurement (const std::string & name) [inline]
Start a new performance measurement with the given name.
Parameters
name The name of the performance measurement.
Referenced by KTN::CME::CmeAlgo::onRecv(), KTN::CME::CmeGT5::onRecv(), KTN::CME::CmeAlgo::Send(), KTN::CME::CmeGT5::Send(), KTN::TCP::EFVITcpV2::SendEFVI_Delegated(), and KTN::CME::CmeGT5::SendHedgeInstruction().
stopMeasurement()
void PerformanceTracker::stopMeasurement (const std::string & name) [inline]
Stop the performance measurement with the given name.
Parameters
name The name of the performance measurement.
Referenced by KTN::CME::CmeAlgo::onRecv(), KTN::CME::CmeGT5::onRecv(), KTN::CME::CmeAlgo::Send(), KTN::CME::CmeGT5::Send(), KTN::TCP::EFVITcpV2::SendEFVI_Delegated(), and KTN::CME::CmeGT5::SendHedgeInstruction().
The documentation for this class was generated from the following file:
Core/PerformanceTracker.hpp