rapidxml::xml_base< Ch > Class Template Reference
#include <rapidxml.hpp>
Public Member Functions
Ch * name () const
std::size_t name_size () const
Ch * value () const
std::size_t value_size () const
void name (const Ch *name, std::size_t size)
void name (const Ch *name)
void value (const Ch *value, std::size_t size)
void value (const Ch *value)
xml_node< Ch > * parent () const
Static Protected Member Functions
static Ch * nullstr ()
Protected Attributes
Ch * m_name
Ch * m_value
std::size_t m_name_size
std::size_t m_value_size
xml_node< Ch > * m_parent
Detailed Description
template<class Ch = char>
class rapidxml::xml_base< Ch >
Base class for xml_node and xml_attribute implementing common functions: name(), name_size(), value(), value_size() and parent().
Parameters
Ch Character type to use
Constructor & Destructor Documentation
xml_base()
template<class Ch = char>
rapidxml::xml_base< Ch >::xml_base () [inline]
Member Function Documentation
name() [1/3]
template<class Ch = char>
Ch * rapidxml::xml_base< Ch >::name () const [inline]
Gets name of the node. Interpretation of name depends on type of node. Note that name will not be zero-terminated if rapidxml::parse_no_string_terminators option was selected during parse.
 Use name_size() function to determine length of the name.
Returns
Name of node, or empty string if node has no name.
Referenced by rapidxml::memory_pool< Ch >::allocate_attribute(), rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::memory_pool< Ch >::clone_node(), rapidxml::xml_base< Ch >::name(), and rapidxml::xml_base< Ch >::name().
name() [2/3]
template<class Ch = char>
void rapidxml::xml_base< Ch >::name (const Ch * name) [inline]
Sets name of node to a zero-terminated string. See also ownership_of_strings and xml_node::name(const Ch *, std::size_t).
Parameters
name Name of node to set. Must be zero terminated.
References rapidxml::xml_base< Ch >::name().
name() [3/3]
template<class Ch = char>
void rapidxml::xml_base< Ch >::name (const Ch * name, std::size_t size) [inline]
Sets name of node to a non zero-terminated string. See ownership_of_strings.
 Note that node does not own its name or value, it only stores a pointer to it. It will not delete or otherwise free the pointer on destruction. It is reponsibility of the user to properly manage lifetime of the string. The easiest way to achieve it is to use memory_pool of the document to allocate the string - on destruction of the document the string will be automatically freed.
 Size of name must be specified separately, because name does not have to be zero terminated. Use name(const Ch *) function to have the length automatically calculated (string must be zero terminated).
Parameters
name Name of node to set. Does not have to be zero terminated.
size Size of name, in characters. This does not include zero terminator, if one is present.
References rapidxml::xml_base< Ch >::name().
name_size()
template<class Ch = char>
std::size_t rapidxml::xml_base< Ch >::name_size () const [inline]
Gets size of node name, not including terminator character. This function works correctly irrespective of whether name is or is not zero terminated.
Returns
Size of node name, in characters.
Referenced by rapidxml::memory_pool< Ch >::clone_node().
nullstr()
template<class Ch = char>
static Ch * rapidxml::xml_base< Ch >::nullstr () [inline], [static], [protected]
parent()
template<class Ch = char>
xml_node< Ch > * rapidxml::xml_base< Ch >::parent () const [inline]
Gets node parent.
Returns
Pointer to parent node, or 0 if there is no parent.
Referenced by rapidxml::xml_node< Ch >::append_attribute(), rapidxml::xml_node< Ch >::append_node(), rapidxml::xml_node< Ch >::document(), rapidxml::xml_node< Ch >::insert_attribute(), rapidxml::xml_node< Ch >::insert_node(), rapidxml::xml_node< Ch >::prepend_attribute(), rapidxml::xml_node< Ch >::prepend_node(), rapidxml::xml_node< Ch >::remove_attribute(), and rapidxml::xml_node< Ch >::remove_node().
value() [1/3]
template<class Ch = char>
Ch * rapidxml::xml_base< Ch >::value () const [inline]
Gets value of node. Interpretation of value depends on type of node. Note that value will not be zero-terminated if rapidxml::parse_no_string_terminators option was selected during parse.
 Use value_size() function to determine length of the value.
Returns
Value of node, or empty string if node has no value.
Referenced by rapidxml::memory_pool< Ch >::allocate_attribute(), rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::memory_pool< Ch >::clone_node(), rapidxml::xml_base< Ch >::value(), and rapidxml::xml_base< Ch >::value().
value() [2/3]
template<class Ch = char>
void rapidxml::xml_base< Ch >::value (const Ch * value) [inline]
Sets value of node to a zero-terminated string. See also ownership_of_strings and xml_node::value(const Ch *, std::size_t).
Parameters
value Vame of node to set. Must be zero terminated.
References rapidxml::xml_base< Ch >::value().
value() [3/3]
template<class Ch = char>
void rapidxml::xml_base< Ch >::value (const Ch * value, std::size_t size) [inline]
Sets value of node to a non zero-terminated string. See ownership_of_strings.
 Note that node does not own its name or value, it only stores a pointer to it. It will not delete or otherwise free the pointer on destruction. It is reponsibility of the user to properly manage lifetime of the string. The easiest way to achieve it is to use memory_pool of the document to allocate the string - on destruction of the document the string will be automatically freed.
 Size of value must be specified separately, because it does not have to be zero terminated. Use value(const Ch *) function to have the length automatically calculated (string must be zero terminated).
 If an element has a child node of type node_data, it will take precedence over element value when printing. If you want to manipulate data of elements using values, use parser flag rapidxml::parse_no_data_nodes to prevent creation of data nodes by the parser.
Parameters
value value of node to set. Does not have to be zero terminated.
size Size of value, in characters. This does not include zero terminator, if one is present.
References rapidxml::xml_base< Ch >::value().
value_size()
template<class Ch = char>
std::size_t rapidxml::xml_base< Ch >::value_size () const [inline]
Gets size of node value, not including terminator character. This function works correctly irrespective of whether value is or is not zero terminated.
Returns
Size of node value, in characters.
Referenced by rapidxml::memory_pool< Ch >::clone_node().
Member Data Documentation
m_name
template<class Ch = char>
Ch* rapidxml::xml_base< Ch >::m_name [protected]
m_name_size
template<class Ch = char>
std::size_t rapidxml::xml_base< Ch >::m_name_size [protected]
m_parent
template<class Ch = char>
xml_node<Ch>* rapidxml::xml_base< Ch >::m_parent [protected]
m_value
template<class Ch = char>
Ch* rapidxml::xml_base< Ch >::m_value [protected]
m_value_size
template<class Ch = char>
std::size_t rapidxml::xml_base< Ch >::m_value_size [protected]
The documentation for this class was generated from the following file:
C:/Users/sgaer/source/repos/katanafinancial/OccamCME4/OccamCME4/src/external/rapidxml/rapidxml.hpp