KTN::NET::KTNPktBuf Class Reference
Represents a packet buffer used in the KTNPktBuf class.
#include <KTNPktBuf.hpp>
Public Member Functions
size_t index ()
Returns the index of the packet buffer.
size_t size ()
Returns the size of the packet buffer.
const char * data () const
Returns a constant pointer to the data in the packet buffer.
char * data ()
Returns a pointer to the data in the packet buffer.
const char * operator[] (int n) const
Returns a constant pointer to the data at the specified index in the packet buffer.
char * operator[] (int n)
Returns a pointer to the data at the specified index in the packet buffer.
Static Public Member Functions
static constexpr size_t capacity ()
Returns the capacity of the packet buffer.
static constexpr size_t alloc_size ()
Returns the allocation size of the packet buffer.
Detailed Description
Represents a packet buffer used in the KTNPktBuf class.
Member Function Documentation
alloc_size()
static constexpr size_t KTN::NET::KTNPktBuf::alloc_size () [inline], [static], [constexpr]
Returns the allocation size of the packet buffer.
Returns
The allocation size of the packet buffer.
capacity()
static constexpr size_t KTN::NET::KTNPktBuf::capacity () [inline], [static], [constexpr]
Returns the capacity of the packet buffer.
Returns
The capacity of the packet buffer.
data() [1/2]
char * KTN::NET::KTNPktBuf::data () [inline]
Returns a pointer to the data in the packet buffer.
Returns
A pointer to the data in the packet buffer.
data() [2/2]
const char * KTN::NET::KTNPktBuf::data () const [inline]
Returns a constant pointer to the data in the packet buffer.
Returns
A constant pointer to the data in the packet buffer.
Referenced by operator[](), and operator[]().
index()
size_t KTN::NET::KTNPktBuf::index () [inline]
Returns the index of the packet buffer.
Returns
The index of the packet buffer.
operator[]() [1/2]
char * KTN::NET::KTNPktBuf::operator[] (int n) [inline]
Returns a pointer to the data at the specified index in the packet buffer.
Parameters
n The index of the data.
Returns
A pointer to the data at the specified index in the packet buffer.
References data().
operator[]() [2/2]
const char * KTN::NET::KTNPktBuf::operator[] (int n) const [inline]
Returns a constant pointer to the data at the specified index in the packet buffer.
Parameters
n The index of the data.
Returns
A constant pointer to the data at the specified index in the packet buffer.
References data().
size()
size_t KTN::NET::KTNPktBuf::size () [inline]
Returns the size of the packet buffer.
Returns
The size of the packet buffer.
The documentation for this class was generated from the following file:
Core/KTNPktBuf.hpp