ZmqMenu Class Reference
The ZmqMenu class represents a menu that uses ZeroMQ for communication.
#include <ZmqMenu.hpp>
Public Member Functions
ZmqMenu (MenuCallback &callback, std::string file, std::string name)
Constructs a ZmqMenu object.
virtual ~ZmqMenu ()
Destroys the ZmqMenu object.
void DisplayAndWait ()
Displays the menu and waits for user input.
void Run () override
Runs the menu in a separate thread.
Public Member Functions inherited from IMenu
virtual ~IMenu ()=default
Virtual destructor.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The ZmqMenu class represents a menu that uses ZeroMQ for communication.
Constructor & Destructor Documentation
ZmqMenu()
ZmqMenu::ZmqMenu (MenuCallback & callback, std::string file, std::string name)
Constructs a ZmqMenu object.
Parameters
callback The MenuCallback object to handle menu events.
file The file associated with the menu.
name The name of the menu.
~ZmqMenu()
ZmqMenu::~ZmqMenu () [virtual]
Destroys the ZmqMenu object.
Member Function Documentation
DisplayAndWait()
void ZmqMenu::DisplayAndWait () [virtual]
Displays the menu and waits for user input.
Implements IMenu.
References NamedThread::CreateAndRun().
Run()
void ZmqMenu::Run () [override], [virtual]
Runs the menu in a separate thread.
Implements NamedThread.
References MenuCallback::onMenuChoice(), and StringSplitter::Split().
The documentation for this class was generated from the following files:
Menu/ZmqMenu.hpp
Menu/ZmqMenu.cpp