KTN::Core::BufferPoolV2 Class Reference
The BufferPoolV2 class represents a buffer pool for managing KTNPktBuf objects.
#include <BufferPoolV2.hpp>
Public Member Functions
BufferPoolV2 (size_t buffer_size, size_t pool_size)
Constructs a BufferPoolV2 object with the specified buffer size and pool size.
~BufferPoolV2 ()
Destroys the BufferPoolV2 object.
KTNPktBuf * get ()
Retrieves a buffer from the pool.
bool put (KTNPktBuf *buffer)
Returns a buffer to the pool.
size_t size ()
Returns the current size of the pool.
void Load ()
Loads the buffer pool.
Detailed Description
The BufferPoolV2 class represents a buffer pool for managing KTNPktBuf objects.
Constructor & Destructor Documentation
BufferPoolV2()
BufferPoolV2::BufferPoolV2 (size_t buffer_size, size_t pool_size)
Constructs a BufferPoolV2 object with the specified buffer size and pool size.
Parameters
buffer_size The size of each buffer in the pool.
pool_size The maximum number of buffers in the pool.
References Load().
~BufferPoolV2()
BufferPoolV2::~BufferPoolV2 ()
Destroys the BufferPoolV2 object.
Member Function Documentation
get()
KTNPktBuf * BufferPoolV2::get ()
Retrieves a buffer from the pool.
Returns
A pointer to the retrieved buffer, or nullptr if the pool is empty.
References Load().
Load()
void BufferPoolV2::Load ()
Loads the buffer pool.
Referenced by BufferPoolV2(), and get().
put()
bool BufferPoolV2::put (KTNPktBuf * buffer)
Returns a buffer to the pool.
Parameters
buffer A pointer to the buffer to be returned.
Returns
True if the buffer was successfully returned, false otherwise.
size()
size_t KTN::Core::BufferPoolV2::size () [inline]
Returns the current size of the pool.
Returns
The current size of the pool.
The documentation for this class was generated from the following files:
Core/BufferPoolV2.hpp
Core/BufferPoolV2.cpp