LogSvc Class Reference
The LogSvc class is responsible for logging messages. This is a thread-safe class that offloads messages to a ring buffer and then logs them to the console or another dstination.
#include <LogSvc.hpp>
Public Member Functions
LogSvc (const string &owner, const string &source)
Constructs a LogSvc object with the specified owner and source.
virtual ~LogSvc ()
Destroys the LogSvc object.
void ChangeName (const string &newname, const string &source)
Changes the name and source of the LogSvc object.
void Start ()
Starts the logging service.
void LogMe (const LogMsg &msg)
Logs the specified LogMsg object.
void LogMe (const string &msg, int icolor)
Logs the specified message with the specified color.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The LogSvc class is responsible for logging messages. This is a thread-safe class that offloads messages to a ring buffer and then logs them to the console or another dstination.
Constructor & Destructor Documentation
LogSvc()
LogSvc::LogSvc (const string & owner, const string & source)
Constructs a LogSvc object with the specified owner and source.
Parameters
owner The owner of the LogSvc object.
source The source of the LogSvc object.
~LogSvc()
LogSvc::~LogSvc () [virtual]
Destroys the LogSvc object.
Member Function Documentation
ChangeName()
void LogSvc::ChangeName (const string & newname, const string & source)
Changes the name and source of the LogSvc object.
Parameters
newname The new name of the LogSvc object.
source The new source of the LogSvc object.
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
LogMe() [1/2]
void LogSvc::LogMe (const LogMsg & msg)
Logs the specified LogMsg object.
Parameters
msg The LogMsg object to be logged.
References KTN::Core::SPSCRingBuffer< T >::enqueue().
Referenced by KTN::ExchangeBase2::LogMe().
LogMe() [2/2]
void LogSvc::LogMe (const string & msg, int icolor)
Logs the specified message with the specified color.
Parameters
msg The message to be logged.
icolor The color of the log message.
Start()
void LogSvc::Start ()
Starts the logging service.
The documentation for this class was generated from the following files:
Loggers/LogSvc.hpp
Loggers/LogSvc.cpp