KTN::REPORTER::AlgoPLReporter Class Reference
The AlgoPLReporter class is responsible for reporting the position data.
#include <AlgoPLReporter.hpp>
Public Member Functions
AlgoPLReporter (string guid)
Constructs an AlgoPLReporter object with the specified GUID.
~AlgoPLReporter ()
Destroys the AlgoPLReporter object.
void Report (Position &data)
Reports the position data.
virtual void DoWork () override
Performs the work of the reporter.
void StopWork ()
Stops the work of the reporter.
Detailed Description
The AlgoPLReporter class is responsible for reporting the position data.
Constructor & Destructor Documentation
AlgoPLReporter()
AlgoPLReporter::AlgoPLReporter (string guid)
Constructs an AlgoPLReporter object with the specified GUID.
Parameters
guid The GUID of the reporter.
References KTN::REPORTER::ReporterBase::Start().
~AlgoPLReporter()
AlgoPLReporter::~AlgoPLReporter ()
Destroys the AlgoPLReporter object.
Member Function Documentation
DoWork()
void AlgoPLReporter::DoWork () [override], [virtual]
Performs the work of the reporter.
Implements KTN::REPORTER::ReporterBase.
References KTN::Core::SPSCRingBuffer< T >::empty(), KTN::REPORTER::ReporterBase::getSsboeUs(), KTN::REPORTER::ReporterBase::getTimeString(), KTN::REPORTER::ReporterBase::SendJson(), and KTN::Core::SPSCRingBuffer< T >::try_pop().
Report()
void AlgoPLReporter::Report (Position & data)
Reports the position data.
Parameters
data The position data to be reported.
References KTN::Core::SPSCRingBuffer< T >::push().
StopWork()
void AlgoPLReporter::StopWork ()
Stops the work of the reporter.
References KTN::REPORTER::ReporterBase::Stop().
The documentation for this class was generated from the following files:
Reporters/AlgoPLReporter.hpp
Reporters/AlgoPLReporter.cpp