Settings Class Reference
Settings collection.
#include <Settings.h>
Public Member Functions
Settings ()
Settings (const std::string filename)
~Settings (void)
void Get (const std::string &filePath, std::string szMe)
void Dump ()
vector< string > LogDump (int indent)
std::string get (const std::string &key) const
bool getInteger (const std::string &key, int *value) const
int getInteger (const std::string &key) const
bool getLong (const std::string &key, long *value) const
long getLong (const std::string &key) const
bool getBoolean (const std::string &key) const
bool getDouble (const::std::string &key, double *value) const
double getDouble (const std::string &key) const
vector< string > getListCsv (const std::string &key) const
map< std::string, std::string > GetMap ()
Static Public Member Functions
static void trimSpaces (std::string *str)
Protected Types
typedef std::map< std::string, std::string > Key2ValueMap
Protected Attributes
Key2ValueMap map_
std::string m_Me
std::string m_FilePath
Detailed Description
Settings collection.
Member Typedef Documentation
Key2ValueMap
std::map<std::string , std::string > Settings::Key2ValueMap [protected]
Constructor & Destructor Documentation
Settings() [1/2]
Settings::Settings ()
Default constructor for the Settings class.
Settings() [2/2]
Settings::Settings (const std::string filename)
Constructor for the Settings class that takes a filename.
Parameters
filename The name of the file to load settings from.
References trimSpaces().
~Settings()
Settings::~Settings (void)
Destructor for the Settings class.
Member Function Documentation
Dump()
void Settings::Dump ()
Dump all the settings to the console.
Get()
void Settings::Get (const std::string & filePath, std::string szMe)
Get the value associated with the given key from the specified file.
Parameters
filePath The path of the file to read settings from.
szMe The key to retrieve the value for.
References trimSpaces().
get()
std::string Settings::get (const std::string & key) const
Get the value associated with the given key.
Parameters
key The key to retrieve the value for.
Returns
The value associated with the key.
Referenced by KTN::AlgoBaseV3::AlgoBaseV3(), KTN::AlgoServiceBrokerV3::AlgoServiceBrokerV3(), KTN::REPORTER::AlgoV3Reporter::AlgoV3Reporter(), KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), LoggerFactory::createLogger(), MenuFactory::createMenu(), KTN::ExchangeManager::ExchangeManager(), getBoolean(), getInteger(), getListCsv(), getLong(), CmeSettingsHelper::GetString(), SessionStateManager::Init(), KTN::notify::Slacker::InitAndRun(), CmeSessionSettings::Load(), tcp_settings::Load(), udp_settings::Load(), KTN::ORD::OrderHandlerZmqV6::LoadTasOrders(), KTN::ORD::OrderHandlerZmqV6::OrderHandlerZmqV6(), KTN::REPORTER::OrderReporterV5::OrderReporterV5(), ZmqLogger::Run(), KTN::REPORTER::ReporterBase::Start(), KTN::REPORTER::StatusReporter::StatusReporter(), and ZmqLogger::ZmqLogger().
getBoolean()
bool Settings::getBoolean (const std::string & key) const
Get the boolean value associated with the given key.
Parameters
key The key to retrieve the value for.
Returns
The boolean value associated with the key.
References get().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), CmeSettingsHelper::GetBool(), SessionStateManager::Init(), CmeSessionSettings::Load(), tcp_settings::Load(), udp_settings::Load(), and KTN::ORD::OrderHandlerZmqV6::OrderHandlerZmqV6().
getDouble() [1/2]
double Settings::getDouble (const std::string & key) const
Get the double value associated with the given key.
Parameters
key The key to retrieve the value for.
Returns
The double value associated with the key.
References getDouble().
getDouble() [2/2]
bool Settings::getDouble (const::std::string & key, double * value) const
Get the double value associated with the given key.
Parameters
key The key to retrieve the value for.
value A pointer to store the retrieved double value.
Returns
True if the value was successfully retrieved, false otherwise.
Referenced by getDouble().
getInteger() [1/2]
int Settings::getInteger (const std::string & key) const
Get the integer value associated with the given key.
Parameters
key The key to retrieve the value for.
Returns
The integer value associated with the key.
References getInteger().
getInteger() [2/2]
bool Settings::getInteger (const std::string & key, int * value) const
Get the integer value associated with the given key.
Parameters
key The key to retrieve the value for.
value A pointer to store the retrieved integer value.
Returns
True if the value was successfully retrieved, false otherwise.
References get().
Referenced by KTN::AlgoBaseV3::AlgoBaseV3(), KTN::AlgoServiceBrokerV3::AlgoServiceBrokerV3(), KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), KTN::ExchangeManager::ExchangeManager(), CmeSettingsHelper::GetInt(), getInteger(), SessionStateManager::Init(), CmeSessionSettings::Load(), tcp_settings::Load(), udp_settings::Load(), KTN::ORD::OrderHandlerZmqV6::LoadTasOrders(), KTN::ORD::OrderHandlerZmqV6::OrderHandlerZmqV6(), ZmqLogger::Run(), KTN::REPORTER::ReporterBase::Start(), and KTN::REPORTER::StatusReporter::StatusReporter().
getListCsv()
vector< string > Settings::getListCsv (const std::string & key) const
Get the list of values associated with the given key, separated by commas.
Parameters
key The key to retrieve the list for.
Returns
A vector of strings containing the values in the list.
References get(), and StringSplitter::Split().
Referenced by ZmqSubscriber::Init(), ZmqSubscriber::LoadTopics(), and ZmqSubscriberV5::LoadTopics().
getLong() [1/2]
long Settings::getLong (const std::string & key) const
Get the long value associated with the given key.
Parameters
key The key to retrieve the value for.
Returns
The long value associated with the key.
References getLong().
getLong() [2/2]
bool Settings::getLong (const std::string & key, long * value) const
Get the long value associated with the given key.
Parameters
key The key to retrieve the value for.
value A pointer to store the retrieved long value.
Returns
True if the value was successfully retrieved, false otherwise.
References get().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), CmeSettingsHelper::GetLong(), getLong(), SessionStateManager::Init(), and CmeSessionSettings::Load().
GetMap()
map< std::string, std::string > Settings::GetMap () [inline]
Get the map of all settings.
Returns
A map containing all the settings.
LogDump()
vector< string > Settings::LogDump (int indent)
Dump all the settings to a vector of strings with indentation.
Parameters
indent The number of spaces to indent each setting.
Returns
A vector of strings containing the dumped settings.
trimSpaces()
void Settings::trimSpaces (std::string * str) [static]
Trim leading and trailing spaces from the given string.
Parameters
str The string to trim.
Referenced by Get(), and Settings().
Member Data Documentation
m_FilePath
std::string Settings::m_FilePath [protected]
m_Me
std::string Settings::m_Me [protected]
map_
Key2ValueMap Settings::map_ [protected]
The documentation for this class was generated from the following files:
Settings/Settings.h
Settings/Settings.cpp