KTN::TCP::EFVITcpV2 Class Reference
The EFVITcpV2 class represents a TCP client making use of OpenOnload, TCP socket EPOLL, and EFVI. The class was originally designed for TAS order release.
#include <EFVITcpV2.hpp>
Public Member Functions
EFVITcpV2 ()
Default constructor.
virtual ~EFVITcpV2 ()
Destructor.
void EFVI_TCP_Start (int fd)
Starts the EFVI TCP client.
void createEfviTcpFeedFilter (ServiceDescriptor &feed)
Creates an EFVI TCP feed filter.
bool Init (ServiceDescriptor &desc, bool isA)
Initializes the EFVI TCP client.
void Subscribe (TcpCallback *callback)
Subscribes to TCP callbacks.
void Stop ()
Stops the EFVI TCP client.
void Poll ()
Polls for events.
void SendMaster (char *buffer, size_t buffer_length, bool send_delegated)
Sends a master message.
int SendEFVI_Delegated (char *buffer, size_t buffer_length)
Sends an EFVI delegated message.
int SendNormal (char *buffer, size_t buffer_length)
Sends a normal message.
void SendWarmup ()
Sends warmup messages.
bool tas_send ()
Sends a TAS message.
bool tas_prepare (const KTN_MSG &msg)
Prepares a TAS message.
int Fd ()
Gets the file descriptor of the TCP connection.
int SegId ()
Gets the segment ID.
uint64_t Warmups ()
Gets the number of warmup messages sent.
Detailed Description
The EFVITcpV2 class represents a TCP client making use of OpenOnload, TCP socket EPOLL, and EFVI. The class was originally designed for TAS order release.
Constructor & Destructor Documentation
EFVITcpV2()
EFVITcpV2::EFVITcpV2 ()
Default constructor.
~EFVITcpV2()
EFVITcpV2::~EFVITcpV2 () [virtual]
Destructor.
Member Function Documentation
createEfviTcpFeedFilter()
void EFVITcpV2::createEfviTcpFeedFilter (ServiceDescriptor & feed)
Creates an EFVI TCP feed filter.
Parameters
feed The service descriptor for the feed.
References KTN::TCP::ServiceDescriptor::address, KTN::TCP::ServiceDescriptor::localinterface, KTN::TCP::ServiceDescriptor::localinterfacename, KTN::TCP::ServiceDescriptor::port, and KTN::TCP::ServiceDescriptor::sa_tcplocal.
Referenced by Init().
EFVI_TCP_Start()
void EFVITcpV2::EFVI_TCP_Start (int fd)
Starts the EFVI TCP client.
Parameters
fd The file descriptor of the TCP connection.
References tcp_settings::MsgBufSize, and tcp_settings::RxCapacity.
Referenced by Init().
Fd()
int KTN::TCP::EFVITcpV2::Fd () [inline]
Gets the file descriptor of the TCP connection.
Returns
The file descriptor.
Init()
bool EFVITcpV2::Init (ServiceDescriptor & desc, bool isA = true)
Initializes the EFVI TCP client.
Parameters
desc The service descriptor for the client.
isA A flag indicating if the client is A.
Returns
True if initialization is successful, false otherwise.
References KTN::TCP::Epoller::AddSocket(), createEfviTcpFeedFilter(), KTN::TCP::Epoller::CreateEpoll(), EFVI_TCP_Start(), KTN::TCP::ServiceDescriptor::feedtype, tcp_settings::IntfA, tcp_settings::IntfB, tcp_settings::IntfNameA, tcp_settings::IntfNameB, KTN::TCP::ServiceDescriptor::iSource, tcp_settings::Load(), KTN::TCP::ServiceDescriptor::localinterface, KTN::TCP::ServiceDescriptor::localinterfacename, tcp_settings::UseCtpio, and tcp_settings::UseDelSends.
Poll()
void EFVITcpV2::Poll ()
Polls for events.
SegId()
int KTN::TCP::EFVITcpV2::SegId () [inline]
Gets the segment ID.
Returns
The segment ID.
SendEFVI_Delegated()
int EFVITcpV2::SendEFVI_Delegated (char * buffer, size_t buffer_length)
Sends an EFVI delegated message.
Parameters
buffer The buffer containing the message.
buffer_length The length of the buffer.
Returns
The number of bytes sent.
References PerformanceTracker::clear(), PerformanceTracker::printMeasurements(), PerformanceTracker::startMeasurement(), and PerformanceTracker::stopMeasurement().
Referenced by SendMaster().
SendMaster()
void EFVITcpV2::SendMaster (char * buffer, size_t buffer_length, bool send_delegated)
Sends a master message.
Parameters
buffer The buffer containing the message.
buffer_length The length of the buffer.
send_delegated A flag indicating if the message should be sent as delegated.
References SendEFVI_Delegated(), and SendNormal().
SendNormal()
int EFVITcpV2::SendNormal (char * buffer, size_t buffer_length)
Sends a normal message.
Parameters
buffer The buffer containing the message.
buffer_length The length of the buffer.
Returns
The number of bytes sent.
Referenced by SendMaster().
SendWarmup()
void EFVITcpV2::SendWarmup ()
Sends warmup messages.
Stop()
void EFVITcpV2::Stop ()
Stops the EFVI TCP client.
Subscribe()
void EFVITcpV2::Subscribe (TcpCallback * callback)
Subscribes to TCP callbacks.
Parameters
callback The TCP callback to subscribe.
tas_prepare()
bool EFVITcpV2::tas_prepare (const KTN_MSG & msg)
Prepares a TAS message.
Parameters
msg The KTN_MSG object representing the message.
Returns
True if preparation is successful, false otherwise.
tas_send()
bool EFVITcpV2::tas_send ()
Sends a TAS message.
Returns
True if sending is successful, false otherwise.
Warmups()
uint64_t KTN::TCP::EFVITcpV2::Warmups () [inline]
Gets the number of warmup messages sent.
Returns
The number of warmup messages sent.
The documentation for this class was generated from the following files:
KtnEfvi/EFVITcpV2.hpp
KtnEfvi/EFVITcpV2.cpp