KTN::NET::ByteWriter Class Reference
Class for writing bytes to a buffer.
#include <byte_writer.hpp>
Public Member Functions
ByteWriter ()
Default constructor.
ByteWriter (void *data, uint32_t total_data_length, uint32_t *output_length)
Constructor that sets the initial buffer and length.
virtual ~ByteWriter ()
Destructor.
void Set (void *data, uint32_t total_data_length, uint32_t *output_length)
Sets the buffer and length for writing.
template<typename T >
bool Write (const T &val)
Writes a value to the buffer.
bool Write (const void *val, uint32_t val_length)
Writes a block of data to the buffer.
bool Seek (int32_t bytes)
Moves the write position in the buffer by the specified number of bytes.
void Reset ()
Resets the write position to the beginning of the buffer.
uint8_t * data ()
Gets a pointer to the buffer.
uint64_t bytes_written ()
Gets the number of bytes that were written to the buffer.
uint8_t * cur ()
Gets a pointer to the current write position in the buffer.
uint32_t bytes_available ()
Gets the number of bytes left to write in the buffer.
uint32_t * cur_length ()
Gets a pointer to the variable that stores the length of the written data.
Detailed Description
Class for writing bytes to a buffer.
Constructor & Destructor Documentation
ByteWriter() [1/2]
KTN::NET::ByteWriter::ByteWriter () [inline]
Default constructor.
ByteWriter() [2/2]
KTN::NET::ByteWriter::ByteWriter (void * data, uint32_t total_data_length, uint32_t * output_length) [inline]
Constructor that sets the initial buffer and length.
Parameters
data Pointer to the buffer.
total_data_length Total length of the buffer.
output_length Pointer to the variable that will store the length of the written data.
~ByteWriter()
virtual KTN::NET::ByteWriter::~ByteWriter () [inline], [virtual]
Destructor.
Member Function Documentation
bytes_available()
uint32_t KTN::NET::ByteWriter::bytes_available () [inline]
Gets the number of bytes left to write in the buffer.
Returns
The number of bytes available for writing.
bytes_written()
uint64_t KTN::NET::ByteWriter::bytes_written () [inline]
Gets the number of bytes that were written to the buffer.
Returns
The number of bytes written.
Referenced by Reset(), and Seek().
cur()
uint8_t * KTN::NET::ByteWriter::cur () [inline]
Gets a pointer to the current write position in the buffer.
Returns
Pointer to the current write position.
Referenced by KTN::CME::IL3::SessionMessageFactory::EstablishEncode(), KTN::CME::IL3::SessionMessageFactory::NegotiateEncode(), KTN::CME::IL3::SessionMessageFactory::RetransRequestEncode(), KTN::CME::IL3::SessionMessageFactory::SequenceEncode(), KTN::CME::IL3::SessionMessageFactory::SofhEncode(), and KTN::CME::IL3::SessionMessageFactory::TerminateEncode().
cur_length()
uint32_t * KTN::NET::ByteWriter::cur_length () [inline]
Gets a pointer to the variable that stores the length of the written data.
Returns
Pointer to the variable that stores the length of the written data.
data()
uint8_t * KTN::NET::ByteWriter::data () [inline]
Gets a pointer to the buffer.
Returns
Pointer to the buffer.
Referenced by Set().
Reset()
void KTN::NET::ByteWriter::Reset () [inline]
Resets the write position to the beginning of the buffer.
References bytes_written(), and Seek().
Seek()
bool KTN::NET::ByteWriter::Seek (int32_t bytes) [inline]
Moves the write position in the buffer by the specified number of bytes.
Parameters
bytes The number of bytes to move the write position. Positive value moves forward, negative value moves backward.
Returns
True if the write position was successfully moved, false otherwise.
References bytes_written().
Referenced by Reset().
Set()
void KTN::NET::ByteWriter::Set (void * data, uint32_t total_data_length, uint32_t * output_length) [inline]
Sets the buffer and length for writing.
Parameters
data Pointer to the buffer.
total_data_length Total length of the buffer.
output_length Pointer to the variable that will store the length of the written data.
References data().
Write() [1/2]
template<typename T >
bool KTN::NET::ByteWriter::Write (const T & val) [inline]
Writes a value to the buffer.
Template Parameters
T The type of the value to write.
Parameters
val The value to write.
Returns
True if the value was successfully written, false otherwise.
Write() [2/2]
bool KTN::NET::ByteWriter::Write (const void * val, uint32_t val_length) [inline]
Writes a block of data to the buffer.
Parameters
val Pointer to the data to write.
val_length Length of the data to write.
Returns
True if the data was successfully written, false otherwise.
The documentation for this class was generated from the following file:
exchsupport/cme/net/byte_writer.hpp