KT01::MSGW::CmeMsgw Class Reference
The CmeMsgw class represents the CME Message Gateway.
#include <CmeMsgw.hpp>
Public Member Functions
void Load (bool certnr)
Loads the CME Message Gateway.
void LoadProductGatewayFile ()
Loads the product gateway file.
void Print ()
Prints the CME Message Gateway.
bool IsLoaded ()
Checks if the CME Message Gateway is loaded.
Msgw getMsgw (int segid)
Gets the Msgw object with the specified segment ID.
int getSegIdFromIp (string ipaddress)
Gets the segment ID from the specified IP address.
int getProdSegId (string product, bool futures)
Gets the product segment ID.
Detailed Description
The CmeMsgw class represents the CME Message Gateway.
Constructor & Destructor Documentation
CmeMsgw()
CmeMsgw::CmeMsgw ()
~CmeMsgw()
CmeMsgw::~CmeMsgw () [virtual]
Member Function Documentation
getMsgw()
Msgw KT01::MSGW::CmeMsgw::getMsgw (int segid) [inline]
Gets the Msgw object with the specified segment ID.
Parameters
segid The segment ID.
Returns
The Msgw object with the specified segment ID.
getProdSegId()
int KT01::MSGW::CmeMsgw::getProdSegId (string product, bool futures) [inline]
Gets the product segment ID.
Parameters
product The product name.
futures A boolean indicating whether the product is for futures.
Returns
The product segment ID.
Referenced by KTN::ORD::OrderHandlerZmqV6::LoadTasOrders().
getSegIdFromIp()
int KT01::MSGW::CmeMsgw::getSegIdFromIp (string ipaddress) [inline]
Gets the segment ID from the specified IP address.
Parameters
ipaddress The IP address.
Returns
The segment ID corresponding to the IP address.
IsLoaded()
bool KT01::MSGW::CmeMsgw::IsLoaded () [inline]
Checks if the CME Message Gateway is loaded.
Returns
True if the CME Message Gateway is loaded, false otherwise.
Load()
void CmeMsgw::Load (bool certnr)
Loads the CME Message Gateway.
Parameters
certnr A boolean indicating whether to load the certificate number.
FULLY QUOALIFIED Directory must have trailing "/"
NOTE: for algos, etc, doesn't matter; we just need the productgwfile....
References LoadProductGatewayFile(), KT01::MSGW::Msgw::Print(), and StringSplitter::Split().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
LoadProductGatewayFile()
void CmeMsgw::LoadProductGatewayFile ()
Loads the product gateway file.
References StringSplitter::Split().
Referenced by KTN::AlgoBaseV3::AlgoBaseV3(), Load(), and KTN::ORD::OrderHandlerZmqV6::OrderHandlerZmqV6().
Print()
void CmeMsgw::Print ()
Prints the CME Message Gateway.
References KT01::MSGW::Msgw::Print().
The documentation for this class was generated from the following files:
exchsupport/cme/CmeMsgw.hpp
exchsupport/cme/CmeMsgw.cpp