KTN::ALGO::SimpleTimer Class Reference
The SimpleTimer class represents a simple timer that can be started, stopped, and paused.
#include <SimpleTimer.hpp>
Public Member Functions
SimpleTimer (TimerCallback &cb)
Constructs a SimpleTimer object with the given TimerCallback.
~SimpleTimer ()
Destroys the SimpleTimer object.
void Pause (bool paused)
Pauses or resumes the timer.
void Start (const std::string &startTime, const std::string &endTime)
Starts the timer with the specified start and end times.
void Stop ()
Stops the timer.
bool Triggered ()
Checks if the timer has been triggered.
bool Started ()
Checks if the timer has been started.
bool Expired ()
Checks if the timer has expired.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The SimpleTimer class represents a simple timer that can be started, stopped, and paused.
Constructor & Destructor Documentation
SimpleTimer()
SimpleTimer::SimpleTimer (TimerCallback & cb)
Constructs a SimpleTimer object with the given TimerCallback.
Parameters
cb The TimerCallback object to be associated with the timer.
~SimpleTimer()
SimpleTimer::~SimpleTimer ()
Destroys the SimpleTimer object.
Member Function Documentation
Expired()
bool KTN::ALGO::SimpleTimer::Expired () [inline]
Checks if the timer has expired.
Returns
True if the timer has expired, false otherwise.
Referenced by KTN::StackerTimer::onJson().
Pause()
void SimpleTimer::Pause (bool paused)
Pauses or resumes the timer.
Parameters
paused If true, the timer will be paused. If false, the timer will be resumed.
Referenced by KTN::StackerTimer::Enable(), and KTN::StackerTimer::onJson().
Start()
void SimpleTimer::Start (const std::string & startTime, const std::string & endTime)
Starts the timer with the specified start and end times.
Parameters
startTime The start time of the timer in string format.
endTime The end time of the timer in string format.
References NamedThread::CreateAndRun(), and Started().
Referenced by KTN::StackerTimer::onJson().
Started()
bool KTN::ALGO::SimpleTimer::Started () [inline]
Checks if the timer has been started.
Returns
True if the timer has been started, false otherwise.
Referenced by KTN::StackerTimer::Enable(), KTN::StackerTimer::minOrderExecution(), KTN::StackerTimer::onJson(), Start(), and KTN::StackerTimer::~StackerTimer().
Stop()
void SimpleTimer::Stop ()
Stops the timer.
Referenced by KTN::StackerTimer::minOrderExecution(), KTN::StackerTimer::ResetPosition(), and KTN::StackerTimer::~StackerTimer().
Triggered()
bool KTN::ALGO::SimpleTimer::Triggered () [inline]
Checks if the timer has been triggered.
Returns
True if the timer has been triggered, false otherwise.
The documentation for this class was generated from the following files:
AlgoCalculators/SimpleTimer.hpp
AlgoCalculators/SimpleTimer.cpp