KTN::REPORTER::GenericReporter Class Reference
The GenericReporter class is responsible for reporting data.
#include <GenericReporter.hpp>
Public Member Functions
GenericReporter ()
Constructs a new GenericReporter object.
~GenericReporter ()
Destroys the GenericReporter object.
void Report (const string &json)
Reports the given JSON data.
void DoWork ()
Performs the work.
void StopWork ()
Stops the work.
Detailed Description
The GenericReporter class is responsible for reporting data.
Constructor & Destructor Documentation
GenericReporter()
GenericReporter::GenericReporter ()
Constructs a new GenericReporter object.
References KTN::REPORTER::ReporterBase::Start().
~GenericReporter()
GenericReporter::~GenericReporter ()
Destroys the GenericReporter object.
Member Function Documentation
DoWork()
void GenericReporter::DoWork () [virtual]
Performs the work.
Implements KTN::REPORTER::ReporterBase.
References KTN::REPORTER::ReporterBase::SendJson().
Report()
void GenericReporter::Report (const string & json)
Reports the given JSON data.
Parameters
json The JSON data to be reported.
StopWork()
void GenericReporter::StopWork ()
Stops the work.
References KTN::REPORTER::ReporterBase::Stop().
The documentation for this class was generated from the following files:
Reporters/GenericReporter.hpp
Reporters/GenericReporter.cpp