JsonUrlReader Class Reference
The JsonUrlReader class is responsible for reading JSON data from a URL.
#include <JsonUrlReader.hpp>
Public Member Functions
JsonUrlReader ()
Default constructor for JsonUrlReader.
virtual ~JsonUrlReader ()
Destructor for JsonUrlReader.
Static Public Member Functions
static size_t WriteCallback (void *contents, size_t size, size_t nmemb, void *userp)
Callback function used by libcurl to write received data to a string buffer.
static std::string Get (std::string url)
Sends an HTTP GET request to the specified URL and returns the response as a string.
Detailed Description
The JsonUrlReader class is responsible for reading JSON data from a URL.
Constructor & Destructor Documentation
JsonUrlReader()
JsonUrlReader::JsonUrlReader ()
Default constructor for JsonUrlReader.
~JsonUrlReader()
JsonUrlReader::~JsonUrlReader () [virtual]
Destructor for JsonUrlReader.
Member Function Documentation
Get()
static std::string JsonUrlReader::Get (std::string url) [inline], [static]
Sends an HTTP GET request to the specified URL and returns the response as a string.
Parameters
url The URL to send the GET request to.
Returns
The response received from the URL as a string.
References WriteCallback().
Referenced by IL3CertHelpers::CertSecId(), and IL3CertHelpers::CertSymbol().
WriteCallback()
static size_t JsonUrlReader::WriteCallback (void * contents, size_t size, size_t nmemb, void * userp) [inline], [static]
Callback function used by libcurl to write received data to a string buffer.
Parameters
contents Pointer to the received data.
size Size of each element in the received data.
nmemb Number of elements in the received data.
userp Pointer to the string buffer where the received data is stored.
Returns
The total number of bytes written to the string buffer.
Referenced by Get().
The documentation for this class was generated from the following files:
Rest/JsonUrlReader.hpp
Rest/JsonUrlReader.cpp