OrderNums Class Reference
Singleton class for generating order numbers and request IDs.
#include <OrderNums.hpp>
Public Member Functions
OrderNums ()
Default constructor.
virtual ~OrderNums ()
Destructor.
string NextOrderId ()
Generates the next order ID.
void NextOrderId (char *&ordernum, size_t len)
Generates the next order ID and copies it to the provided character array.
void NextOrderId2 (char *ordernum, size_t len)
Generates the next order ID and copies it to the provided character array.
uint64_t NextReqIdEncoded (int callbackid)
Generates the next encoded request ID.
uint32_t NextReqId ()
Generates the next request ID.
bool isLoaded ()
Checks if the order numbers have been loaded.
int OrdIdSize ()
Gets the size of the order ID queue.
int ReqIdSize ()
Gets the size of the request ID queue.
Additional Inherited Members
Static Public Member Functions inherited from Singleton< OrderNums >
static I01_API OrderNums & instance ()
Protected Member Functions inherited from Singleton< OrderNums >
Singleton (const Singleton &)=delete
Detailed Description
Singleton class for generating order numbers and request IDs.
Constructor & Destructor Documentation
OrderNums()
OrderNums::OrderNums () [inline]
Default constructor.
~OrderNums()
virtual OrderNums::~OrderNums () [inline], [virtual]
Destructor.
Member Function Documentation
isLoaded()
bool OrderNums::isLoaded () [inline]
Checks if the order numbers have been loaded.
Returns
True if the order numbers have been loaded, false otherwise.
NextOrderID() [1/2]
string OrderNums::NextOrderId () [inline]
Generates the next order ID.
Returns
The next order ID.
References KTN::Core::SPSCRingBuffer< T >::dequeue().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
NextOrderID() [2/2]
void OrderNums::NextOrderId (char *& ordernum, size_t len) [inline]
Generates the next order ID and copies it to the provided character array.
Parameters
ordernum The character array to copy the order ID to.
len The length of the character array.
References KTN::Core::SPSCRingBuffer< T >::dequeue().
NextOrderID2()
void OrderNums::NextOrderId2 (char * ordernum, size_t len) [inline]
Generates the next order ID and copies it to the provided character array.
Parameters
ordernum The character array to copy the order ID to.
len The length of the character array.
References KTN::Core::SPSCRingBuffer< T >::dequeue().
NextReqId()
uint32_t OrderNums::NextReqId () [inline]
Generates the next request ID.
Returns
The next request ID.
References KTN::Core::SPSCRingBuffer< T >::dequeue().
NextReqIdEncoded()
uint64_t OrderNums::NextReqIdEncoded (int callbackid) [inline]
Generates the next encoded request ID.
Parameters
callbackid The callback ID.
Returns
The next encoded request ID.
References KTN::Core::SPSCRingBuffer< T >::dequeue().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
OrdIdSize()
int OrderNums::OrdIdSize () [inline]
Gets the size of the order ID queue.
Returns
The size of the order ID queue.
References KTN::Core::SPSCRingBuffer< T >::size().
ReqIdSize()
int OrderNums::ReqIdSize () [inline]
Gets the size of the request ID queue.
Returns
The size of the request ID queue.
References KTN::Core::SPSCRingBuffer< T >::size().
The documentation for this class was generated from the following file:
Orders/OrderNums.hpp