KTN::notify::Slacker Class Reference
Class representing a Slack-enabled messaging class for alerts and notifications.
#include <Slacker.hpp>
Public Member Functions
Slacker ()
Default constructor for Slacker.
~Slacker ()
Destructor for Slacker.
void InitAndRun ()
Initializes and runs the Slacker.
void Send (string preview, string topic, string msg, int color, bool force)
Sends a Slack message.
void Send (slackmsg &msg)
Sends a Slack message.
void Enable (bool sendmessages)
Enables or disables sending messages.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
Class representing a Slack-enabled messaging class for alerts and notifications.
Constructor & Destructor Documentation
Slacker()
Slacker::Slacker ()
Default constructor for Slacker.
~Slacker()
Slacker::~Slacker ()
Destructor for Slacker.
Member Function Documentation
Enable()
void Slacker::Enable (bool sendmessages)
Enables or disables sending messages.
Parameters
sendmessages A flag indicating whether to enable sending messages.
InitAndRun()
void Slacker::InitAndRun ()
Initializes and runs the Slacker.
References KTN::notify::slackbot::baseurl, KTN::notify::slackbot::channel, KTN::notify::slackbot::color, NamedThread::CreateAndRun(), Settings::get(), KTN::notify::slackbot::Print(), KTN::notify::slackbot::token, and KTN::notify::slackbot::username.
Referenced by KTN::Skewer::Skewer(), KTN::SkewTrader::SkewTrader(), KTN::Stacker::Stacker(), KTN::StackerTimer::StackerTimer(), and KTN::Twap::Twap().
Send() [1/2]
void Slacker::Send (slackmsg & msg)
Sends a Slack message.
Parameters
msg The Slack message to send.
References KTN::notify::slackmsg::text.
Send() [2/2]
void Slacker::Send (string preview, string topic, string msg, int color = LOG_WHITE, bool force = false)
Sends a Slack message.
Parameters
preview The preview of the message.
topic The topic of the message.
msg The text of the message.
color The color of the message.
force A flag indicating whether to force sending the message.
References KTN::notify::slackmsg::color, KTN::notify::slackmsg::preview, KTN::notify::slackmsg::text, and KTN::notify::slackmsg::topic.
Referenced by KTN::Skewer::minOrderExecution(), KTN::StackerTimer::minOrderExecution(), and KTN::Twap::minOrderExecution().
The documentation for this class was generated from the following files:
Notifications/Slacker.hpp
Notifications/Slacker.cpp