RiskLimits Class Reference
The RiskLimits class represents the risk limits for a particular trading account.
#include <RiskLimits.h>
Public Member Functions
RiskLimits ()
Constructs a new RiskLimits object.
~RiskLimits ()
Destroys the RiskLimits object.
void Update (int enable, std::string acro, std::string prod, std::string prodtype, std::string exch, int iMaxOrderSize, int iMaxLong, int iMaxShort, int iMaxBuyOpen, int iMaxSellOpen, int iLogLevel)
Updates the risk limits with the specified parameters.
void LogLevel (int iLogLevel)
Sets the log level.
void SetEnable (bool enable)
Sets the enable flag to enable or disable the risk limits.
void CreateKey ()
Creates a key for the risk limits.
bool OK ()
Checks if the risk limits are within acceptable limits.
bool CheckPos ()
Checks if the current position is within acceptable limits.
bool CheckOrds (bool bIsBid)
Checks if the order quantity is within acceptable limits.
void Print (bool current_risk_only=false)
Prints the risk limits.
bool LegalSize (int iOrderQty)
Checks if the order size is within legal limits.
void GotFill (int iFillSize, bool bIsBuy)
Updates the risk limits based on a fill.
void GotOrder (int iSize, bool bIsBid, bool bIsCxl)
Updates the risk limits based on an order.
int NetPos ()
Calculates the net position.
int GetMaxContracts (bool bIsBid)
Gets the maximum number of contracts for the specified bid/ask.
int GetOrderCount (bool bIsBid)
Gets the number of orders for the specified bid/ask.
int GetPosition (bool bIsBid)
Gets the position for the specified bid/ask.
int GetMaxOrderSize ()
Gets the maximum order size.
bool WillMaxOut (bool bIsBid, int iAdd)
Checks if adding the specified quantity to the bid/ask will exceed the maximum limits.
Public Attributes
string acronym
string account
string product
string producttype
string exchange
int max_order_qty
int max_open_qty_buy
int max_open_qty_sell
int max_pos_long
int max_pos_short
int curr_open_qty_buy
int curr_open_qty_sell
int curr_pos_long
int curr_pos_short
int enabled
string keyvalue
bool hasData
Detailed Description
The RiskLimits class represents the risk limits for a particular trading account.
The RiskLimits class provides methods to update the risk limits, set the log level, enable/disable the risk limits, check various risk conditions, and perform other operations related to risk management.
Constructor & Destructor Documentation
RiskLimits()
RiskLimits::RiskLimits ()
Constructs a new RiskLimits object.
~RiskLimits()
RiskLimits::~RiskLimits ()
Destroys the RiskLimits object.
Member Function Documentation
CheckOrds()
bool RiskLimits::CheckOrds (bool bIsBid)
Checks if the order quantity is within acceptable limits.
Parameters
bIsBid A flag indicating whether the order is a bid or ask.
Returns
True if the order quantity is within acceptable limits, false otherwise.
CheckPos()
bool RiskLimits::CheckPos ()
Checks if the current position is within acceptable limits.
Returns
True if the current position is within acceptable limits, false otherwise.
GetMaxContracts()
int RiskLimits::GetMaxContracts (bool bIsBid)
Gets the maximum number of contracts for the specified bid/ask.
Parameters
bIsBid A flag indicating whether the bid/ask is a bid or ask.
Returns
The maximum number of contracts.
GetMaxOrderSize()
int RiskLimits::GetMaxOrderSize ()
Gets the maximum order size.
Returns
The maximum order size.
GetOrderCount()
int RiskLimits::GetOrderCount (bool bIsBid)
Gets the number of orders for the specified bid/ask.
Parameters
bIsBid A flag indicating whether the bid/ask is a bid or ask.
Returns
The number of orders.
GetPosition()
int RiskLimits::GetPosition (bool bIsBid)
Gets the position for the specified bid/ask.
Parameters
bIsBid A flag indicating whether the bid/ask is a bid or ask.
Returns
The position.
GotFill()
void RiskLimits::GotFill (int iFillSize, bool bIsBuy)
Updates the risk limits based on a fill.
Parameters
iFillSize The fill size.
bIsBuy A flag indicating whether the fill is a buy or sell.
Referenced by KTN::RiskManager::UpdateLimitsOnOrder().
GotOrder()
void RiskLimits::GotOrder (int iSize, bool bIsBid, bool bIsCxl)
Updates the risk limits based on an order.
Parameters
iSize The order size.
bIsBid A flag indicating whether the order is a bid or ask.
bIsCxl A flag indicating whether the order is a cancellation.
Referenced by KTN::RiskManager::UpdateLimitsOnOrder().
LegalSize()
bool RiskLimits::LegalSize (int iOrderQty)
Checks if the order size is within legal limits.
Parameters
iOrderQty The order quantity.
Returns
True if the order size is within legal limits, false otherwise.
LogLevel()
void RiskLimits::LogLevel (int iLogLevel)
Sets the log level.
Parameters
iLogLevel The log level to set.
NetPos()
int RiskLimits::NetPos ()
Calculates the net position.
Returns
The net position.
Referenced by Print().
OK()
bool RiskLimits::OK ()
Checks if the risk limits are within acceptable limits.
Returns
True if the risk limits are within acceptable limits, false otherwise.
Print()
void RiskLimits::Print (bool current_risk_only = false)
Prints the risk limits.
Parameters
current_risk_only A flag indicating whether to print only the current risk limits.
References NetPos().
Referenced by KTN::RiskManager::HandleRiskLimitsJSON(), and Update().
SetEnable()
void RiskLimits::SetEnable (bool enable)
Sets the enable flag to enable or disable the risk limits.
Parameters
enable The enable flag.
Referenced by KTN::RiskManager::setEnable().
Update()
void RiskLimits::Update (int enable, std::string acro, std::string prod, std::string prodtype, std::string exch, int iMaxOrderSize, int iMaxLong, int iMaxShort, int iMaxBuyOpen, int iMaxSellOpen, int iLogLevel)
Updates the risk limits with the specified parameters.
Parameters
enable The enable flag indicating whether the risk limits are enabled or disabled.
acro The acronym of the trading account.
prod The product name.
prodtype The product type.
exch The exchange name.
iMaxOrderSize The maximum order size.
iMaxLong The maximum long position.
iMaxShort The maximum short position.
iMaxBuyOpen The maximum buy open quantity.
iMaxSellOpen The maximum sell open quantity.
iLogLevel The log level.
References Print().
WillMaxOut()
bool RiskLimits::WillMaxOut (bool bIsBid, int iAdd)
Checks if adding the specified quantity to the bid/ask will exceed the maximum limits.
Parameters
bIsBid A flag indicating whether the bid/ask is a bid or ask.
iAdd The quantity to add.
Returns
True if adding the quantity will exceed the maximum limits, false otherwise.
Member Data Documentation
account
string RiskLimits::account
acronym
string RiskLimits::acronym
curr_open_qty_buy
int RiskLimits::curr_open_qty_buy
curr_open_qty_sell
int RiskLimits::curr_open_qty_sell
curr_pos_long
int RiskLimits::curr_pos_long
curr_pos_short
int RiskLimits::curr_pos_short
enabled
int RiskLimits::enabled
exchange
string RiskLimits::exchange
hasData
bool RiskLimits::hasData
keyvalue
string RiskLimits::keyvalue
max_open_qty_buy
int RiskLimits::max_open_qty_buy
max_open_qty_sell
int RiskLimits::max_open_qty_sell
max_order_qty
int RiskLimits::max_order_qty
max_pos_long
int RiskLimits::max_pos_long
max_pos_short
int RiskLimits::max_pos_short
product
string RiskLimits::product
producttype
string RiskLimits::producttype
The documentation for this class was generated from the following files:
Risk/RiskLimits.h
Risk/RiskLimits.cpp