StandardMenu Class Reference
The StandardMenu class represents a standard menu implementation.
#include <StandardMenu.hpp>
Public Member Functions
StandardMenu (MenuCallback &callback, std::string file, std::string name)
Constructs a new StandardMenu object.
virtual ~StandardMenu ()
Destroys the StandardMenu object.
void DisplayAndWait ()
Displays the menu and waits for user input.
void Run () override
Runs the menu in a separate thread.
Public Member Functions inherited from IMenu
virtual ~IMenu ()=default
Virtual destructor.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The StandardMenu class represents a standard menu implementation.
This class inherits from the IMenu interface and the NamedThread class. It provides functionality to display and interact with a menu.
Constructor & Destructor Documentation
StandardMenu()
StandardMenu::StandardMenu (MenuCallback & callback, std::string file, std::string name)
Constructs a new StandardMenu object.
Parameters
callback The MenuCallback object to handle menu events.
file The file associated with the menu.
name The name of the menu.
~StandardMenu()
StandardMenu::~StandardMenu () [virtual]
Destroys the StandardMenu object.
Member Function Documentation
DisplayAndWait()
void StandardMenu::DisplayAndWait () [virtual]
Displays the menu and waits for user input.
Implements IMenu.
References NamedThread::CreateAndRun().
Run()
void StandardMenu::Run () [override], [virtual]
Runs the menu in a separate thread.
Implements NamedThread.
References MenuCallback::onMenuChoice(), and StringSplitter::Split().
The documentation for this class was generated from the following files:
Menu/StandardMenu.hpp
Menu/StandardMenu.cpp