KTN::REPORTER::AlgoV3Reporter Class Reference
The AlgoV3Reporter class is responsible for reporting generic statistics.
#include <AlgoV3Reporter.hpp>
Public Member Functions
AlgoV3Reporter ()
Constructs an instance of AlgoV3Reporter.
~AlgoV3Reporter ()
Destroys the AlgoV3Reporter instance.
void Report (const genericstats &msg)
Reports the generic statistics.
virtual void DoWork () override
Performs the work of the reporter.
void StopWork ()
Stops the work of the reporter.
void SendMessage (const genericstats &gmsg, uint64_t ssboe, const string &updtime)
Sends a message with generic statistics, ssboe, and updtime.
Detailed Description
The AlgoV3Reporter class is responsible for reporting generic statistics.
Constructor & Destructor Documentation
AlgoV3Reporter()
AlgoV3Reporter::AlgoV3Reporter ()
Constructs an instance of AlgoV3Reporter.
References Settings::get(), and KTN::REPORTER::ReporterBase::Start().
~AlgoV3Reporter()
AlgoV3Reporter::~AlgoV3Reporter ()
Destroys the AlgoV3Reporter instance.
Member Function Documentation
DoWork()
void AlgoV3Reporter::DoWork () [override], [virtual]
Performs the work of the reporter.
Implements KTN::REPORTER::ReporterBase.
References KTN::Core::SPSCRingBuffer< T >::empty(), genericstats::enabled, KTN::REPORTER::ReporterBase::getSsboeUs(), KTN::REPORTER::ReporterBase::getTimeString(), genericstats::msgtype, SendMessage(), genericstats::ssboe, KTN::Core::SPSCRingBuffer< T >::try_pop(), genericstats::uniqueid, and genericstats::updatetime.
Report()
void AlgoV3Reporter::Report (const genericstats & msg)
Reports the generic statistics.
Parameters
msg The generic statistics to report.
References KTN::Core::SPSCRingBuffer< T >::push().
SendMessage()
void AlgoV3Reporter::SendMessage (const genericstats & gmsg, uint64_t ssboe, const string & updtime)
Sends a message with generic statistics, ssboe, and updtime.
Parameters
gmsg The generic statistics to send.
ssboe The ssboe value.
updtime The updtime value.
References genericstats::enabled, genericstats::exch, AlgoJson::FormatAlgoStats(), genericstats::msgtype, genericstats::name, genericstats::position, KTN::REPORTER::ReporterBase::SendJson(), genericstats::source, genericstats::symbol, genericstats::templatename, genericstats::text, genericstats::totalexec, and genericstats::uniqueid.
Referenced by DoWork().
StopWork()
void AlgoV3Reporter::StopWork ()
Stops the work of the reporter.
References KTN::REPORTER::ReporterBase::Stop().
The documentation for this class was generated from the following files:
Reporters/AlgoV3Reporter.hpp
Reporters/AlgoV3Reporter.cpp