StringSplitter Class Reference
Static Public Member Functions
static std::vector< std::string > Split (const std::string &src, const std::string &delim)
static bool CheckDelim (std::string szLine, std::string szDelim)
static std::vector< std::string > SplitStream (std::string input, char delim)
static void toUpperCase (std::string &s)
static std::string join (const std::vector< std::string > &strings, const std::string &delimiter)
Detailed Description
Member Function Documentation
CheckDelim()
static bool StringSplitter::CheckDelim (std::string szLine, std::string szDelim) [inline], [static]
Checks if a string contains a specific delimiter.
Parameters
szLine The string to check.
szDelim The delimiter to search for.
Returns
True if the delimiter is found, false otherwise.
join()
static std::string StringSplitter::join (const std::vector< std::string > & strings, const std::string & delimiter) [inline], [static]
Joins a vector of strings into a single string using a delimiter.
Parameters
strings The vector of strings to join.
delimiter The delimiter to insert between the strings.
Returns
The joined string.
Split()
static std::vector< std::string > StringSplitter::Split (const std::string & src, const std::string & delim) [inline], [static]
Splits a string into multiple tokens based on a delimiter.
Parameters
src The source string to split.
delim The delimiter to split the string by.
Returns
A vector of strings containing the tokens.
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), KTN::ExchangeManager::ExchangeManager(), Settings::getListCsv(), KT01::MSGW::CmeMsgw::Load(), KTN::ALGO::OrderLoader::LoadFile(), KT01::MSGW::CmeMsgw::LoadProductGatewayFile(), StandardMenu::Run(), and ZmqMenu::Run().
SplitStream()
static std::vector< std::string > StringSplitter::SplitStream (std::string input, char delim) [inline], [static]
Splits a string into multiple tokens based on a single character delimiter.
Parameters
input The input string to split.
delim The delimiter character to split the string by.
Returns
A vector of strings containing the tokens.
toUpperCase()
static void StringSplitter::toUpperCase (std::string & s) [inline], [static]
Converts a string to uppercase.
Parameters
s The string to convert.
The documentation for this class was generated from the following file:
Core/StringSplitter.hpp