KTN::MultiSpreaderV3 Class Reference
The MultiSpreaderV3 class is a derived class of AlgoBaseV3 and implements an automated multi-leg spread trading algorithm.
#include <MultiSpreaderV3.hpp>
Public Member Functions
MultiSpreaderV3 (AlgoInitializer p)
Constructs a new instance of the MultiSpreaderV3 class.
virtual ~MultiSpreaderV3 ()
Destroys the instance of the MultiSpreaderV3 class.
void onJson (std::string json) override
Handles the JSON input for the algorithm.
void onLaunch (std::string json) override
Handles the launch of the algorithm.
void onCalculate () override
Performs the calculation logic of the algorithm.
void minOrderExecution (KTN::OrderPod &ord, bool hedgeSent) override
Handles Order Execution events from the exchange handler.
void onHedgeOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, uint16_t stratid) override
Handles the event when a hedge order is sent.
void onOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) override
Handles the event when an order is sent.
void Enable (bool bEnable) override
Enables or disables the algorithm.
void ResetPosition () override
Resets the position of the algorithm.
void Print () override
Prints the algorithm's information.
void ToggleCommand (int id) override
Toggles a command in the algorithm.
void Restart () override
Restarts the algorithm.
vector< string > Symbols ()
Gets the symbols used in the algorithm.
Public Member Functions inherited from KTN::AlgoBaseV3
AlgoBaseV3 (AlgoInitializer params)
Constructs a new AlgoBaseV3 object.
virtual ~AlgoBaseV3 ()
Destructor for AlgoBaseV3.
std::string GUID ()
Returns the globally unique identifier (GUID) of the algorithm.
void Poll ()
Polls the system for events.
virtual void onEngineJson (EngineCommand &cmd)
Processes algo engine-specific commands.
virtual void onTrade (int index, double price, double size, int aggressor)
Handles a trade event.
virtual void onMktData (int index)
Handles market data updates.
virtual void onHeartbeat (int msgseqnum)
Handles session heartbeat events.
virtual void onSessionStatus (std::string exch, int mktsegid, int protocol, std::string desc, std::string state)
Handles session status updates.
void onSpreadLegOrderExecution (KTN::Order &ord)
Executes spread leg orders.
virtual void minOrderAck (KTN::OrderPod &ord) override
This method is called when a minimum order acknowledgement is received.
virtual void minOrderCancel (KTN::OrderPod &ord) override
This method is called when a minimum order cancellation is received.
virtual void minOrderModify (KTN::OrderPod &ord) override
This method is called when a minimum order modification is received.
virtual void minOrderReject (KTN::OrderPod &ord, const std::string &text)
Handles order rejection events.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const std::string &text)
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const std::string &text)
virtual void Shutdown ()
Shuts down the algorithm.
void shutdownHandler ()
Shuts down the algorithm handler.
virtual void onMktDataBidAsk (const algomd &md)
Handles bid-ask market data updates.
virtual void onMktDataTrade (const algomd &md)
Handles trade market data updates.
Public Member Functions inherited from KTN::AlgoMktDataCallback
AlgoMktDataCallback ()
Default constructor for AlgoMktDataCallback.
virtual ~AlgoMktDataCallback ()
Virtual destructor for AlgoMktDataCallback.
virtual void onStateChange (int state)
This method is called when the state of the algorithm changes.
Public Member Functions inherited from KTN::SessionCallback
virtual void onSessionStatus (string exch, int mktsegid, int protocol, string desc, string state)=0
This method is called when the session status changes.
virtual void minOrderReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order rejection is received.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancellation rejection is received.
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancel/replace rejection is received.
Additional Inherited Members
Public Attributes inherited from KTN::AlgoBaseV3
std::vector< instrument > _LEGS
Protected Member Functions inherited from KTN::AlgoBaseV3
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
void Notify (std::string msg, MsgLevel::Enum level, MsgType::Enum msgtype)
void PrintMdMap ()
void PrintBookMap ()
void PrintBook (instrument inst)
void UpdateMetaParams (algometa meta)
void ChangeQuoteState (const QuoteState::Enum &newstate)
void ChangeHedgeState (const HedgeState::Enum &newstate)
void RegisterCallbackId ()
void RegisterParams (std::string json)
void RegisterCmeSecId (instrument &inst)
algomd & GetQuote (const instrument &inst)
bool GetQuote (const instrument &inst, algomd &md)
bool GetQuoteByIndex (int index, algomd &md)
bookmd & GetBook (const instrument &inst)
bool GetBook (const instrument &inst, bookmd &book)
bool RiskCheckQty (int qty, int totalqty, int execqty, KOrderSide::Enum side)
void SendOrder (KTN::OrderPod &ord, instrument &inst)
void SendOrderWithHedge (OrderWithHedge &oh, instrument &inst)
int GetBid (int index)
int GetAsk (int index)
void GetBid (int index, atomicquote &qt)
void GetAsk (int index, atomicquote &qt)
bool isValidSecId (uint32_t secid)
const algomd & findBySecId (int id) const
int indexBySecId (int id)
void GenIds (std::string prefix)
void AddReportingMsg (std::string msg, std::string msgtype)
void AddCmeSymbol (std::string symbol)
std::string getCertSymbol (long secid)
int32_t getCertSecId (std::string symbol)
int32_t getProdSecIdFromCert (long secid)
Protected Attributes inherited from KTN::AlgoBaseV3
std::atomic< bool > _ACTIVE
IExchangeSender * _ordersender
KtnCmeMdpV4 * _mdh
CmeMsgw _msgw
OrderManagerV5 _Ords
PerformanceTracker _trk
AlgoHelpers helpers
Slacker _SLACK
AlgoV3Reporter * _algorpt
genericstats _mystats
LogMsg _LOG
algometa _PARAMS
int _NUMLEGS
algomd _MD [8]
std::unordered_map< std::string, instrument > _LEGMAP
std::unordered_map< int, instrument > _SECIDMAP
std::unordered_map< long, std::string > _certIdMap
std::unordered_map< std::string, long > _certIdSymbolMap
QuoteState::Enum _QuotingState
HedgeState::Enum _HedgingState
Settings settings_
volatile bool stopped_
int _EXCH_CALLBACK_ID
bool _CME_BY_SECID
bool _bQuoteInFlight
std::string _GUID
std::string _ORG
bool _MEASURE
bool _CERTNR
int _MKT_DATA_CPU
bool _MKT_DATA_OK
bool _GOT_DATA
long _DATA_TRIES
bool _WATCH_TRADES
bool _WATCH_VOLUME
bool _USEAUDIT
bool _ENABLED
bool _CAN_TRADE
bool _HANDLER_STARTED
double _NETPOS
double _TOTALEXEC
bool _USE_REPORTING_MSGS
volatile bool _RPT_ACTIVE
bool _USE_STOPS
bool _CME_MKT_DATA_STARTED
bool _ALLSYMBOLS
std::string _BASE
int _CNT
int _TESTID
int _GROUPCNT
std::string _SPRDID
int _CORE
bool _VERBOSE
std::string m_Name
Detailed Description
The MultiSpreaderV3 class is a derived class of AlgoBaseV3 and implements an automated multi-leg spread trading algorithm.
Constructor & Destructor Documentation
MultiSpreaderV3()
KTN::MultiSpreaderV3::MultiSpreaderV3 (AlgoInitializer p)
Constructs a new instance of the MultiSpreaderV3 class.
Parameters
p The AlgoInitializer object used to initialize the algorithm.
~MultiSpreaderV3()
KTN::MultiSpreaderV3::~MultiSpreaderV3 () [virtual]
Destroys the instance of the MultiSpreaderV3 class.
Member Function Documentation
Enable()
void KTN::MultiSpreaderV3::Enable (bool bEnable) [override], [virtual]
Enables or disables the algorithm.
Parameters
bEnable A boolean indicating whether to enable or disable the algorithm.
Implements KTN::AlgoBaseV3.
References OrderManagerV5::ClearDeadOrders(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, and instrument::lastSentSellPrice.
Referenced by onJson(), and ResetPosition().
minOrderExecution()
void KTN::MultiSpreaderV3::minOrderExecution (KTN::OrderPod & ord, bool hedgeSent) [override], [virtual]
Handles Order Execution events from the exchange handler.
Parameters
ord The OrderPod object representing the order.
hedgeSent A boolean indicating whether a hedge order has been sent.
Reimplemented from KTN::AlgoBaseV3.
References KTN::OrderPod::exchordid, KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, OrderManagerV5::minOrderExecSpreadLeg(), OrderManagerV5::minOrderExecution(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdState, KTN::OrderPod::OrdStatus, and KTN::OrderPod::secid.
onCalculate()
void KTN::MultiSpreaderV3::onCalculate () [override], [virtual]
Performs the calculation logic of the algorithm.
Implements KTN::AlgoBaseV3.
References instrument::activeQuoting, instrument::askChanged, instrument::bidChanged, instrument::index, instrument::lastAsk, instrument::lastBid, and instrument::mintick.
onHedgeOrderSent()
void KTN::MultiSpreaderV3::onHedgeOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, uint16_t stratid) [override], [virtual]
Handles the event when a hedge order is sent.
Parameters
clordid The client order ID.
reqid The request ID.
secid The security ID.
side The order side.
qty The order quantity.
price The order price.
stratid The strategy ID.
Reimplemented from KTN::AlgoBaseV3.
References QuoterV3::NextNew(), OrderManagerV5::onSentOrderFast(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, and KTN::OrderPod::orderReqId.
onJson()
void KTN::MultiSpreaderV3::onJson (std::string json) [override], [virtual]
Handles the JSON input for the algorithm.
Parameters
json The JSON input string.
Implements KTN::AlgoBaseV3.
References instrument::activeQuoting, Enable(), algometa::Enabled, LegParamParser::ParseSpreadLegs(), ResetPosition(), and instrument::symbol.
Referenced by onLaunch().
onLaunch()
void KTN::MultiSpreaderV3::onLaunch (std::string json) [override], [virtual]
Handles the launch of the algorithm.
Parameters
json The JSON input string.
Implements KTN::AlgoBaseV3.
References onJson(), and MS2Params::parse().
onOrderSent()
void KTN::MultiSpreaderV3::onOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) [override], [virtual]
Handles the event when an order is sent.
Parameters
clordid The client order ID.
reqid The request ID.
secid The security ID.
side The order side.
qty The order quantity.
price The order price.
trig The order trigger.
Reimplemented from KTN::AlgoBaseV3.
References QuoterV3::NextNew(), OrderManagerV5::onSentOrderFast(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, and instrument::symbol.
Print()
void KTN::MultiSpreaderV3::Print () [override], [virtual]
Prints the algorithm's information.
Reimplemented from KTN::AlgoBaseV3.
References PerformanceTracker::clear(), msgstats::mods, msgstats::news, KTN::AlgoBaseV3::Print(), OrderManagerV5::Print(), PerformanceTracker::printMeasurements(), instrument::symbol, and instrument::totalexec.
ResetPosition()
void KTN::MultiSpreaderV3::ResetPosition () [override], [virtual]
Resets the position of the algorithm.
Reimplemented from KTN::AlgoBaseV3.
References instrument::effective, Enable(), instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, instrument::lastSentSellPrice, instrument::position, and instrument::totalexec.
Referenced by onJson().
Restart()
void KTN::MultiSpreaderV3::Restart () [override], [virtual]
Restarts the algorithm.
Reimplemented from KTN::AlgoBaseV3.
Symbols()
vector< string > KTN::MultiSpreaderV3::Symbols ()
Gets the symbols used in the algorithm.
Returns
A vector of strings representing the symbols.
References instrument::symbol.
ToggleCommand()
void KTN::MultiSpreaderV3::ToggleCommand (int id) [override], [virtual]
Toggles a command in the algorithm.
Parameters
id The ID of the command to toggle.
Reimplemented from KTN::AlgoBaseV3.
The documentation for this class was generated from the following files:
Algos/MultiSpreaderV3.hpp
Algos/MultiSpreaderV3.cpp