WavgCalcMulti Class Reference
Class for calculating weighted averages and performing related operations.
#include <WavgCalcMulti.hpp>
Public Member Functions
WavgCalcMulti (TimerCallback &cb)
Constructor for WavgCalcMulti class.
void Test ()
Test function for WavgCalcMulti class.
void Start ()
Start the calculation process.
void Stop ()
Stop the calculation process.
bool setStartEndTime (const std::string &startTime, const std::string &endTime)
Set the start and end time for the calculation.
void calculate (int n, int j, int64_t price, int32_t size)
Perform the calculation for a given set of parameters.
void CalculateSettlements ()
Calculate the settlements.
double CalcStpr (int n)
Calculate the Stpr value for a given n.
std::string getCurrentTime ()
Get the current time in string format.
double getStpr (int n, int j)
Get the Stpr value for a given n and j.
double getWavg (int n, int j)
Get the weighted average value for a given n and j.
double getVolume (int n, int j)
Get the volume value for a given n and j.
double getCount (int n, int j)
Get the count value for a given n and j.
bool Triggered ()
Check if the calculation is triggered.
bool Started ()
Check if the calculation is started.
void Init (string product, string startmonth, int startyear, int nummonths)
Initialize the WavgCalcMulti object with the given parameters.
Detailed Description
Class for calculating weighted averages and performing related operations.
Constructor & Destructor Documentation
WavgCalcMulti()
WavgCalcMulti::WavgCalcMulti (TimerCallback & cb)
Constructor for WavgCalcMulti class.
Parameters
cb The TimerCallback object to be used for timing operations.
Member Function Documentation
CalcStpr()
double WavgCalcMulti::CalcStpr (int n)
Calculate the Stpr value for a given n.
Parameters
n The value of n.
Returns
The calculated Stpr value.
calculate()
void WavgCalcMulti::calculate (int n, int j, int64_t price, int32_t size)
Perform the calculation for a given set of parameters.
Parameters
n The value of n.
j The value of j.
price The price value.
size The size value.
References CalculateSettlements().
CalculateSettlements()
void WavgCalcMulti::CalculateSettlements ()
Calculate the settlements.
Referenced by calculate().
getCount()
double WavgCalcMulti::getCount (int n, int j)
Get the count value for a given n and j.
Parameters
n The value of n.
j The value of j.
Returns
The count value.
getCurrentTime()
std::string WavgCalcMulti::getCurrentTime ()
Get the current time in string format.
Returns
The current time in string format.
getStpr()
double WavgCalcMulti::getStpr (int n, int j)
Get the Stpr value for a given n and j.
Parameters
n The value of n.
j The value of j.
Returns
The Stpr value.
getVolume()
double WavgCalcMulti::getVolume (int n, int j)
Get the volume value for a given n and j.
Parameters
n The value of n.
j The value of j.
Returns
The volume value.
getWavg()
double WavgCalcMulti::getWavg (int n, int j)
Get the weighted average value for a given n and j.
Parameters
n The value of n.
j The value of j.
Returns
The weighted average value.
Init()
void WavgCalcMulti::Init (string product, string startmonth, int startyear, int nummonths)
Initialize the WavgCalcMulti object with the given parameters.
Parameters
product The product string.
startmonth The start month string.
startyear The start year value.
nummonths The number of months value.
References MatrixGen::GenOutrightMatrix(), MatrixGen::GenSpreadMatrix(), and MatrixGen::GetGraphMap().
setStartEndTime()
bool WavgCalcMulti::setStartEndTime (const std::string & startTime, const std::string & endTime)
Set the start and end time for the calculation.
Parameters
startTime The start time in string format.
endTime The end time in string format.
Returns
True if the start and end time are successfully set, false otherwise.
References Start().
Referenced by Test().
Start()
void WavgCalcMulti::Start ()
Start the calculation process.
References Started().
Referenced by setStartEndTime(), and Test().
Started()
bool WavgCalcMulti::Started ()
Check if the calculation is started.
Returns
True if the calculation is started, false otherwise.
Referenced by Start().
Stop()
void WavgCalcMulti::Stop ()
Stop the calculation process.
Test()
void WavgCalcMulti::Test ()
Test function for WavgCalcMulti class.
References setStartEndTime(), and Start().
Triggered()
bool WavgCalcMulti::Triggered ()
Check if the calculation is triggered.
Returns
True if the calculation is triggered, false otherwise.
The documentation for this class was generated from the following files:
AlgoEngines/WavgCalcMulti.hpp
AlgoEngines/WavgCalcMulti.cpp