KTN::TCP::EFVITcpV5 Class Reference
Represents the EFVITcpV5 class. This is our main TCP class. This class is a true EFVI TCP implementation.
#include <EFVITcpV5.hpp>
Classes
struct Conf
Public Types
using TcpClient = efvitcp::TcpClient<Conf>
using TcpConn = TcpClient::Conn
Public Member Functions
EFVITcpV5 (TcpCallback8t *callback)
Constructs an EFVITcpV5 object with the specified callback.
virtual ~EFVITcpV5 ()
Destroys the EFVITcpV5 object.
bool Init (ServiceDescriptor &desc, bool isA)
Initializes the EFVITcpV5 object with the specified service descriptor and flag.
void Subscribe (TcpCallback8t *callback)
Subscribes to the EFVITcpV5 object with the specified callback.
void Stop ()
Stops the EFVITcpV5 object.
void Poll ()
Polls the EFVITcpV5 object.
void SendMaster (char *buffer, size_t buffer_length, bool send_delegated)
Sends the master data with the specified buffer and buffer length.
int SendFastPath (char *buffer, size_t buffer_length)
Sends the data using the fast path with the specified buffer and buffer length.
int SendNormal (char *buffer, size_t buffer_length)
Sends the data using the normal path with the specified buffer and buffer length.
void SendWarm ()
Sends the warm data.
int Fd ()
Gets the file descriptor.
int SegId ()
Gets the segment ID.
void poll ()
Polls the EFVITcpV5 object.
bool bye ()
Sends the bye message.
void onConnectionRefused ()
Handles the connection refused event.
void onConnectionEstablished (TcpConn &conn)
Handles the connection established event.
uint32_t onData (TcpConn &conn, uint8_t *data, uint32_t size)
Handles the data event.
void onConnectionReset (TcpConn &conn)
Handles the connection reset event.
void onConnectionClosed (TcpConn &conn)
Handles the connection closed event.
void onFin (TcpConn &conn, uint8_t *data, uint32_t size)
Handles the FIN event.
void onConnectionTimeout (TcpConn &conn)
Handles the connection timeout event.
void onMoreSendable (TcpConn &conn)
Handles the more sendable event.
void onUserTimeout (TcpConn &conn, uint32_t timer_id)
Handles the user timeout event.
Detailed Description
Represents the EFVITcpV5 class. This is our main TCP class. This class is a true EFVI TCP implementation.
Member Typedef Documentation
TcpClient
using KTN::TCP::EFVITcpV5::TcpClient = efvitcp::TcpClient<Conf>
TcpConn
using KTN::TCP::EFVITcpV5::TcpConn = TcpClient::Conn
Constructor & Destructor Documentation
EFVITcpV5()
EFVITcpV5::EFVITcpV5 (TcpCallback8t * callback)
Constructs an EFVITcpV5 object with the specified callback.
Parameters
callback The callback object.
~EFVITcpV5()
EFVITcpV5::~EFVITcpV5 () [virtual]
Destroys the EFVITcpV5 object.
Member Function Documentation
bye()
bool EFVITcpV5::bye ()
Sends the bye message.
Returns
True if sending the bye message is successful, false otherwise.
Referenced by Stop().
Fd()
int KTN::TCP::EFVITcpV5::Fd () [inline]
Gets the file descriptor.
Returns
The file descriptor.
Init()
bool EFVITcpV5::Init (ServiceDescriptor & desc, bool isA = true)
Initializes the EFVITcpV5 object with the specified service descriptor and flag.
Parameters
desc The service descriptor.
isA The flag indicating whether it is A.
Returns
True if initialization is successful, false otherwise.
References KTN::TCP::ServiceDescriptor::address, KTN::TCP::ServiceDescriptor::feedtype, KTN::TCP::ServiceDescriptor::index, tcp_settings::IntfA, tcp_settings::IntfB, tcp_settings::IntfNameA, tcp_settings::IntfNameB, KTN::TCP::ServiceDescriptor::iSource, tcp_settings::Load(), KTN::TCP::ServiceDescriptor::localinterface, KTN::TCP::ServiceDescriptor::localinterfacename, KTN::TCP::ServiceDescriptor::port, and tcp_settings::UseCtpio.
onConnectionClosed()
void EFVITcpV5::onConnectionClosed (TcpConn & conn)
Handles the connection closed event.
Parameters
conn The TCP connection.
onConnectionEstablished()
void EFVITcpV5::onConnectionEstablished (TcpConn & conn)
Handles the connection established event.
Parameters
conn The TCP connection.
onConnectionRefused()
void EFVITcpV5::onConnectionRefused ()
Handles the connection refused event.
onConnectionReset()
void EFVITcpV5::onConnectionReset (TcpConn & conn)
Handles the connection reset event.
Parameters
conn The TCP connection.
onConnectionTimeout()
void EFVITcpV5::onConnectionTimeout (TcpConn & conn)
Handles the connection timeout event.
Parameters
conn The TCP connection.
onData()
uint32_t EFVITcpV5::onData (TcpConn & conn, uint8_t * data, uint32_t size)
Handles the data event.
Parameters
conn The TCP connection.
data The data received.
size The size of the data.
Returns
The number of bytes processed.
References KTN::TCP::TcpCallback8t::onRecv().
onFin()
void EFVITcpV5::onFin (TcpConn & conn, uint8_t * data, uint32_t size)
Handles the FIN event.
Parameters
conn The TCP connection.
data The data received.
size The size of the data.
onMoreSendable()
void EFVITcpV5::onMoreSendable (TcpConn & conn)
Handles the more sendable event.
Parameters
conn The TCP connection.
onUserTimeout()
void EFVITcpV5::onUserTimeout (TcpConn & conn, uint32_t timer_id)
Handles the user timeout event.
Parameters
conn The TCP connection.
timer_id The timer ID.
Poll()
void EFVITcpV5::Poll ()
Polls the EFVITcpV5 object.
References poll().
poll()
void EFVITcpV5::poll ()
Polls the EFVITcpV5 object.
Referenced by Poll().
SegId()
int KTN::TCP::EFVITcpV5::SegId () [inline]
Gets the segment ID.
Returns
The segment ID.
SendFastPath()
int EFVITcpV5::SendFastPath (char * buffer, size_t buffer_length)
Sends the data using the fast path with the specified buffer and buffer length.
Parameters
buffer The buffer containing the data to send.
buffer_length The length of the buffer.
Returns
The number of bytes sent.
Referenced by KTN::CME::CmeAlgo::Send(), KTN::CME::CmeGT5::Send(), and SendMaster().
SendMaster()
void EFVITcpV5::SendMaster (char * buffer, size_t buffer_length, bool send_delegated)
Sends the master data with the specified buffer and buffer length.
Parameters
buffer The buffer containing the data to send.
buffer_length The length of the buffer.
send_delegated The flag indicating whether to send delegated.
References SendFastPath(), and SendNormal().
SendNormal()
int EFVITcpV5::SendNormal (char * buffer, size_t buffer_length)
Sends the data using the normal path with the specified buffer and buffer length.
Parameters
buffer The buffer containing the data to send.
buffer_length The length of the buffer.
Returns
The number of bytes sent.
Referenced by SendMaster().
SendWarm()
void EFVITcpV5::SendWarm ()
Sends the warm data.
Referenced by KTN::CME::CmeGT5::SendWarm().
Stop()
void EFVITcpV5::Stop ()
Stops the EFVITcpV5 object.
References bye().
Subscribe()
void EFVITcpV5::Subscribe (TcpCallback8t * callback)
Subscribes to the EFVITcpV5 object with the specified callback.
Parameters
callback The callback object.
The documentation for this class was generated from the following files:
KtnEfvi/EFVITcpV5.hpp
KtnEfvi/EFVITcpV5.cpp