KTN::Stacker Class Reference
The Stacker class is a derived class of AlgoBaseV3 and implements the stacking algorithm. This algorithm "seeds" price levels in an automated fashion based on input parameters and current market conditions.
#include <Stacker.hpp>
Public Member Functions
Stacker (AlgoInitializer p)
Constructs a Stacker object.
virtual ~Stacker ()
Destroys the Stacker object.
void onJson (std::string json) override
Handles the JSON input.
void onLaunch (std::string json) override
Handles the launch event.
void onCalculate () override
Calculates the algorithm.
void onTrade (int index, double price, double size, int aggressor) override
Handles the trade event.
void onMktData (int index) override
Handles the market data event.
void minOrderExecution (KTN::OrderPod &ord, bool hedgeSent) override
Handles the minimum order execution event.
void minOrderCancel (KTN::OrderPod &ord) override
Handles the minimum order cancel event.
void minOrderCancelReplaceReject (KTN::OrderPod &ord, const string &text) override
Handles the minimum order cancel replace reject event.
void minOrderCancelReject (KTN::OrderPod &ord, const string &text) override
Handles the minimum order cancel reject event.
void onHedgeOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, uint16_t stratid) override
Handles the hedge order sent event.
void onOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) override
Handles the order sent event.
void Enable (bool bEnable) override
Enables or disables the algorithm.
void ResetPosition () override
Resets the position.
void Print () override
Prints the algorithm details.
void ToggleCommand (int id) override
Toggles a command.
void Restart () override
Restarts the algorithm.
vector< string > Symbols ()
Gets the list of symbols.
Public Member Functions inherited from KTN::AlgoBaseV3
AlgoBaseV3 (AlgoInitializer params)
Constructs a new AlgoBaseV3 object.
virtual ~AlgoBaseV3 ()
Destructor for AlgoBaseV3.
std::string GUID ()
Returns the globally unique identifier (GUID) of the algorithm.
void Poll ()
Polls the system for events.
virtual void onEngineJson (EngineCommand &cmd)
Processes algo engine-specific commands.
virtual void onHeartbeat (int msgseqnum)
Handles session heartbeat events.
virtual void onSessionStatus (std::string exch, int mktsegid, int protocol, std::string desc, std::string state)
Handles session status updates.
void onSpreadLegOrderExecution (KTN::Order &ord)
Executes spread leg orders.
virtual void minOrderAck (KTN::OrderPod &ord) override
This method is called when a minimum order acknowledgement is received.
virtual void minOrderModify (KTN::OrderPod &ord) override
This method is called when a minimum order modification is received.
virtual void minOrderReject (KTN::OrderPod &ord, const std::string &text)
Handles order rejection events.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const std::string &text)
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const std::string &text)
virtual void Shutdown ()
Shuts down the algorithm.
void shutdownHandler ()
Shuts down the algorithm handler.
virtual void onMktDataBidAsk (const algomd &md)
Handles bid-ask market data updates.
virtual void onMktDataTrade (const algomd &md)
Handles trade market data updates.
Public Member Functions inherited from KTN::AlgoMktDataCallback
AlgoMktDataCallback ()
Default constructor for AlgoMktDataCallback.
virtual ~AlgoMktDataCallback ()
Virtual destructor for AlgoMktDataCallback.
virtual void onStateChange (int state)
This method is called when the state of the algorithm changes.
Public Member Functions inherited from KTN::SessionCallback
virtual void onSessionStatus (string exch, int mktsegid, int protocol, string desc, string state)=0
This method is called when the session status changes.
virtual void minOrderReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order rejection is received.
Additional Inherited Members
Public Attributes inherited from KTN::AlgoBaseV3
std::vector< instrument > _LEGS
Protected Member Functions inherited from KTN::AlgoBaseV3
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
void Notify (std::string msg, MsgLevel::Enum level, MsgType::Enum msgtype)
void PrintMdMap ()
void PrintBookMap ()
void PrintBook (instrument inst)
void UpdateMetaParams (algometa meta)
void ChangeQuoteState (const QuoteState::Enum &newstate)
void ChangeHedgeState (const HedgeState::Enum &newstate)
void RegisterCallbackId ()
void RegisterParams (std::string json)
void RegisterCmeSecId (instrument &inst)
algomd & GetQuote (const instrument &inst)
bool GetQuote (const instrument &inst, algomd &md)
bool GetQuoteByIndex (int index, algomd &md)
bookmd & GetBook (const instrument &inst)
bool GetBook (const instrument &inst, bookmd &book)
bool RiskCheckQty (int qty, int totalqty, int execqty, KOrderSide::Enum side)
void SendOrder (KTN::OrderPod &ord, instrument &inst)
void SendOrderWithHedge (OrderWithHedge &oh, instrument &inst)
int GetBid (int index)
int GetAsk (int index)
void GetBid (int index, atomicquote &qt)
void GetAsk (int index, atomicquote &qt)
bool isValidSecId (uint32_t secid)
const algomd & findBySecId (int id) const
int indexBySecId (int id)
void GenIds (std::string prefix)
void AddReportingMsg (std::string msg, std::string msgtype)
void AddCmeSymbol (std::string symbol)
std::string getCertSymbol (long secid)
int32_t getCertSecId (std::string symbol)
int32_t getProdSecIdFromCert (long secid)
Protected Attributes inherited from KTN::AlgoBaseV3
std::atomic< bool > _ACTIVE
IExchangeSender * _ordersender
KtnCmeMdpV4 * _mdh
CmeMsgw _msgw
OrderManagerV5 _Ords
PerformanceTracker _trk
AlgoHelpers helpers
Slacker _SLACK
AlgoV3Reporter * _algorpt
genericstats _mystats
LogMsg _LOG
algometa _PARAMS
int _NUMLEGS
algomd _MD [8]
std::unordered_map< std::string, instrument > _LEGMAP
std::unordered_map< int, instrument > _SECIDMAP
std::unordered_map< long, std::string > _certIdMap
std::unordered_map< std::string, long > _certIdSymbolMap
QuoteState::Enum _QuotingState
HedgeState::Enum _HedgingState
Settings settings_
volatile bool stopped_
int _EXCH_CALLBACK_ID
bool _CME_BY_SECID
bool _bQuoteInFlight
std::string _GUID
std::string _ORG
bool _MEASURE
bool _CERTNR
int _MKT_DATA_CPU
bool _MKT_DATA_OK
bool _GOT_DATA
long _DATA_TRIES
bool _WATCH_TRADES
bool _WATCH_VOLUME
bool _USEAUDIT
bool _ENABLED
bool _CAN_TRADE
bool _HANDLER_STARTED
double _NETPOS
double _TOTALEXEC
bool _USE_REPORTING_MSGS
volatile bool _RPT_ACTIVE
bool _USE_STOPS
bool _CME_MKT_DATA_STARTED
bool _ALLSYMBOLS
std::string _BASE
int _CNT
int _TESTID
int _GROUPCNT
std::string _SPRDID
int _CORE
bool _VERBOSE
std::string m_Name
Detailed Description
The Stacker class is a derived class of AlgoBaseV3 and implements the stacking algorithm. This algorithm "seeds" price levels in an automated fashion based on input parameters and current market conditions.
Constructor & Destructor Documentation
Stacker()
KTN::Stacker::Stacker (AlgoInitializer p)
Constructs a Stacker object.
Parameters
p The AlgoInitializer object.
References KTN::notify::Slacker::InitAndRun().
~Stacker()
KTN::Stacker::~Stacker () [virtual]
Destroys the Stacker object.
Member Function Documentation
Enable()
void KTN::Stacker::Enable (bool bEnable) [override], [virtual]
Enables or disables the algorithm.
Parameters
bEnable The enable flag.
Implements KTN::AlgoBaseV3.
References OrderManagerV5::ClearDeadOrders(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, and instrument::lastSentSellPrice.
Referenced by minOrderExecution(), onJson(), and ResetPosition().
minOrderCancel()
void KTN::Stacker::minOrderCancel (KTN::OrderPod & ord) [override], [virtual]
Handles the minimum order cancel event.
Parameters
ord The OrderPod object.
Reimplemented from KTN::AlgoBaseV3.
References OrderManagerV5::minOrderCancel(), and KTN::OrderPod::OrdAlgoTrig.
minOrderCancelReject()
void KTN::Stacker::minOrderCancelReject (KTN::OrderPod & ord, const string & text) [override], [virtual]
Handles the minimum order cancel reject event.
Parameters
ord The OrderPod object.
text The reject text.
Implements KTN::SessionCallback.
References OrderManagerV5::minOrderReject(), and KTN::OrderPod::OrdAlgoTrig.
minOrderCancelReplaceReject()
void KTN::Stacker::minOrderCancelReplaceReject (KTN::OrderPod & ord, const string & text) [override], [virtual]
Handles the minimum order cancel replace reject event.
Parameters
ord The OrderPod object.
text The reject text.
Implements KTN::SessionCallback.
References OrderManagerV5::minOrderReject().
minOrderExecution()
void KTN::Stacker::minOrderExecution (KTN::OrderPod & ord, bool hedgeSent) [override], [virtual]
Handles the minimum order execution event.
Parameters
ord The OrderPod object.
hedgeSent The hedgeSent flag.
Reimplemented from KTN::AlgoBaseV3.
References KTN::OrderPod::exchordid, Enable(), KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, OrderManagerV5::minOrderExecSpreadLeg(), OrderManagerV5::minOrderExecution(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdState, and KTN::OrderPod::secid.
onCalculate()
void KTN::Stacker::onCalculate () [override], [virtual]
Calculates the algorithm.
Implements KTN::AlgoBaseV3.
onHedgeOrderSent()
void KTN::Stacker::onHedgeOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, uint16_t stratid) [override], [virtual]
Handles the hedge order sent event.
Parameters
clordid The client order ID.
reqid The request ID.
secid The security ID.
side The order side.
qty The order quantity.
price The order price.
stratid The strategy ID.
Reimplemented from KTN::AlgoBaseV3.
References QuoterV3::NextNew(), OrderManagerV5::onSentOrderFast(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, and KTN::OrderPod::orderReqId.
onJson()
void KTN::Stacker::onJson (std::string json) [override], [virtual]
Handles the JSON input.
Parameters
json The JSON string.
Implements KTN::AlgoBaseV3.
References instrument::activeQuoting, Enable(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, instrument::lastSentSellPrice, and ResetPosition().
Referenced by onLaunch().
onLaunch()
void KTN::Stacker::onLaunch (std::string json) [override], [virtual]
Handles the launch event.
Parameters
json The JSON string.
Implements KTN::AlgoBaseV3.
References onJson(), StackerParams::parse(), KtnCmeMdpV4::SetHandleDepth(), and KtnCmeMdpV4::SetHandleTrades().
onMktData()
void KTN::Stacker::onMktData (int index) [override], [virtual]
Handles the market data event.
Parameters
index The index of the market data.
Reimplemented from KTN::AlgoBaseV3.
onOrderSent()
void KTN::Stacker::onOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) [override], [virtual]
Handles the order sent event.
Parameters
clordid The client order ID.
reqid The request ID.
secid The security ID.
side The order side.
qty The order quantity.
price The order price.
trig The order trigger.
Reimplemented from KTN::AlgoBaseV3.
References QuoterV3::NextNew(), OrderManagerV5::onSentOrderFast(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, and instrument::symbol.
onTrade()
void KTN::Stacker::onTrade (int index, double price, double size, int aggressor) [override], [virtual]
Handles the trade event.
Parameters
index The index of the trade.
price The trade price.
size The trade size.
aggressor The aggressor flag.
Reimplemented from KTN::AlgoBaseV3.
References instrument::secid.
Print()
void KTN::Stacker::Print () [override], [virtual]
Prints the algorithm details.
Reimplemented from KTN::AlgoBaseV3.
References OrderManagerV5::Print(), instrument::secid, and instrument::symbol.
ResetPosition()
void KTN::Stacker::ResetPosition () [override], [virtual]
Resets the position.
Reimplemented from KTN::AlgoBaseV3.
References instrument::effective, Enable(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, instrument::lastSentSellPrice, instrument::position, and instrument::totalexec.
Referenced by onJson().
Restart()
void KTN::Stacker::Restart () [override], [virtual]
Restarts the algorithm.
Reimplemented from KTN::AlgoBaseV3.
Symbols()
vector< string > KTN::Stacker::Symbols ()
Gets the list of symbols.
Returns
The list of symbols.
References instrument::symbol.
ToggleCommand()
void KTN::Stacker::ToggleCommand (int id) [override], [virtual]
Toggles a command.
Parameters
id The command ID.
Reimplemented from KTN::AlgoBaseV3.
The documentation for this class was generated from the following files:
Algos/Stacker.hpp
Algos/Stacker.cpp