MatrixGen Class Reference
The MatrixGen class is responsible for generating spread and outright matrices from the input data.
#include <MatrixGen.hpp>
Public Member Functions
void GenSpreadMatrix (string Product, string StartMonth, int StartYear, int NumMonths)
Generates the spread matrix.
void GenOutrightMatrix (string product, string StartMont, int StartYear, int NumMonths)
Generates the outright matrix.
const map< pair< int, int >, std::string > & GetGraphMap () const
Gets the graph map.
const std::tr1::unordered_map< std::string, RC > & GetRcMap () const
Gets the row-column map.
Detailed Description
The MatrixGen class is responsible for generating spread and outright matrices from the input data.
Constructor & Destructor Documentation
MatrixGen()
MatrixGen::MatrixGen ()
~MatrixGen()
MatrixGen::~MatrixGen () [virtual]
Member Function Documentation
GenOutrightMatrix()
void MatrixGen::GenOutrightMatrix (string product, string StartMont, int StartYear, int NumMonths)
Generates the outright matrix.
Parameters
product The product name.
StartMont The starting month.
StartYear The starting year.
NumMonths The number of months.
Referenced by WavgCalcMulti::Init().
GenSpreadMatrix()
void MatrixGen::GenSpreadMatrix (string Product, string StartMonth, int StartYear, int NumMonths)
Generates the spread matrix.
Parameters
Product The product name.
StartMonth The starting month.
StartYear The starting year.
NumMonths The number of months.
Referenced by WavgCalcMulti::Init().
GetGraphMap()
const map< pair< int, int >, std::string > & MatrixGen::GetGraphMap () const
Gets the graph map.
Returns
The graph map.
Referenced by WavgCalcMulti::Init().
GetRcMap()
const std::tr1::unordered_map< std::string, RC > & MatrixGen::GetRcMap () const
Gets the row-column map.
Returns
The row-column map.
The documentation for this class was generated from the following files:
AlgoEngines/MatrixGen.hpp
AlgoEngines/MatrixGen.cpp