KTN::Core::HeartbeatMonitor Class Reference
The HeartbeatMonitor class is responsible for monitoring the heartbeat of a system.
#include <HeartbeatMonitor.hpp>
Public Member Functions
HeartbeatMonitor ()
Constructs a new HeartbeatMonitor object.
virtual ~HeartbeatMonitor ()
Destroys the HeartbeatMonitor object.
void Start (int seconds, int segid, int bufferms)
Starts the heartbeat monitoring with the specified parameters.
void Stop ()
Stops the heartbeat monitoring.
void Reset ()
Resets the heartbeat monitoring.
bool IsFlagSet ()
Checks if the flag is set.
bool ResetFlag ()
Resets the flag.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The HeartbeatMonitor class is responsible for monitoring the heartbeat of a system.
Constructor & Destructor Documentation
HeartbeatMonitor()
HeartbeatMonitor::HeartbeatMonitor ()
Constructs a new HeartbeatMonitor object.
~HeartbeatMonitor()
HeartbeatMonitor::~HeartbeatMonitor () [virtual]
Destroys the HeartbeatMonitor object.
Member Function Documentation
IsFlagSet()
bool KTN::Core::HeartbeatMonitor::IsFlagSet () [inline]
Checks if the flag is set.
Returns
True if the flag is set, false otherwise.
Referenced by SessionStateManager::HbTriggered().
Reset()
void HeartbeatMonitor::Reset ()
Resets the heartbeat monitoring.
Referenced by SessionStateManager::HbSent().
ResetFlag()
bool KTN::Core::HeartbeatMonitor::ResetFlag () [inline]
Resets the flag.
Returns
True if the flag was reset, false otherwise.
Start()
void HeartbeatMonitor::Start (int seconds, int segid, int bufferms)
Starts the heartbeat monitoring with the specified parameters.
Parameters
seconds The interval in seconds between each heartbeat.
segid The segment ID of the system.
bufferms The buffer time in milliseconds.
References NamedThread::CreateAndRun().
Referenced by SessionStateManager::Init().
Stop()
void HeartbeatMonitor::Stop ()
Stops the heartbeat monitoring.
Referenced by SessionStateManager::Stop().
The documentation for this class was generated from the following files:
Core/HeartbeatMonitor.hpp
Core/HeartbeatMonitor.cpp