KTN::ExchangeManager Class Reference
#include <ExchangeManager.hpp>
Public Member Functions
ExchangeManager (tbb::concurrent_queue< KTN::OrderPod > &qords, const string &settingsfile)
virtual ~ExchangeManager ()
void onCommand (const Instruction &cmd)
void Send (KTN::OrderPod &ord)
void SendOrderWithHedge (OrderWithHedge &oh)
void SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > &hdg)
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
Class Name: ExchangeManager Purpose: Container class for exchange handlers. This class will spawn a thread for polling of exchange handler You can also pass messages/commands to the exchange handler via queues
Constructor & Destructor Documentation
ExchangeManager()
ExchangeManager::ExchangeManager (tbb::concurrent_queue< KTN::OrderPod > & qords, const string & settingsfile)
Constructor for ExchangeManager class.
Parameters
qords The concurrent queue for storing order pods.
settingsfile The settings file for the exchange manager.
References NamedThread::CreateAndRun(), Settings::get(), Settings::getInteger(), and StringSplitter::Split().
~ExchangeManager()
ExchangeManager::~ExchangeManager () [virtual]
Destructor for ExchangeManager class.
Member Function Documentation
onCommand()
void ExchangeManager::onCommand (const Instruction & cmd)
Handles the command received by the exchange manager.
Parameters
cmd The instruction/command to be handled.
Referenced by Raptor2::Run(), Raptor2::Send(), Raptor2::SendHedgeInstruction(), Raptor2::SendOrderWithHedge(), and Raptor2::Stop().
Send()
void KTN::ExchangeManager::Send (KTN::OrderPod & ord)
Sends an order pod to the exchange.
Parameters
ord The order pod to be sent.
SendHedgeInstruction()
void KTN::ExchangeManager::SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > & hdg)
Sends a hedge instruction to the exchange.
Parameters
ordereqid The order request ID.
hdg The vector of spread hedge instructions.
SendOrderWithHedge()
void KTN::ExchangeManager::SendOrderWithHedge (OrderWithHedge & oh)
Sends an order with hedge to the exchange.
Parameters
oh The order with hedge to be sent.
The documentation for this class was generated from the following files:
ExchangeHandlers2/ExchangeManager.hpp
ExchangeHandlers2/ExchangeManager.cpp