AlgoFactory Class Reference
Factory class responsible for launching various algorithms.
#include <AlgoFactory.hpp>
Static Public Member Functions
static AlgoBaseV3 * LaunchAlgo (const std::string &json, int cpu, IExchangeSender *exch)
Launches an algorithm based on the provided JSON configuration.
static void ParseLegs (string archetype, string json, vector< instrument > &legs)
Parses the legs for the specified algorithm.
static AlgoHeader ParseAlgoHeader (string json)
Parses the header section of the JSON string and extracts algorithm metadata.
static KTN::Order ParseAlgoOrder (const std::string &json)
Parses an order from a JSON string and returns a KTN::Order object.
static EngineCommand ParseEngineCommand (string json)
Parses an engine command from the given JSON string.
Static Public Member Functions inherited from Singleton< AlgoFactory >
static I01_API AlgoFactory & instance ()
Additional Inherited Members
Protected Member Functions inherited from Singleton< AlgoFactory >
Singleton (const Singleton &)=delete
Detailed Description
Factory class responsible for launching various algorithms.
This class parses the input JSON, extracts algorithm parameters and legs, and returns an instance of the appropriate algorithm.
Member Function Documentation
LaunchAlgo()
static AlgoBaseV3 * AlgoFactory::LaunchAlgo (const std::string & json, int cpu, IExchangeSender * exch) [inline], [static]
Launches an algorithm based on the provided JSON configuration.
Parameters
json JSON string containing algorithm configuration.
cpu CPU affinity for the algorithm.
exch Exchange sender interface for sending orders.
Returns
A pointer to the created AlgoBaseV3 object, or nullptr if the algorithm could not be created.
References instrument::exch, ParseAlgoHeader(), ParseLegs(), and LegParamParser::ParseSpreadLegs().
Referenced by KTN::AlgoServiceBrokerV3::onAlgoCommand().
ParseAlgoHeader()
static AlgoHeader AlgoFactory::ParseAlgoHeader (string json) [inline], [static]
Parses the header section of the JSON string and extracts algorithm metadata.
Parameters
json JSON string containing the header information.
Returns
An AlgoHeader structure containing parsed metadata.
Referenced by LaunchAlgo(), and KTN::AlgoServiceBrokerV3::onAlgoCommand().
ParseAlgoOrder()
static KTN::Order AlgoFactory::ParseAlgoOrder (const std::string & json) [inline], [static]
Parses an order from a JSON string and returns a KTN::Order object.
Parameters
json JSON string containing the order.
Returns
A KTN::Order object representing the parsed order.
References OrderParser::parseincoming().
Referenced by KTN::AlgoServiceBrokerV3::onAlgoCommand().
ParseEngineCommand()
static EngineCommand AlgoFactory::ParseEngineCommand (string json) [inline], [static]
Parses an engine command from the given JSON string.
Parameters
json JSON string containing the engine command.
Returns
An EngineCommand object containing parsed engine command details.
References KEngineCommand::NONE, KEngineType::NONE, KEngineCommand::Value(), KEngineItem::Value(), and KEngineType::Value().
Referenced by KTN::AlgoServiceBrokerV3::onAlgoCommand().
ParseLegs()
static void AlgoFactory::ParseLegs (string archetype, string json, vector< instrument > & legs) [inline], [static]
Parses the legs for the specified algorithm.
Parameters
archetype The type of algorithm.
json JSON string containing leg configurations.
legs Vector where the parsed legs will be stored.
References instrument::exch, and LegParamParser::ParseSpreadLegs().
Referenced by LaunchAlgo().
The documentation for this class was generated from the following file:
Algos/AlgoFactory.hpp