KTN::REPORTER::StatusReporter Class Reference
The StatusReporter class is responsible for reporting session status.
#include <StatusReporter.hpp>
Public Member Functions
StatusReporter ()
Default constructor for StatusReporter.
~StatusReporter ()
Destructor for StatusReporter.
void Stop ()
Stops the StatusReporter.
void Report (SessionStatus &data)
Reports the session status.
bool is_active ()
Checks if the StatusReporter is active.
int status_queue_size ()
Gets the size of the status queue.
Public Attributes
moodycamel::ConcurrentQueue< SessionStatus > _qStatus
Detailed Description
The StatusReporter class is responsible for reporting session status.
Constructor & Destructor Documentation
StatusReporter()
StatusReporter::StatusReporter ()
Default constructor for StatusReporter.
References Settings::get(), and Settings::getInteger().
~StatusReporter()
StatusReporter::~StatusReporter ()
Destructor for StatusReporter.
References Stop().
Member Function Documentation
is_active()
bool KTN::REPORTER::StatusReporter::is_active () [inline]
Checks if the StatusReporter is active.
Returns
True if the StatusReporter is active, false otherwise.
Report()
void StatusReporter::Report (SessionStatus & data)
Reports the session status.
Parameters
data The session status to be reported.
status_queue_size()
int KTN::REPORTER::StatusReporter::status_queue_size () [inline]
Gets the size of the status queue.
Returns
The size of the status queue.
Stop()
void StatusReporter::Stop ()
Stops the StatusReporter.
Referenced by ~StatusReporter().
Member Data Documentation
_qStatus
moodycamel::ConcurrentQueue<SessionStatus> KTN::REPORTER::StatusReporter::_qStatus
The documentation for this class was generated from the following files:
Reporters/StatusReporter.hpp
Reporters/StatusReporter.cpp