ZmqSubscriberV5 Class Reference
A ZMQ subscriber class.
#include <ZmqSubscriberV5.hpp>
Public Member Functions
ZmqSubscriberV5 (IZmqSubscriber *sub, const string &server, int port, const string &name, vector< string > topics)
Constructs a ZmqSubscriberV5 object.
ZmqSubscriberV5 (IZmqSubscriber *sub, const string &server, int port, const string &name, const string &filename, const string &key)
Constructs a ZmqSubscriberV5 object.
virtual ~ZmqSubscriberV5 ()
Destroys the ZmqSubscriberV5 object.
bool AddTopic (string szTopic)
Adds a topic to subscribe to.
void LoadTopics (const string &filename, const string &key)
Loads topics from a file.
const vector< string > Topics () const
Gets the list of subscribed topics.
Detailed Description
A ZMQ subscriber class.
Constructor & Destructor Documentation
ZmqSubscriberV5() [1/2]
ZmqSubscriberV5::ZmqSubscriberV5 (IZmqSubscriber * sub, const string & server, int port, const string & name, vector< string > topics) [explicit]
Constructs a ZmqSubscriberV5 object.
Parameters
sub The IZmqSubscriber object to handle received messages.
server The ZMQ server address.
port The ZMQ server port.
name The name of the subscriber.
topics The initial topics to subscribe to.
References NamedThread::CreateAndRun().
ZmqSubscriberV5() [2/2]
ZmqSubscriberV5::ZmqSubscriberV5 (IZmqSubscriber * sub, const string & server, int port, const string & name, const string & filename, const string & key) [explicit]
Constructs a ZmqSubscriberV5 object.
Parameters
sub The IZmqSubscriber object to handle received messages.
server The ZMQ server address.
port The ZMQ server port.
name The name of the subscriber.
filename The name of the file containing the topics to subscribe to.
key The key to access the topics in the file.
References NamedThread::CreateAndRun(), and LoadTopics().
~ZmqSubscriberV5()
ZmqSubscriberV5::~ZmqSubscriberV5 () [virtual]
Destroys the ZmqSubscriberV5 object.
Member Function Documentation
AddTopic()
bool ZmqSubscriberV5::AddTopic (string szTopic)
Adds a topic to subscribe to.
Parameters
szTopic The topic to add.
Returns
True if the topic was added successfully, false otherwise.
LoadTopics()
void ZmqSubscriberV5::LoadTopics (const string & filename, const string & key)
Loads topics from a file.
Parameters
filename The name of the file containing the topics.
key The key to access the topics in the file.
References Settings::getListCsv().
Referenced by ZmqSubscriberV5().
Topics()
const vector< string > ZmqSubscriberV5::Topics () const [inline]
Gets the list of subscribed topics.
Returns
The list of subscribed topics.
The documentation for this class was generated from the following files:
ZMQ/ZmqSubscriberV5.hpp
ZMQ/ZmqSubscriberV5.cpp