KTN::ALGO::PRICING::PricingStrategyBase Class Reference
The base class for pricing strategies.
#include <PricingStrategyBase.hpp>
Public Member Functions
PricingStrategyBase ()
Default constructor.
virtual ~PricingStrategyBase ()
Destructor.
void Load (instrument *legs, int len, bool certnr)
Load the pricing strategy with the given legs.
Protected Member Functions
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
Log a message.
int roundToTick (int value, int MINTICK, int side)
Round a value to the nearest tick.
float priceRoundConvert (float px, int tickprecision, float mintick, bool roundUp=false)
Round and convert a price value.
int32_t getCertSecId (string symbol)
Get the certificate security ID for the given symbol.
Protected Attributes
instrument _legs [24]
int _numLegs
bool _priceround
bool _CERTNR
tr1::unordered_map< string, long > _certIdMap
Detailed Description
The base class for pricing strategies.
Constructor & Destructor Documentation
PricingStrategyBase()
PricingStrategyBase::PricingStrategyBase ()
Default constructor.
~PricingStrategyBase()
PricingStrategyBase::~PricingStrategyBase () [virtual]
Destructor.
Member Function Documentation
getCertSecId()
int32_t KTN::ALGO::PRICING::PricingStrategyBase::getCertSecId (string symbol) [inline], [protected]
Get the certificate security ID for the given symbol.
Parameters
symbol The symbol for which to get the certificate security ID.
Returns
The certificate security ID.
References IL3CertHelpers::CertSecId().
Referenced by Load().
Load()
void PricingStrategyBase::Load (instrument * legs, int len, bool certnr)
Load the pricing strategy with the given legs.
Parameters
legs An array of instrument objects representing the legs.
len The length of the legs array.
certnr A flag indicating whether to use certificate number.
References getCertSecId(), and instrument::secid.
LogMe()
void PricingStrategyBase::LogMe (std::string szMsg, int iColor = LOG_WHITE) [protected]
Log a message.
Parameters
szMsg The message to log.
iColor The color of the log message (optional).
Referenced by KTN::ALGO::PRICING::ImpliedPricer::CalculateSide().
priceRoundConvert()
float KTN::ALGO::PRICING::PricingStrategyBase::priceRoundConvert (float px, int tickprecision, float mintick, bool roundUp = false) [inline], [protected]
Round and convert a price value.
Parameters
px The price value to round and convert.
tickprecision The precision of the tick size.
mintick The minimum tick size.
roundUp Flag indicating whether to round up or down.
Returns
The rounded and converted price value.
roundToTick()
int KTN::ALGO::PRICING::PricingStrategyBase::roundToTick (int value, int MINTICK, int side) [inline], [protected]
Round a value to the nearest tick.
Parameters
value The value to round.
MINTICK The minimum tick size.
side The rounding side (-1 for rounding up, 1 for rounding down).
Returns
The rounded value.
Referenced by KTN::ALGO::PRICING::SpreadPricer::CalculateSide3().
Member Data Documentation
_certIdMap
tr1::unordered_map<string, long> KTN::ALGO::PRICING::PricingStrategyBase::_certIdMap [protected]
_CERTNR
bool KTN::ALGO::PRICING::PricingStrategyBase::_CERTNR [protected]
_legs
instrument KTN::ALGO::PRICING::PricingStrategyBase::_legs[24] [protected]
_numLegs
int KTN::ALGO::PRICING::PricingStrategyBase::_numLegs [protected]
_priceround
bool KTN::ALGO::PRICING::PricingStrategyBase::_priceround [protected]
The documentation for this class was generated from the following files:
AlgoEngines/PricingStrategyBase.hpp
AlgoEngines/PricingStrategyBase.cpp