KTN::CME::IL3::SessionMessageFactory Class Reference
The SessionMessageFactory class is responsible for creating various session messages.
#include <SessionMessageFactory.hpp>
Public Member Functions
void Init (string settingsfile)
Initializes the SessionMessageFactory with the specified settings file.
KTN_MSG SofhEncode (uint16_t msglen)
Encodes the SOFH (Start of Frame Header) for the given message length.
KTN_MSG NegotiateEncode (uint64_t uuid)
Encodes the Negotiate message with the specified UUID.
KTNBuf EstablishEncode (uint64_t uuid, uint64_t seqid)
Encodes the Establish message with the specified UUID and sequence ID.
KTN_MSG SequenceEncode (uint64_t uuid, uint64_t seqid, bool primary, bool lapse)
Encodes the Sequence message with the specified UUID, sequence ID, primary flag, and lapse flag.
KTNBuf TerminateEncode (uint64_t uuid, string reason, int errorcodes)
Encodes the Terminate message with the specified UUID, reason, and error codes.
KTN_MSG RetransRequestEncode (uint64_t uuid, uint32_t FromSeqNo, uint16_t MsgCount, uInt64NULL lastuuid)
Encodes the RetransRequest message with the specified UUID, FromSeqNo, MsgCount, and last UUID.
KTN_MSG PartyDetailsDefEncode (uint64_t uuid, uint64_t seqid, uint64_t partyDetailsListReqID, uint64_t selfmatchId, string account, string firmid, string traderid)
Encodes the PartyDetailsDef message with the specified UUID, sequence ID, partyDetailsListReqID, selfmatchId, account, firmid, and traderid.
Static Public Member Functions
static uint64_t getSendingTimeEpoch ()
Gets the current sending time epoch.
Detailed Description
The SessionMessageFactory class is responsible for creating various session messages.
Member Function Documentation
EstablishEncode()
KTNBuf SessionMessageFactory::EstablishEncode (uint64_t uuid, uint64_t seqid = 1)
Encodes the Establish message with the specified UUID and sequence ID.
Parameters
uuid The UUID for the message.
seqid The sequence ID for the message.
Returns
The encoded Establish message.
References KTN::NET::ByteWriter::cur().
getSendingTimeEpoch()
static uint64_t KTN::CME::IL3::SessionMessageFactory::getSendingTimeEpoch () [inline], [static]
Gets the current sending time epoch.
Returns
The current sending time epoch.
Init()
void SessionMessageFactory::Init (string settingsfile)
Initializes the SessionMessageFactory with the specified settings file.
Parameters
settingsfile The path to the settings file.
References CmeSessionSettings::Load().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
NegotiateEncode()
KTN_MSG SessionMessageFactory::NegotiateEncode (uint64_t uuid = 0)
Encodes the Negotiate message with the specified UUID.
Parameters
uuid The UUID for the message.
Returns
The encoded Negotiate message.
References KTN::NET::ByteWriter::cur().
PartyDetailsDefEncode()
KTN_MSG KTN::CME::IL3::SessionMessageFactory::PartyDetailsDefEncode (uint64_t uuid, uint64_t seqid, uint64_t partyDetailsListReqID, uint64_t selfmatchId, string account, string firmid, string traderid)
Encodes the PartyDetailsDef message with the specified UUID, sequence ID, partyDetailsListReqID, selfmatchId, account, firmid, and traderid.
Parameters
uuid The UUID for the message.
seqid The sequence ID for the message.
partyDetailsListReqID The partyDetailsListReqID for the message.
selfmatchId The selfmatchId for the message.
account The account for the message.
firmid The firmid for the message.
traderid The traderid for the message.
Returns
The encoded PartyDetailsDef message.
RetransRequestEncode()
KTN_MSG SessionMessageFactory::RetransRequestEncode (uint64_t uuid, uint32_t FromSeqNo, uint16_t MsgCount, uInt64NULL lastuuid = 0)
Encodes the RetransRequest message with the specified UUID, FromSeqNo, MsgCount, and last UUID.
Parameters
uuid The UUID for the message.
FromSeqNo The starting sequence number for retransmission.
MsgCount The number of messages to retransmit.
lastuuid The last UUID for retransmission.
Returns
The encoded RetransRequest message.
References KTN::NET::ByteWriter::cur().
SequenceEncode()
KTN_MSG SessionMessageFactory::SequenceEncode (uint64_t uuid, uint64_t seqid, bool primary = true, bool lapse = false)
Encodes the Sequence message with the specified UUID, sequence ID, primary flag, and lapse flag.
Parameters
uuid The UUID for the message.
seqid The sequence ID for the message.
primary The primary flag for the message.
lapse The lapse flag for the message.
Returns
The encoded Sequence message.
References KTN::NET::ByteWriter::cur().
SofhEncode()
KTN_MSG SessionMessageFactory::SofhEncode (uint16_t msglen)
Encodes the SOFH (Start of Frame Header) for the given message length.
Parameters
msglen The length of the message.
Returns
The encoded SOFH message.
References KTN::NET::ByteWriter::cur().
TerminateEncode()
KTNBuf SessionMessageFactory::TerminateEncode (uint64_t uuid, string reason, int errorcodes)
Encodes the Terminate message with the specified UUID, reason, and error codes.
Parameters
uuid The UUID for the message.
reason The reason for termination.
errorcodes The error codes for the message.
Returns
The encoded Terminate message.
References KTN::NET::ByteWriter::cur().
The documentation for this class was generated from the following files:
exchsupport/cme/factory/SessionMessageFactory.hpp
exchsupport/cme/factory/SessionMessageFactory.cpp