IL3CertHelpers Class Reference
Helper class for working with IL3 certification environments. FOR TESTING ONLY.
#include <IL3CertHelpers.hpp>
Static Public Member Functions
static long CertSecId (string symbol)
Get the cert environment security ID for a given symbol. FOR TESTING ONLY.
static string CertSymbol (long secid)
Get the certification environment symbol for a given security ID. FOR TESTING ONLY.
Detailed Description
Helper class for working with IL3 certification environments. FOR TESTING ONLY.
Constructor & Destructor Documentation
IL3CertHelpers()
IL3CertHelpers::IL3CertHelpers ()
~IL3CertHelpers()
IL3CertHelpers::~IL3CertHelpers () [virtual]
Member Function Documentation
CertSecId()
static long IL3CertHelpers::CertSecId (string symbol) [inline], [static]
Get the cert environment security ID for a given symbol. FOR TESTING ONLY.
Parameters
symbol The cert symbol of the contract.
Returns
The security ID.
References JsonUrlReader::Get().
Referenced by KTN::ALGO::PRICING::PricingStrategyBase::getCertSecId().
CertSymbol()
static string IL3CertHelpers::CertSymbol (long secid) [inline], [static]
Get the certification environment symbol for a given security ID. FOR TESTING ONLY.
Parameters
secid The security ID.
Returns
The symbol of the certificate.
References JsonUrlReader::Get().
The documentation for this class was generated from the following files:
exchsupport/cme/il3/IL3CertHelpers.hpp
exchsupport/cme/il3/IL3CertHelpers.cpp