rapidxml::xml_node< Ch > Class Template Reference
#include <rapidxml.hpp>
Public Member Functions
xml_node (node_type type)
node_type type () const
xml_document< Ch > * document () const
xml_node< Ch > * first_node (const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_node< Ch > * last_node (const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_node< Ch > * previous_sibling (const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_node< Ch > * next_sibling (const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_attribute< Ch > * first_attribute (const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_attribute< Ch > * last_attribute (const Ch *name=0, std::size_t name_size=0, bool case_sensitive=true) const
void type (node_type type)
void prepend_node (xml_node< Ch > *child)
void append_node (xml_node< Ch > *child)
void insert_node (xml_node< Ch > *where, xml_node< Ch > *child)
void remove_first_node ()
void remove_last_node ()
void remove_node (xml_node< Ch > *where)
Removes specified child from the node.
void remove_all_nodes ()
Removes all child nodes (but not attributes).
void prepend_attribute (xml_attribute< Ch > *attribute)
void append_attribute (xml_attribute< Ch > *attribute)
void insert_attribute (xml_attribute< Ch > *where, xml_attribute< Ch > *attribute)
void remove_first_attribute ()
void remove_last_attribute ()
void remove_attribute (xml_attribute< Ch > *where)
void remove_all_attributes ()
Removes all attributes of node.
Public Member Functions inherited from rapidxml::xml_base< char >
char * name () const
void name (const char *name, std::size_t size)
void name (const char *name)
std::size_t name_size () const
char * value () const
void value (const char *value, std::size_t size)
void value (const char *value)
std::size_t value_size () const
xml_node< char > * parent () const
Additional Inherited Members
Static Protected Member Functions inherited from rapidxml::xml_base< char >
static char * nullstr ()
Protected Attributes inherited from rapidxml::xml_base< char >
char * m_name
char * m_value
std::size_t m_name_size
std::size_t m_value_size
xml_node< char > * m_parent
Detailed Description
template<class Ch = char>
class rapidxml::xml_node< Ch >
Class representing a node of XML document. Each node may have associated name and value strings, which are available through name() and value() functions. Interpretation of name and value depends on type of the node. Type of node can be determined by using type() function.
 Note that after parse, both name and value of node, if any, will point interior of source text used for parsing. Thus, this text must persist in the memory for the lifetime of node.
Parameters
Ch Character type to use.
Constructor & Destructor Documentation
xml_node()
template<class Ch = char>
rapidxml::xml_node< Ch >::xml_node (node_type type) [inline]
Constructs an empty node with the specified type. Consider using memory_pool of appropriate document to allocate nodes manually.
Parameters
type Type of node to construct.
Member Function Documentation
append_attribute()
template<class Ch = char>
void rapidxml::xml_node< Ch >::append_attribute (xml_attribute< Ch > * attribute) [inline]
Appends a new attribute to the node.
Parameters
attribute Attribute to append.
References rapidxml::xml_node< Ch >::first_attribute(), and rapidxml::xml_base< Ch >::parent().
Referenced by rapidxml::xml_node< Ch >::insert_attribute().
append_node()
template<class Ch = char>
void rapidxml::xml_node< Ch >::append_node (xml_node< Ch > * child) [inline]
Appends a new child node. The appended child becomes the last child.
Parameters
child Node to append.
References rapidxml::xml_node< Ch >::first_node(), rapidxml::xml_base< Ch >::parent(), and rapidxml::xml_node< Ch >::type().
Referenced by rapidxml::xml_node< Ch >::insert_node().
document()
template<class Ch = char>
xml_document< Ch > * rapidxml::xml_node< Ch >::document () const [inline]
Gets document of which node is a child.
Returns
Pointer to document that contains this node, or 0 if there is no parent document.
References rapidxml::xml_base< Ch >::parent(), and rapidxml::xml_node< Ch >::type().
first_attribute()
template<class Ch = char>
xml_attribute< Ch > * rapidxml::xml_node< Ch >::first_attribute (const Ch * name = 0, std::size_t name_size = 0, bool case_sensitive = true) const [inline]
Gets first attribute of node, optionally matching attribute name.
Parameters
name Name of attribute to find, or 0 to return first attribute regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero
name_size Size of name, in characters, or 0 to have size calculated automatically from string
case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters
Returns
Pointer to found attribute, or 0 if not found.
References rapidxml::xml_base< char >::name(), and rapidxml::xml_base< char >::name_size().
Referenced by rapidxml::xml_node< Ch >::append_attribute(), rapidxml::memory_pool< Ch >::clone_node(), rapidxml::xml_node< Ch >::prepend_attribute(), rapidxml::xml_node< Ch >::remove_all_attributes(), rapidxml::xml_node< Ch >::remove_attribute(), rapidxml::xml_node< Ch >::remove_first_attribute(), and rapidxml::xml_node< Ch >::remove_last_attribute().
first_node()
template<class Ch = char>
xml_node< Ch > * rapidxml::xml_node< Ch >::first_node (const Ch * name = 0, std::size_t name_size = 0, bool case_sensitive = true) const [inline]
Gets first child node, optionally matching node name.
Parameters
name Name of child to find, or 0 to return first child regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero
name_size Size of name, in characters, or 0 to have size calculated automatically from string
case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters
Returns
Pointer to found child, or 0 if not found.
References rapidxml::xml_base< char >::name(), rapidxml::xml_base< char >::name_size(), and rapidxml::xml_node< Ch >::next_sibling().
Referenced by rapidxml::xml_node< Ch >::append_node(), rapidxml::memory_pool< Ch >::clone_node(), rapidxml::xml_node< Ch >::prepend_node(), rapidxml::xml_node< Ch >::remove_all_nodes(), rapidxml::xml_node< Ch >::remove_first_node(), rapidxml::xml_node< Ch >::remove_last_node(), and rapidxml::xml_node< Ch >::remove_node().
insert_attribute()
template<class Ch = char>
void rapidxml::xml_node< Ch >::insert_attribute (xml_attribute< Ch > * where, xml_attribute< Ch > * attribute) [inline]
Inserts a new attribute at specified place inside the node. All attributes after and including the specified attribute are moved one position back.
Parameters
where Place where to insert the attribute, or 0 to insert at the back.
attribute Attribute to insert.
References rapidxml::xml_node< Ch >::append_attribute(), rapidxml::xml_base< Ch >::parent(), and rapidxml::xml_node< Ch >::prepend_attribute().
insert_node()
template<class Ch = char>
void rapidxml::xml_node< Ch >::insert_node (xml_node< Ch > * where, xml_node< Ch > * child) [inline]
Inserts a new child node at specified place inside the node. All children after and including the specified node are moved one position back.
Parameters
where Place where to insert the child, or 0 to insert at the back.
child Node to insert.
References rapidxml::xml_node< Ch >::append_node(), rapidxml::xml_base< Ch >::parent(), rapidxml::xml_node< Ch >::prepend_node(), and rapidxml::xml_node< Ch >::type().
last_attribute()
template<class Ch = char>
xml_attribute< Ch > * rapidxml::xml_node< Ch >::last_attribute (const Ch * name = 0, std::size_t name_size = 0, bool case_sensitive = true) const [inline]
Gets last attribute of node, optionally matching attribute name.
Parameters
name Name of attribute to find, or 0 to return last attribute regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero
name_size Size of name, in characters, or 0 to have size calculated automatically from string
case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters
Returns
Pointer to found attribute, or 0 if not found.
References rapidxml::xml_base< char >::name(), and rapidxml::xml_base< char >::name_size().
last_node()
template<class Ch = char>
xml_node< Ch > * rapidxml::xml_node< Ch >::last_node (const Ch * name = 0, std::size_t name_size = 0, bool case_sensitive = true) const [inline]
Gets last child node, optionally matching node name. Behaviour is undefined if node has no children. Use first_node() to test if node has children.
Parameters
name Name of child to find, or 0 to return last child regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero
name_size Size of name, in characters, or 0 to have size calculated automatically from string
case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters
Returns
Pointer to found child, or 0 if not found.
References rapidxml::xml_base< char >::name(), rapidxml::xml_base< char >::name_size(), and rapidxml::xml_node< Ch >::previous_sibling().
next_sibling()
template<class Ch = char>
xml_node< Ch > * rapidxml::xml_node< Ch >::next_sibling (const Ch * name = 0, std::size_t name_size = 0, bool case_sensitive = true) const [inline]
Gets next sibling node, optionally matching node name. Behaviour is undefined if node has no parent. Use parent() to test if node has a parent.
Parameters
name Name of sibling to find, or 0 to return next sibling regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero
name_size Size of name, in characters, or 0 to have size calculated automatically from string
case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters
Returns
Pointer to found sibling, or 0 if not found.
References rapidxml::xml_base< char >::name(), and rapidxml::xml_base< char >::name_size().
Referenced by rapidxml::memory_pool< Ch >::clone_node(), and rapidxml::xml_node< Ch >::first_node().
prepend_attribute()
template<class Ch = char>
void rapidxml::xml_node< Ch >::prepend_attribute (xml_attribute< Ch > * attribute) [inline]
Prepends a new attribute to the node.
Parameters
attribute Attribute to prepend.
References rapidxml::xml_node< Ch >::first_attribute(), and rapidxml::xml_base< Ch >::parent().
Referenced by rapidxml::xml_node< Ch >::insert_attribute().
prepend_node()
template<class Ch = char>
void rapidxml::xml_node< Ch >::prepend_node (xml_node< Ch > * child) [inline]
Prepends a new child node. The prepended child becomes the first child, and all existing children are moved one position back.
Parameters
child Node to prepend.
References rapidxml::xml_node< Ch >::first_node(), rapidxml::xml_base< Ch >::parent(), and rapidxml::xml_node< Ch >::type().
Referenced by rapidxml::xml_node< Ch >::insert_node().
previous_sibling()
template<class Ch = char>
xml_node< Ch > * rapidxml::xml_node< Ch >::previous_sibling (const Ch * name = 0, std::size_t name_size = 0, bool case_sensitive = true) const [inline]
Gets previous sibling node, optionally matching node name. Behaviour is undefined if node has no parent. Use parent() to test if node has a parent.
Parameters
name Name of sibling to find, or 0 to return previous sibling regardless of its name; this string doesn't have to be zero-terminated if name_size is non-zero
name_size Size of name, in characters, or 0 to have size calculated automatically from string
case_sensitive Should name comparison be case-sensitive; non case-sensitive comparison works properly only for ASCII characters
Returns
Pointer to found sibling, or 0 if not found.
References rapidxml::xml_base< char >::name(), and rapidxml::xml_base< char >::name_size().
Referenced by rapidxml::xml_node< Ch >::last_node().
remove_all_attributes()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_all_attributes () [inline]
Removes all attributes of node.
References rapidxml::xml_node< Ch >::first_attribute().
remove_all_nodes()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_all_nodes () [inline]
Removes all child nodes (but not attributes).
References rapidxml::xml_node< Ch >::first_node().
remove_attribute()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_attribute (xml_attribute< Ch > * where) [inline]
Removes specified attribute from node.
Parameters
where Pointer to attribute to be removed.
References rapidxml::xml_node< Ch >::first_attribute(), rapidxml::xml_base< Ch >::parent(), rapidxml::xml_node< Ch >::remove_first_attribute(), and rapidxml::xml_node< Ch >::remove_last_attribute().
remove_first_attribute()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_first_attribute () [inline]
Removes first attribute of the node. If node has no attributes, behaviour is undefined. Use first_attribute() to test if node has attributes.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by rapidxml::xml_node< Ch >::remove_attribute().
remove_first_node()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_first_node () [inline]
Removes first child node. If node has no children, behaviour is undefined. Use first_node() to test if node has children.
References rapidxml::xml_node< Ch >::first_node().
Referenced by rapidxml::xml_node< Ch >::remove_node().
remove_last_attribute()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_last_attribute () [inline]
Removes last attribute of the node. If node has no attributes, behaviour is undefined. Use first_attribute() to test if node has attributes.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by rapidxml::xml_node< Ch >::remove_attribute().
remove_last_node()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_last_node () [inline]
Removes last child of the node. If node has no children, behaviour is undefined. Use first_node() to test if node has children.
References rapidxml::xml_node< Ch >::first_node().
Referenced by rapidxml::xml_node< Ch >::remove_node().
remove_node()
template<class Ch = char>
void rapidxml::xml_node< Ch >::remove_node (xml_node< Ch > * where) [inline]
Removes specified child from the node.
References rapidxml::xml_node< Ch >::first_node(), rapidxml::xml_base< Ch >::parent(), rapidxml::xml_node< Ch >::remove_first_node(), and rapidxml::xml_node< Ch >::remove_last_node().
type() [1/2]
template<class Ch = char>
node_type rapidxml::xml_node< Ch >::type () const [inline]
Gets type of node.
Returns
Type of node.
Referenced by rapidxml::xml_node< Ch >::append_node(), rapidxml::memory_pool< Ch >::clone_node(), rapidxml::xml_node< Ch >::document(), rapidxml::xml_node< Ch >::insert_node(), rapidxml::xml_node< Ch >::prepend_node(), and rapidxml::xml_node< Ch >::type().
type() [2/2]
template<class Ch = char>
void rapidxml::xml_node< Ch >::type (node_type type) [inline]
Sets type of node.
Parameters
type Type of node to set.
References rapidxml::xml_node< Ch >::type().
The documentation for this class was generated from the following file:
C:/Users/sgaer/source/repos/katanafinancial/OccamCME4/OccamCME4/src/external/rapidxml/rapidxml.hpp