KtnCmeMdpV4 Class Reference
Represents a class that handles CME MDP3 market data.
#include <KtnCmeMdpV4.hpp>
Public Types
using UpdateAlgoCallback = void (*)(const algomd&)
Public Types inherited from KTN::NET::EFVIUdpV4
enum class FilterIPProto : int { UDP = ::IPPROTO_UDP
, TCP = ::IPPROTO_TCP
 }
typedef i01::core::Timestamp Timestamp
Public Member Functions
KtnCmeMdpV4 (string name, int core, bool handletrades)
Constructs a KtnCmeMdpV4 object.
virtual ~KtnCmeMdpV4 ()
Destroys the KtnCmeMdpV4 object.
void Start ()
Starts the KtnCmeMdpV4 object.
void Stop ()
Stops the KtnCmeMdpV4 object.
void Reset ()
Resets the KtnCmeMdpV4 object.
void PrintStats ()
Prints the statistics of the KtnCmeMdpV4 object.
void AddSymbols (vector< string > symbols)
Adds a list of symbols to the KtnCmeMdpV4 object.
void AddSymbols (vector< instrument > legs)
Adds a list of instruments to the KtnCmeMdpV4 object.
void AddSymbol (string symb)
Adds a symbol to the KtnCmeMdpV4 object.
void AddBookDepth (string symb)
Adds book depth for a symbol to the KtnCmeMdpV4 object.
void AddMbo (string symb)
Adds MBO (Market By Order) for a symbol to the KtnCmeMdpV4 object.
void AddChannelFilter (const CmeSecDef &secdef, const string &feedtype)
Adds a channel filter to the KtnCmeMdpV4 object.
void Subscribe (AlgoMktDataCallback *subscriber)
Subscribes to the market data callback.
void Print (bool verbose)
Prints the KtnCmeMdpV4 object.
bool HandleMbo () const
Gets the flag indicating whether to handle MBO (Market By Order).
void SetHandleMbo (bool handleMbo)
Sets the flag indicating whether to handle MBO (Market By Order).
bool HandleDepth () const
Gets the flag indicating whether to handle depth.
void SetHandleDepth (bool handleSnap)
Sets the flag indicating whether to handle depth.
bool HandleStats () const
Gets the flag indicating whether to handle statistics.
void SetHandleStats (bool handleStats)
Sets the flag indicating whether to handle statistics.
bool HandleTrades () const
Gets the flag indicating whether to handle trades.
void SetHandleTrades (bool handleTrades)
Sets the flag indicating whether to handle trades.
bool HandleVolume () const
Gets the flag indicating whether to handle volume.
void SetHandleVolume (bool handleVolume)
Sets the flag indicating whether to handle volume.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Public Member Functions inherited from KTN::NET::EFVIUdpV4
EFVIUdpV4 (std::string feed, bool hwtimestamping, std::string name, bool useCertNrConfigFile=false)
bool apply_filter (const string &connid, const string &ipaddr, int port, bool isA)
void poll ()
void EfPrintStats ()
void RefillRing ()
void testticket ()
int Source ()
Public Attributes
algomd _algomds [16]
bookmd _bookmds [16]
std::vector< string > _FILTERS
int _SECIDS [16]
int _NUMSECS
vector< CmeSecDef > _DEFS
tr1::unordered_map< int, string > _SYMBMAP
Detailed Description
Represents a class that handles CME MDP3 market data.
Member Typedef Documentation
UpdateAlgoCallback
using KtnCmeMdpV4::UpdateAlgoCallback = void (*)(const algomd&)
Constructor & Destructor Documentation
KtnCmeMdpV4()
KtnCmeMdpV4::KtnCmeMdpV4 (string name, int core, bool handletrades) [explicit]
Constructs a KtnCmeMdpV4 object.
Parameters
name The name of the object.
core The core number.
handletrades Flag indicating whether to handle trades.
~KtnCmeMdpV4()
KtnCmeMdpV4::~KtnCmeMdpV4 () [virtual]
Destroys the KtnCmeMdpV4 object.
Member Function Documentation
AddBookDepth()
void KtnCmeMdpV4::AddBookDepth (string symb)
Adds book depth for a symbol to the KtnCmeMdpV4 object.
Parameters
symb The symbol to add book depth for.
References AddChannelFilter(), bookmd::index, and bookmd::secid.
AddChannelFilter()
void KtnCmeMdpV4::AddChannelFilter (const CmeSecDef & secdef, const string & feedtype)
Adds a channel filter to the KtnCmeMdpV4 object.
Parameters
secdef The CME security definition.
feedtype The feed type.
Referenced by AddBookDepth(), and AddSymbol().
AddMbo()
void KtnCmeMdpV4::AddMbo (string symb)
Adds MBO (Market By Order) for a symbol to the KtnCmeMdpV4 object.
Parameters
symb The symbol to add MBO for.
AddSymbol()
void KtnCmeMdpV4::AddSymbol (string symb)
Adds a symbol to the KtnCmeMdpV4 object.
Parameters
symb The symbol to add.
References AddChannelFilter(), algomd::hasImpliedEnabled, algomd::index, and algomd::secid.
Referenced by AddSymbols(), and AddSymbols().
AddSymbols() [1/2]
void KtnCmeMdpV4::AddSymbols (vector< instrument > legs)
Adds a list of instruments to the KtnCmeMdpV4 object.
Parameters
legs The list of instruments to add.
References AddSymbol().
AddSymbols() [2/2]
void KtnCmeMdpV4::AddSymbols (vector< string > symbols)
Adds a list of symbols to the KtnCmeMdpV4 object.
Parameters
symbols The list of symbols to add.
References AddSymbol().
HandleDepth()
bool KtnCmeMdpV4::HandleDepth () const [inline]
Gets the flag indicating whether to handle depth.
Returns
True if depth should be handled, false otherwise.
HandleMbo()
bool KtnCmeMdpV4::HandleMbo () const [inline]
Gets the flag indicating whether to handle MBO (Market By Order).
Returns
True if MBO should be handled, false otherwise.
HandleStats()
bool KtnCmeMdpV4::HandleStats () const [inline]
Gets the flag indicating whether to handle statistics.
Returns
True if statistics should be handled, false otherwise.
HandleTrades()
bool KtnCmeMdpV4::HandleTrades () const [inline]
Gets the flag indicating whether to handle trades.
Returns
True if trades should be handled, false otherwise.
HandleVolume()
bool KtnCmeMdpV4::HandleVolume () const [inline]
Gets the flag indicating whether to handle volume.
Returns
True if volume should be handled, false otherwise.
Print()
void KtnCmeMdpV4::Print (bool verbose)
Prints the KtnCmeMdpV4 object.
Parameters
verbose Flag indicating whether to print verbose information.
PrintStats()
void KtnCmeMdpV4::PrintStats ()
Prints the statistics of the KtnCmeMdpV4 object.
References PerformanceTracker::printMeasurements().
Referenced by KTN::AlgoBaseV3::Print().
SetHandleDepth()
void KtnCmeMdpV4::SetHandleDepth (bool handleSnap) [inline]
Sets the flag indicating whether to handle depth.
Parameters
handleSnap The flag value to set.
Referenced by KTN::Stacker::onLaunch(), KTN::Skewer::Skewer(), and KTN::SkewTrader::SkewTrader().
SetHandleMbo()
void KtnCmeMdpV4::SetHandleMbo (bool handleMbo) [inline]
Sets the flag indicating whether to handle MBO (Market By Order).
Parameters
handleMbo The flag value to set.
SetHandleStats()
void KtnCmeMdpV4::SetHandleStats (bool handleStats) [inline]
Sets the flag indicating whether to handle statistics.
Parameters
handleStats The flag value to set.
SetHandleTrades()
void KtnCmeMdpV4::SetHandleTrades (bool handleTrades) [inline]
Sets the flag indicating whether to handle trades.
Parameters
handleTrades The flag value to set.
Referenced by KTN::AutoHedgeOB::AutoHedgeOB(), KTN::SqueezerOB::onJson(), KTN::AutoHedgeOB::onLaunch(), KTN::PLWatcher::onLaunch(), KTN::SqueezerOB::onLaunch(), KTN::Stacker::onLaunch(), KTN::SqueezerOB::SqueezerOB(), and KTN::StackerTimer::StackerTimer().
SetHandleVolume()
void KtnCmeMdpV4::SetHandleVolume (bool handleVolume) [inline]
Sets the flag indicating whether to handle volume.
Parameters
handleVolume The flag value to set.
Start()
void KtnCmeMdpV4::Start ()
Starts the KtnCmeMdpV4 object.
References NamedThread::CreateAndRun().
Referenced by KTN::AlgoBaseV3::AlgoBaseV3().
Stop()
void KtnCmeMdpV4::Stop ()
Stops the KtnCmeMdpV4 object.
Subscribe()
void KtnCmeMdpV4::Subscribe (AlgoMktDataCallback * subscriber)
Subscribes to the market data callback.
Parameters
subscriber The market data callback subscriber.
Referenced by KTN::AlgoBaseV3::AlgoBaseV3().
Member Data Documentation
_algomds
algomd KtnCmeMdpV4::_algomds[16]
_bookmds
bookmd KtnCmeMdpV4::_bookmds[16]
_DEFS
vector<CmeSecDef> KtnCmeMdpV4::_DEFS
_FILTERS
std::vector<string> KtnCmeMdpV4::_FILTERS
_NUMSECS
int KtnCmeMdpV4::_NUMSECS
_SECIDS
int KtnCmeMdpV4::_SECIDS[16]
_SYMBMAP
tr1::unordered_map<int, string> KtnCmeMdpV4::_SYMBMAP
The documentation for this class was generated from the following files:
exchsupport/cme/KtnCmeMdpV4.hpp
exchsupport/cme/KtnCmeMdpV4.cpp