OrderParser Class Reference
Parses JSON order data and converts it into Order objects.
#include <OrderParser.hpp>
Static Public Member Functions
static KTN::Order parseorder (const rapidjson::Value &json_ord)
Parses a JSON order and returns an Order object.
static KTN::Order parseincoming (const rapidjson::Value &json_ord)
Parses incoming JSON order data and returns an Order object.
static KTN::OrderPod parsepod (const rapidjson::Value &json_ord)
Parses a JSON order and returns an OrderPod object.
Detailed Description
Parses JSON order data and converts it into Order objects.
Member Function Documentation
parseincoming()
KTN::Order OrderParser::parseincoming (const rapidjson::Value & json_ord) [static]
Parses incoming JSON order data and returns an Order object.
Parameters
json_ord The incoming JSON order data.
Returns
The parsed Order object.
Referenced by AlgoFactory::ParseAlgoOrder().
parseorder()
KTN::Order OrderParser::parseorder (const rapidjson::Value & json_ord) [static]
Parses a JSON order and returns an Order object.
Parameters
json_ord The JSON order data.
Returns
The parsed Order object.
Referenced by KTN::AutoHedgeOB::onJson(), KTN::PLWatcher::onJson(), and KTN::SqueezerOB::onJson().
parsepod()
static KTN::OrderPod OrderParser::parsepod (const rapidjson::Value & json_ord) [static]
Parses a JSON order and returns an OrderPod object.
Parameters
json_ord The JSON order data.
Returns
The parsed OrderPod object.
The documentation for this class was generated from the following files:
AlgoParams/OrderParser.hpp
AlgoParams/OrderParser.cpp