QuoterV3 Class Reference
Represents a QuoterV3 class that manages quoting orders and functions.
#include <QuoterV3.hpp>
Public Member Functions
QuoterV3 ()
Default constructor for QuoterV3.
virtual ~QuoterV3 ()
Destructor for QuoterV3.
void Construct (int cbid, instrument inst, algometa meta, bool cert)
Constructs a QuoterV3 object.
void Get (KTN::OrderPod &ord)
Gets the OrderPod object.
void NextNew (KTN::OrderPod &ord, KOrderSide::Enum side, uint64_t exchordid, uint32_t qty, int price)
Retrieve a new OrderPod object.
void NextMod (KTN::OrderPod &ord, KOrderSide::Enum side, uint64_t reqid, uint64_t exchordid, uint32_t qty, int price)
Modifies an existing OrderPod object.
uint64_t HedgeReqId (int32_t secid, int16_t differential, uint8_t multiplier)
Generates a HedgeReqId.
KTN::Order NewBlank ()
Creates a new blank Order object.
int32_t CertSecId (string symbol)
Gets the CertSecId.
KTN::Order GetTemplate ()
Gets the template Order object.
int Total ()
Gets the total count.
string NextId ()
Generates the next ID.
Detailed Description
Represents a QuoterV3 class that manages quoting orders and functions.
Constructor & Destructor Documentation
QuoterV3()
QuoterV3::QuoterV3 ()
Default constructor for QuoterV3.
~QuoterV3()
QuoterV3::~QuoterV3 () [virtual]
Destructor for QuoterV3.
Member Function Documentation
CertSecId()
int32_t QuoterV3::CertSecId (string symbol) [inline]
Gets the CertSecId.
Parameters
symbol The symbol value.
Returns
The CertSecId.
Construct()
void QuoterV3::Construct (int cbid, instrument inst, algometa meta, bool cert)
Constructs a QuoterV3 object.
Parameters
cbid The cbid value.
inst The instrument value.
meta The algometa value.
cert The cert value.
References instrument::exch, instrument::index, instrument::mintick, instrument::mktsegid, instrument::prodtype, instrument::product, instrument::secid, algometa::Source, algometa::Strategy, algometa::StratId, instrument::symbol, algometa::Tag, algometa::UniqueId, and algometa::userinfo.
Get()
void QuoterV3::Get (KTN::OrderPod & ord)
Gets the OrderPod object.
Parameters
ord The OrderPod object to get.
References KTN::Core::SPSCRingBuffer< T >::try_pop().
Referenced by KTN::PLWatcher::OrderReceived().
GetTemplate()
KTN::Order QuoterV3::GetTemplate () [inline]
Gets the template Order object.
Returns
The template Order object.
HedgeReqId()
uint64_t QuoterV3::HedgeReqId (int32_t secid, int16_t differential, uint8_t multiplier)
Generates a HedgeReqId.
Parameters
secid The secid value.
differential The differential value.
multiplier The multiplier value.
Returns
The generated HedgeReqId.
References AlgoHdgEncoder::encodeData().
NewBlank()
KTN::Order QuoterV3::NewBlank () [inline]
Creates a new blank Order object.
Returns
The new blank Order object.
NextId()
string QuoterV3::NextId () [inline]
Generates the next ID.
Returns
The next ID.
Referenced by KTN::Waves::OrderReceived().
NextMod()
void QuoterV3::NextMod (KTN::OrderPod & ord, KOrderSide::Enum side, uint64_t reqid, uint64_t exchordid, uint32_t qty, int price)
Modifies an existing OrderPod object.
Parameters
ord The OrderPod object to modify.
side The KOrderSide value.
reqid The reqid value.
exchordid The exchordid value.
qty The quantity value.
price The price value.
References KTN::OrderPod::exchordid, KTN::OrderPod::OrdAction, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdStatus, KTN::OrderPod::price, KTN::OrderPod::quantity, and KTN::Core::SPSCRingBuffer< T >::try_pop().
NextNew()
void QuoterV3::NextNew (KTN::OrderPod & ord, KOrderSide::Enum side, uint64_t exchordid, uint32_t qty, int price)
Retrieve a new OrderPod object.
Parameters
ord The OrderPod object to create.
side The KOrderSide value.
exchordid The exchordid value.
qty The quantity value.
price The price value.
References KTN::OrderPod::OrdAction, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdStatus, KTN::OrderPod::price, KTN::OrderPod::quantity, and KTN::Core::SPSCRingBuffer< T >::try_pop().
Referenced by KTN::MultiSpreaderV3::onHedgeOrderSent(), KTN::SkewTrader::onHedgeOrderSent(), KTN::Stacker::onHedgeOrderSent(), KTN::Waves::onHedgeOrderSent(), KTN::AutoHedgeOB::onJson(), KTN::SqueezerOB::onJson(), KTN::MultiSpreaderV3::onOrderSent(), KTN::SkewTrader::onOrderSent(), KTN::Stacker::onOrderSent(), KTN::Waves::onOrderSent(), and KTN::PLWatcher::onPL().
Total()
int QuoterV3::Total () [inline]
Gets the total count.
Returns
The total count.
The documentation for this class was generated from the following files:
AlgoEngines/QuoterV3.hpp
AlgoEngines/QuoterV3.cpp