KTN::Waves Class Reference
Weighted Average algorithm class derived from AlgoBaseV3.
#include <Waves.hpp>
Public Member Functions
Waves (AlgoInitializer p)
Constructor for Weighted Average algorithm.
virtual ~Waves ()
Destructor for Waves algorithm.
virtual void onJson (std::string json)
Processes a JSON-formatted string.
virtual void onEngineJson (EngineCommand &cmd)
Processes algo engine-specific commands.
virtual void onLaunch (std::string json)
Triggered when the algorithm is launched.
virtual void onCalculate ()
Performs calculation logic for the algorithm.
void onMktData (int index) override
Handles market data updates.
void onTrade (int index, double price, double size, int aggressor) override
Handles a trade event.
void minOrderExecution (KTN::OrderPod &ord, bool hedgeSent) override
This method is called when a minimum order execution is received.
void onHedgeOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, uint16_t stratid) override
Handles hedge order sent events.
void onOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) override
Handles order sent events.
void OrderReceived (KTN::Order &incoming, int idx) override
Processes received order events.
virtual void Enable (bool bEnable)
Enables or disables the algorithm.
void ResetPosition () override
Resets the algorithm's position.
void Print () override
Prints information about the algorithm instance.
void DoublePrint ()
void ToggleCommand (int id) override
Toggles a specific command by ID.
void Restart () override
Restarts the algorithm.
Public Member Functions inherited from KTN::AlgoBaseV3
AlgoBaseV3 (AlgoInitializer params)
Constructs a new AlgoBaseV3 object.
virtual ~AlgoBaseV3 ()
Destructor for AlgoBaseV3.
std::string GUID ()
Returns the globally unique identifier (GUID) of the algorithm.
void Poll ()
Polls the system for events.
virtual void onHeartbeat (int msgseqnum)
Handles session heartbeat events.
virtual void onSessionStatus (std::string exch, int mktsegid, int protocol, std::string desc, std::string state)
Handles session status updates.
void onSpreadLegOrderExecution (KTN::Order &ord)
Executes spread leg orders.
virtual void minOrderAck (KTN::OrderPod &ord) override
This method is called when a minimum order acknowledgement is received.
virtual void minOrderCancel (KTN::OrderPod &ord) override
This method is called when a minimum order cancellation is received.
virtual void minOrderModify (KTN::OrderPod &ord) override
This method is called when a minimum order modification is received.
virtual void minOrderReject (KTN::OrderPod &ord, const std::string &text)
Handles order rejection events.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const std::string &text)
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const std::string &text)
virtual void Shutdown ()
Shuts down the algorithm.
virtual void OrderMinUpdate (KTN::OrderPod &ord)
Processes updates for an order. OrderMin is a minimal order object.
void shutdownHandler ()
Shuts down the algorithm handler.
virtual void onMktDataBidAsk (const algomd &md)
Handles bid-ask market data updates.
virtual void onMktDataTrade (const algomd &md)
Handles trade market data updates.
Public Member Functions inherited from KTN::AlgoMktDataCallback
AlgoMktDataCallback ()
Default constructor for AlgoMktDataCallback.
virtual ~AlgoMktDataCallback ()
Virtual destructor for AlgoMktDataCallback.
virtual void onStateChange (int state)
This method is called when the state of the algorithm changes.
Public Member Functions inherited from KTN::SessionCallback
virtual void onSessionStatus (string exch, int mktsegid, int protocol, string desc, string state)=0
This method is called when the session status changes.
virtual void minOrderReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order rejection is received.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancellation rejection is received.
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancel/replace rejection is received.
Additional Inherited Members
Public Attributes inherited from KTN::AlgoBaseV3
std::vector< instrument > _LEGS
Protected Member Functions inherited from KTN::AlgoBaseV3
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
void Notify (std::string msg, MsgLevel::Enum level, MsgType::Enum msgtype)
void PrintMdMap ()
void PrintBookMap ()
void PrintBook (instrument inst)
void UpdateMetaParams (algometa meta)
void ChangeQuoteState (const QuoteState::Enum &newstate)
void ChangeHedgeState (const HedgeState::Enum &newstate)
void RegisterCallbackId ()
void RegisterParams (std::string json)
void RegisterCmeSecId (instrument &inst)
algomd & GetQuote (const instrument &inst)
bool GetQuote (const instrument &inst, algomd &md)
bool GetQuoteByIndex (int index, algomd &md)
bookmd & GetBook (const instrument &inst)
bool GetBook (const instrument &inst, bookmd &book)
bool RiskCheckQty (int qty, int totalqty, int execqty, KOrderSide::Enum side)
void SendOrder (KTN::OrderPod &ord, instrument &inst)
void SendOrderWithHedge (OrderWithHedge &oh, instrument &inst)
int GetBid (int index)
int GetAsk (int index)
void GetBid (int index, atomicquote &qt)
void GetAsk (int index, atomicquote &qt)
bool isValidSecId (uint32_t secid)
const algomd & findBySecId (int id) const
int indexBySecId (int id)
void GenIds (std::string prefix)
void AddReportingMsg (std::string msg, std::string msgtype)
void AddCmeSymbol (std::string symbol)
std::string getCertSymbol (long secid)
int32_t getCertSecId (std::string symbol)
int32_t getProdSecIdFromCert (long secid)
Protected Attributes inherited from KTN::AlgoBaseV3
std::atomic< bool > _ACTIVE
IExchangeSender * _ordersender
KtnCmeMdpV4 * _mdh
CmeMsgw _msgw
OrderManagerV5 _Ords
PerformanceTracker _trk
AlgoHelpers helpers
Slacker _SLACK
AlgoV3Reporter * _algorpt
genericstats _mystats
LogMsg _LOG
algometa _PARAMS
int _NUMLEGS
algomd _MD [8]
std::unordered_map< std::string, instrument > _LEGMAP
std::unordered_map< int, instrument > _SECIDMAP
std::unordered_map< long, std::string > _certIdMap
std::unordered_map< std::string, long > _certIdSymbolMap
QuoteState::Enum _QuotingState
HedgeState::Enum _HedgingState
Settings settings_
volatile bool stopped_
int _EXCH_CALLBACK_ID
bool _CME_BY_SECID
bool _bQuoteInFlight
std::string _GUID
std::string _ORG
bool _MEASURE
bool _CERTNR
int _MKT_DATA_CPU
bool _MKT_DATA_OK
bool _GOT_DATA
long _DATA_TRIES
bool _WATCH_TRADES
bool _WATCH_VOLUME
bool _USEAUDIT
bool _ENABLED
bool _CAN_TRADE
bool _HANDLER_STARTED
double _NETPOS
double _TOTALEXEC
bool _USE_REPORTING_MSGS
volatile bool _RPT_ACTIVE
bool _USE_STOPS
bool _CME_MKT_DATA_STARTED
bool _ALLSYMBOLS
std::string _BASE
int _CNT
int _TESTID
int _GROUPCNT
std::string _SPRDID
int _CORE
bool _VERBOSE
std::string m_Name
Detailed Description
Weighted Average algorithm class derived from AlgoBaseV3.
Constructor & Destructor Documentation
Waves()
KTN::Waves::Waves (AlgoInitializer p)
Constructor for Weighted Average algorithm.
Parameters
p AlgoInitializer object.
~Waves()
KTN::Waves::~Waves () [virtual]
Destructor for Waves algorithm.
Member Function Documentation
DoublePrint()
void KTN::Waves::DoublePrint ()
Enable()
void KTN::Waves::Enable (bool bEnable) [virtual]
Enables or disables the algorithm.
Parameters
bEnable A boolean indicating whether to enable or disable.
Implements KTN::AlgoBaseV3.
References algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, and instrument::lastSentSellPrice.
Referenced by onJson(), and ResetPosition().
minOrderExecution()
void KTN::Waves::minOrderExecution (KTN::OrderPod & ord, bool hedgeSent) [override], [virtual]
This method is called when a minimum order execution is received.
Parameters
ord The order details.
hedgeSent Indicates whether a hedge order was sent.
Reimplemented from KTN::AlgoBaseV3.
References KTN::OrderPod::exchordid, KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, OrderManagerV5::minOrderExecution(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdStatus, and KTN::OrderPod::secid.
onCalculate()
void KTN::Waves::onCalculate () [virtual]
Performs calculation logic for the algorithm.
Implements KTN::AlgoBaseV3.
onEngineJson()
void KTN::Waves::onEngineJson (EngineCommand & cmd) [virtual]
Processes algo engine-specific commands.
Parameters
cmd The engine command to process.
Reimplemented from KTN::AlgoBaseV3.
onHedgeOrderSent()
void KTN::Waves::onHedgeOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price9, uint16_t instindex) [override], [virtual]
Handles hedge order sent events.
Parameters
clordid Client order ID.
reqid Request ID.
secid Security ID.
side Order side.
qty Quantity.
price9 Price.
instindex Instrument index.
Reimplemented from KTN::AlgoBaseV3.
References QuoterV3::NextNew(), OrderManagerV5::onSentOrderFast(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, and instrument::secid.
onJson()
void KTN::Waves::onJson (std::string json) [virtual]
Processes a JSON-formatted string.
Parameters
json A JSON-formatted string representing algo parameters.
Note
This is a pure virtual function that must be implemented by derived classes.
Implements KTN::AlgoBaseV3.
References Enable(), algometa::Enabled, and ResetPosition().
Referenced by onLaunch().
onLaunch()
void KTN::Waves::onLaunch (std::string json) [virtual]
Triggered when the algorithm is launched.
Parameters
json A JSON-formatted string representing launch data.
Implements KTN::AlgoBaseV3.
References onJson(), and WavesParams::parse().
onMktData()
void KTN::Waves::onMktData (int index) [override], [virtual]
Handles market data updates.
Parameters
index Market data index.
Reimplemented from KTN::AlgoBaseV3.
onOrderSent()
void KTN::Waves::onOrderSent (char * clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig) [override], [virtual]
Handles order sent events.
Parameters
clordid Client order ID.
reqid Request ID.
secid Security ID.
side Order side.
qty Quantity.
price Price.
trig Order trigger.
Reimplemented from KTN::AlgoBaseV3.
References QuoterV3::NextNew(), OrderManagerV5::onSentOrderFast(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, and instrument::symbol.
onTrade()
void KTN::Waves::onTrade (int index, double price, double size, int aggressor) [override], [virtual]
Handles a trade event.
Parameters
index Trade index.
price Trade price.
size Trade size.
aggressor Trade aggressor indicator.
Reimplemented from KTN::AlgoBaseV3.
OrderReceived()
void KTN::Waves::OrderReceived (KTN::Order & ord, int index) [override], [virtual]
Processes received order events.
Parameters
ord The received order.
index Order index.
Reimplemented from KTN::AlgoBaseV3.
References KTN::OrderPod::callbackid, KTN::OrderPod::instindex, QuoterV3::NextId(), OrderManagerV5::onSentOrderCxl(), OrderManagerV5::onSentOrderMod(), KTN::OrderPod::OrdAction, KTN::OrderPod::ordernum, KTN::OrderPod::OrdExch, KTN::OrderPod::OrdState, KTN::OrderPod::OrdStatus, KTN::OrderPod::price, KTN::OrderPod::quantity, IExchangeSender::Send(), algometa::StratId, KTN::OrderPod::stratid, and instrument::symbol.
Print()
void KTN::Waves::Print () [override], [virtual]
Prints information about the algorithm instance.
Reimplemented from KTN::AlgoBaseV3.
References instrument::col, EdgeStruct::exists, EdgeStruct::index, instrument::istas, KTN::AlgoBaseV3::Print(), instrument::row, and instrument::symbol.
ResetPosition()
void KTN::Waves::ResetPosition () [override], [virtual]
Resets the algorithm's position.
Reimplemented from KTN::AlgoBaseV3.
References instrument::buyState, Enable(), instrument::lastBuyId, and instrument::lastSentBuyPrice.
Referenced by onJson().
Restart()
void KTN::Waves::Restart () [override], [virtual]
Restarts the algorithm.
Reimplemented from KTN::AlgoBaseV3.
ToggleCommand()
void KTN::Waves::ToggleCommand (int id) [override], [virtual]
Toggles a specific command by ID.
Parameters
id Command ID to toggle.
Reimplemented from KTN::AlgoBaseV3.
References OrderManagerV5::Print().
The documentation for this class was generated from the following files:
Algos/Waves.hpp
Algos/Waves.cpp