KTN::RiskManager Class Reference
The RiskManager class handles risk management operations.
#include <RiskManager.h>
Public Member Functions
RiskManager ()
RiskManager constructor.
~RiskManager ()
RiskManager destructor.
void Init (std::string key, std::string account, std::string source, std::string argoserver, int argosubport, int argopushport, int affinity)
Initializes the RiskManager with the provided parameters.
void ProcessLimits (std::string szXml)
Processes the limits using the provided XML string.
void HandleRiskLimitsJSON (std::string szJson)
Handles the risk limits using the provided JSON string.
void GetLimits ()
Retrieves the limits.
void SendToRMS (Order ord, int iStatus, int iReportType, bool bResend, bool bUseJsonArray)
Sends the order to the Risk Management System (RMS).
void SendToRMS (std::vector< Order > ords)
Sends the orders to the Risk Management System (RMS).
void UpdateLimitsOnOrder (Order ord)
Updates the limits on the given order.
void SendRaw (std::string szJson)
Sends the raw JSON string to the Risk Management System (RMS).
bool OK (std::string key)
Checks if the provided key is valid.
int MaxOrdQty (std::string key)
Retrieves the maximum order quantity for the provided key.
bool OrderSizeOK (std::string key, int ordqty, bool bIsBuy, std::string &reason, int oldqty=0)
Checks if the order size is valid for the provided key.
void HandleException (const std::exception &e, std::string sz)
Handles the exception with the provided message.
void onLimitsUpdate ()
Handles the update of the risk limits.
bool GotLimits ()
Checks if the risk limits are available.
void Print ()
Prints the RiskManager information.
void onPnlUpdate (double sl, double tp)
Handles the update of the profit and loss (PnL).
void setEnable (RiskLimits &rl)
Sets the enable flag for the provided risk limits.
void panicMode (int secsToClose)
Activates the panic mode for the specified number of seconds.
void closePositions ()
Closes all positions.
void closePositionsByGroup (const char *const *groupIds, int groupCount)
Closes positions by the provided group IDs.
void cancelOrders ()
Cancels all orders.
void cancelOrders (const char *const *orderIds, int orderCount)
Cancels orders by the provided order IDs.
void cancelOrdersByGroup (const char *const *groupIds, int groupCount)
Cancels orders by the provided group IDs.
void shutdown ()
Shuts down the RiskManager.
void onError (const char *text)
Handles the error with the provided text.
void onDisconnected ()
Handles the disconnection event.
void ResetPosition (std::string sessionId, std::string symbol, std::string szBatsId)
Resets the position for the specified session, symbol, and Bats ID.
void PositionChange (std::string szBatsId, int netchange)
Changes the position for the specified Bats ID by the provided net change.
void Positions ()
Retrieves the positions.
int NetPosition (std::string szBatsId)
Retrieves the net position for the specified Bats ID.
Detailed Description
The RiskManager class handles risk management operations.
Constructor & Destructor Documentation
RiskManager()
RiskManager::RiskManager ()
RiskManager constructor.
~RiskManager()
RiskManager::~RiskManager ()
RiskManager destructor.
Member Function Documentation
cancelOrders() [1/2]
void RiskManager::cancelOrders ()
Cancels all orders.
cancelOrders() [2/2]
void RiskManager::cancelOrders (const char *const * orderIds, int orderCount)
Cancels orders by the provided order IDs.
Parameters
orderIds The array of order IDs to cancel.
orderCount The number of order IDs in the array.
cancelOrdersByGroup()
void RiskManager::cancelOrdersByGroup (const char *const * groupIds, int groupCount)
Cancels orders by the provided group IDs.
Parameters
groupIds The array of group IDs to cancel orders for.
groupCount The number of group IDs in the array.
closePositions()
void RiskManager::closePositions ()
Closes all positions.
closePositionsByGroup()
void RiskManager::closePositionsByGroup (const char *const * groupIds, int groupCount)
Closes positions by the provided group IDs.
Parameters
groupIds The array of group IDs to close positions for.
groupCount The number of group IDs in the array.
GetLimits()
void RiskManager::GetLimits ()
Retrieves the limits.
GotLimits()
bool RiskManager::GotLimits ()
Checks if the risk limits are available.
Returns
True if the risk limits are available, false otherwise.
HandleException()
void RiskManager::HandleException (const std::exception & e, std::string sz)
Handles the exception with the provided message.
Parameters
e The exception object.
sz The exception message.
HandleRiskLimitsJSON()
void RiskManager::HandleRiskLimitsJSON (std::string szJson)
Handles the risk limits using the provided JSON string.
Parameters
szJson The JSON string.
References RiskLimits::Print(), and setEnable().
Init()
void RiskManager::Init (std::string key, std::string account, std::string source, std::string argoserver, int argosubport, int argopushport, int affinity)
Initializes the RiskManager with the provided parameters.
Parameters
key The key parameter.
account The account parameter.
source The source parameter.
argoserver The argoserver parameter.
argosubport The argosubport parameter.
argopushport The argopushport parameter.
affinity The affinity parameter.
MaxOrdQty()
int RiskManager::MaxOrdQty (std::string key)
Retrieves the maximum order quantity for the provided key.
Parameters
key The key to retrieve the maximum order quantity for.
Returns
The maximum order quantity.
NetPosition()
int KTN::RiskManager::NetPosition (std::string szBatsId)
Retrieves the net position for the specified Bats ID.
Parameters
szBatsId The Bats ID.
Returns
The net position.
OK()
bool RiskManager::OK (std::string key)
Checks if the provided key is valid.
Parameters
key The key to check.
Returns
True if the key is valid, false otherwise.
onDisconnected()
void RiskManager::onDisconnected ()
Handles the disconnection event.
onError()
void RiskManager::onError (const char * text)
Handles the error with the provided text.
Parameters
text The error text.
onLimitsUpdate()
void RiskManager::onLimitsUpdate ()
Handles the update of the risk limits.
References setEnable().
onPnlUpdate()
void RiskManager::onPnlUpdate (double sl, double tp)
Handles the update of the profit and loss (PnL).
Parameters
sl The stop loss value.
tp The take profit value.
OrderSizeOK()
bool RiskManager::OrderSizeOK (std::string key, int ordqty, bool bIsBuy, std::string & reason, int oldqty = 0)
Checks if the order size is valid for the provided key.
Parameters
key The key to check the order size for.
ordqty The order quantity.
bIsBuy The flag indicating whether the order is a buy order.
reason The reason for the order size validation result.
oldqty The old order quantity.
Returns
True if the order size is valid, false otherwise.
panicMode()
void RiskManager::panicMode (int secsToClose)
Activates the panic mode for the specified number of seconds.
Parameters
secsToClose The number of seconds to activate the panic mode for.
PositionChange()
void KTN::RiskManager::PositionChange (std::string szBatsId, int netchange)
Changes the position for the specified Bats ID by the provided net change.
Parameters
szBatsId The Bats ID.
netchange The net change.
Print()
void RiskManager::Print ()
Prints the RiskManager information.
ProcessLimits()
void KTN::RiskManager::ProcessLimits (std::string szXml)
Processes the limits using the provided XML string.
Parameters
szXml The XML string.
ResetPosition()
void KTN::RiskManager::ResetPosition (std::string sessionId, std::string symbol, std::string szBatsId)
Resets the position for the specified session, symbol, and Bats ID.
Parameters
sessionId The session ID.
symbol The symbol.
szBatsId The Bats ID.
SendRaw()
void RiskManager::SendRaw (std::string szJson)
Sends the raw JSON string to the Risk Management System (RMS).
Parameters
szJson The raw JSON string to send.
SendToRMS() [1/2]
void RiskManager::SendToRMS (Order ord, int iStatus, int iReportType, bool bResend, bool bUseJsonArray)
Sends the order to the Risk Management System (RMS).
Parameters
ord The order to send.
iStatus The status parameter.
iReportType The report type parameter.
bResend The resend flag.
bUseJsonArray The flag indicating whether to use JSON array.
SendToRMS() [2/2]
void RiskManager::SendToRMS (std::vector< Order > ords)
Sends the orders to the Risk Management System (RMS).
Parameters
ords The vector of orders to send.
setEnable()
void RiskManager::setEnable (RiskLimits & rl)
Sets the enable flag for the provided risk limits.
Parameters
rl The risk limits to set the enable flag for.
References RiskLimits::SetEnable().
Referenced by HandleRiskLimitsJSON(), and onLimitsUpdate().
shutdown()
void RiskManager::shutdown ()
Shuts down the RiskManager.
UpdateLimitsOnOrder()
void RiskManager::UpdateLimitsOnOrder (Order ord)
Updates the limits on the given order.
Parameters
ord The order to update the limits on.
References RiskLimits::GotFill(), and RiskLimits::GotOrder().
The documentation for this class was generated from the following files:
Risk/RiskManager.h
Risk/RiskManager.cpp