KTN::notify::NotifierRest Class Reference
The NotifierRest class is responsible for sending notifications via REST.
#include <NotifierRest.hpp>
Public Member Functions
NotifierRest ()
Constructs a NotifierRest object.
virtual ~NotifierRest ()
Destroys the NotifierRest object.
void Notify (std::string source, string exch, string org, string user, std::string text, MsgLevel::Enum lvl, MsgType::Enum msgtype)
Sends a notification with the specified parameters.
void Notify (Notification &msg)
Sends a notification.
void Heartbeat (std::string source, std::string exch, string org)
Sends a heartbeat notification with the specified parameters.
void Start ()
Starts the NotifierRest thread.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Additional Inherited Members
Static Public Member Functions inherited from Singleton< NotifierRest >
static I01_API NotifierRest & instance ()
Protected Member Functions inherited from Singleton< NotifierRest >
Singleton (const Singleton &)=delete
Detailed Description
The NotifierRest class is responsible for sending notifications via REST.
Constructor & Destructor Documentation
NotifierRest()
NotifierRest::NotifierRest ()
Constructs a NotifierRest object.
References NamedThread::CreateAndRun().
~NotifierRest()
NotifierRest::~NotifierRest () [virtual]
Destroys the NotifierRest object.
Member Function Documentation
Heartbeat()
void NotifierRest::Heartbeat (std::string source, std::string exch, string org)
Sends a heartbeat notification with the specified parameters.
Parameters
source The source of the heartbeat.
exch The exchange of the heartbeat.
org The organization of the heartbeat.
References Notify().
Notify() [1/2]
void NotifierRest::Notify (Notification & msg)
Sends a notification.
Parameters
msg The notification to send.
Notify() [2/2]
void NotifierRest::Notify (std::string source, string exch, string org, string user, std::string text, MsgLevel::Enum lvl, MsgType::Enum msgtype)
Sends a notification with the specified parameters.
Parameters
source The source of the notification.
exch The exchange of the notification.
org The organization of the notification.
user The user of the notification.
text The text of the notification.
lvl The level of the notification.
msgtype The type of the notification.
References Notify().
Referenced by Heartbeat(), and Notify().
The documentation for this class was generated from the following files:
Notifications/NotifierRest.hpp
Notifications/NotifierRest.cpp