KTN::ExchangeBase2 Class Reference
Represents the base class for an exchange handler.
#include <ExchangeBase2.hpp>
Public Member Functions
ExchangeBase2 (const std::string &settingsfile, const std::string &source, const std::string &exchname)
Constructor for ExchangeBase2.
virtual ~ExchangeBase2 ()
Destructor for ExchangeBase2.
const std::string & Name () const
Gets the name of the exchange.
virtual void Stop ()=0
Stops the exchange.
virtual void Send (KTN::OrderPod &order, int action)=0
Sends an order.
virtual void SendMassAction (KTN::Order &order)=0
Sends a mass action.
virtual void SendHedgeInstruction (uint64_t ordereqid, const std::vector< SpreadHedgeV3 > &hdg)
Sends a hedge instruction.
virtual void AlgoJson (std::string json, ExchCmd::Enum cmd)
Sends an algorithmic command in JSON format.
virtual void ClearMaps ()
Clears the maps.
virtual void PrintLatencies (bool clear)
Prints the latencies.
virtual void PrintMsgRatios ()
Prints the message ratios.
virtual void Reset ()
Resets the exchange.
virtual void Command (Instruction command)
Executes a command.
virtual void Poll ()
Polls the exchange.
std::string SettFile ()
Gets the settings file path.
Protected Member Functions
void LogMe (const std::string &szMsg, int iColor=LOG_WHITE)
Logs a message.
void ChangeName (const std::string &owner, const std::string &source)
Changes the name of the exchange.
void ReportStatus (SessionStatus s)
Reports the status of the session.
void MsgSent (const std::string &symb, int cnt, int volume, int event)
Logs a message indicating that a message was sent.
void StopBase ()
Stops the base exchange.
void fastCopy2 (char *dest, const char *src, size_t length)
Fast copy function for copying memory.
bool needhb ()
Checks if a heartbeat is needed.
Protected Attributes
ExchState _State
LogSvc * _logsvc
std::unordered_map< std::string, msgrate > _msgratio
std::unordered_map< std::string, msgevents > _msgevents
HashMap< uint64_t, std::vector< KTN::OrderPod >, 1000 > _hedgeOrds
SpreadHedgeCircBuff _hedgeMap
PerformanceTracker _trk
Detailed Description
Represents the base class for an exchange handler.
Constructor & Destructor Documentation
ExchangeBase2()
ExchangeBase2::ExchangeBase2 (const std::string & settingsfile, const std::string & source, const std::string & exchname)
Constructor for ExchangeBase2.
Parameters
settingsfile The path to the settings file.
source The source of the exchange.
exchname The name of the exchange.
~ExchangeBase2()
ExchangeBase2::~ExchangeBase2 () [virtual]
Destructor for ExchangeBase2.
Member Function Documentation
AlgoJson()
void ExchangeBase2::AlgoJson (std::string json, ExchCmd::Enum cmd) [virtual]
Sends an algorithmic command in JSON format.
Parameters
json The JSON string.
cmd The command type.
AlgoJson reception IF Algo is integrated into handler.
Parameters
json
cmd
References LogMe().
ChangeName()
void KTN::ExchangeBase2::ChangeName (const std::string & owner, const std::string & source) [protected]
Changes the name of the exchange.
Parameters
owner The owner of the exchange.
source The source of the exchange.
ClearMaps()
void ExchangeBase2::ClearMaps () [virtual]
Clears the maps.
Reimplemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
References LogMe().
Command()
void ExchangeBase2::Command (Instruction command) [virtual]
Executes a command.
Parameters
command The command to execute.
Reimplemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
References LogMe().
fastCopy2()
void KTN::ExchangeBase2::fastCopy2 (char * dest, const char * src, size_t length) [inline], [protected]
Fast copy function for copying memory.
Parameters
dest The destination memory address.
src The source memory address.
length The length of the memory to copy.
LogMe()
void ExchangeBase2::LogMe (const std::string & szMsg, int iColor = LOG_WHITE) [protected]
Logs a message.
Parameters
szMsg The message to log.
iColor The color of the log message.
References LogSvc::LogMe().
Referenced by AlgoJson(), KTN::CME::CmeAlgo::ClearMaps(), KTN::CME::CmeGT5::ClearMaps(), ClearMaps(), KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), KTN::CME::CmeAlgo::Command(), KTN::CME::CmeGT5::Command(), Command(), KTN::CME::CmeAlgo::onRecv(), KTN::CME::CmeGT5::onRecv(), KTN::CME::CmeAlgo::PrintLatencies(), KTN::CME::CmeGT5::PrintLatencies(), PrintLatencies(), PrintMsgRatios(), KTN::CME::CmeGT5::PrintSessionMap(), KTN::CME::CmeGT5::ProcessingThread(), Reset(), KTN::CME::CmeAlgo::Send(), KTN::CME::CmeGT5::Send(), KTN::CME::CmeGT5::SendHedgeInstruction(), SendHedgeInstruction(), KTN::CME::CmeGT5::Start(), KTN::CME::CmeAlgo::Stop(), and KTN::CME::CmeGT5::Stop().
MsgSent()
void ExchangeBase2::MsgSent (const std::string & symb, int cnt, int volume, int event) [protected]
Logs a message indicating that a message was sent.
Parameters
symb The symbol of the message.
cnt The count of the message.
volume The volume of the message.
event The event of the message.
Name()
const std::string & KTN::ExchangeBase2::Name () const [inline]
Gets the name of the exchange.
Returns
The name of the exchange.
needhb()
bool KTN::ExchangeBase2::needhb () [inline], [protected]
Checks if a heartbeat is needed.
Returns
True if a heartbeat is needed, false otherwise.
Poll()
virtual void KTN::ExchangeBase2::Poll () [virtual]
Polls the exchange.
Reimplemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
PrintLatencies()
void ExchangeBase2::PrintLatencies (bool clear) [virtual]
Prints the latencies.
Parameters
clear Indicates whether to clear the latencies after printing.
Reimplemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
References PerformanceTracker::clear(), LogMe(), and PerformanceTracker::printMeasurements().
PrintMsgRatios()
void ExchangeBase2::PrintMsgRatios () [virtual]
Prints the message ratios.
References LogMe().
ReportStatus()
void ExchangeBase2::ReportStatus (SessionStatus s) [protected]
Reports the status of the session.
Parameters
s The session status.
Reset()
void ExchangeBase2::Reset () [virtual]
Resets the exchange.
Reimplemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
References LogMe().
Send()
virtual void KTN::ExchangeBase2::Send (KTN::OrderPod & order, int action) [pure virtual]
Sends an order.
Parameters
order The order to send.
action The action to perform.
Implemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
SendHedgeInstruction()
void ExchangeBase2::SendHedgeInstruction (uint64_t ordereqid, const std::vector< SpreadHedgeV3 > & hdg) [virtual]
Sends a hedge instruction.
Parameters
ordereqid The order request ID.
hdg The vector of spread hedge instructions.
References LogMe().
SendMassAction()
virtual void KTN::ExchangeBase2::SendMassAction (KTN::Order & order) [pure virtual]
Sends a mass action.
Parameters
order The order to send.
Implemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
SettFile()
std::string KTN::ExchangeBase2::SettFile ()
Gets the settings file path.
Returns
The settings file path.
Stop()
virtual void KTN::ExchangeBase2::Stop () [pure virtual]
Stops the exchange.
Implemented in KTN::CME::CmeAlgo, and KTN::CME::CmeGT5.
StopBase()
void ExchangeBase2::StopBase () [protected]
Stops the base exchange.
Member Data Documentation
_hedgeMap
SpreadHedgeCircBuff KTN::ExchangeBase2::_hedgeMap [protected]
_hedgeOrds
HashMap<uint64_t, std::vector<KTN::OrderPod>, 1000> KTN::ExchangeBase2::_hedgeOrds [protected]
_logsvc
LogSvc* KTN::ExchangeBase2::_logsvc [protected]
_msgevents
std::unordered_map<std::string, msgevents> KTN::ExchangeBase2::_msgevents [protected]
_msgratio
std::unordered_map<std::string, msgrate> KTN::ExchangeBase2::_msgratio [protected]
_State
ExchState KTN::ExchangeBase2::_State [protected]
_trk
PerformanceTracker KTN::ExchangeBase2::_trk [protected]
The documentation for this class was generated from the following files:
ExchangeHandlers2/ExchangeBase2.hpp
ExchangeHandlers2/ExchangeBase2.cpp