KTN::Core::BufferPool Class Reference
The BufferPool class represents a pool of buffers.
#include <BufferPool.hpp>
Public Member Functions
BufferPool (size_t buffer_size, size_t pool_size)
Constructs a BufferPool object with the specified buffer size and pool size.
~BufferPool ()
Destructor for the BufferPool object.
KTNBuf * get ()
Retrieves a buffer from the pool.
bool put (KTNBuf *buffer)
Puts a buffer back into the pool.
size_t size ()
Gets the current size of the buffer pool.
void Load ()
Loads the buffer pool.
Detailed Description
The BufferPool class represents a pool of buffers.
Constructor & Destructor Documentation
BufferPool()
BufferPool::BufferPool (size_t buffer_size, size_t pool_size)
Constructs a BufferPool object with the specified buffer size and pool size.
Parameters
buffer_size The size of each buffer in bytes.
pool_size The maximum number of buffers in the pool.
References Load().
~BufferPool()
BufferPool::~BufferPool ()
Destructor for the BufferPool object.
Member Function Documentation
get()
KTNBuf * BufferPool::get ()
Retrieves a buffer from the pool.
Returns
A pointer to the retrieved buffer.
References Load().
Referenced by KTN::CME::CmeAlgo::Send(), and KTN::CME::CmeGT5::Send().
Load()
void BufferPool::Load ()
Loads the buffer pool.
Referenced by BufferPool(), and get().
put()
bool BufferPool::put (KTNBuf * buffer)
Puts a buffer back into the pool.
Parameters
buffer A pointer to the buffer to be put back.
Returns
True if the buffer was successfully put back, false otherwise.
Referenced by KTN::CME::CmeAlgo::Send(), and KTN::CME::CmeGT5::Send().
size()
size_t KTN::Core::BufferPool::size () [inline]
Gets the current size of the buffer pool.
Returns
The current size of the buffer pool.
The documentation for this class was generated from the following files:
Core/BufferPool.hpp
Core/BufferPool.cpp