Raptor2 Class Reference
Represents the Raptor2 Main Exchange Handler class that extends NamedThread, MenuCallback, and IExchangeSender.
#include <Raptor2.hpp>
Public Member Functions
Raptor2 (const string &settingsfile)
Constructs a Raptor2 object with the specified settings file.
virtual ~Raptor2 ()
Destroys the Raptor2 object.
void Stop ()
Stops the Raptor2 object.
void Run () override
Runs the Raptor2 object.
int Subscribe (SessionCallback *cb)
Subscribes a session callback to the Raptor2 object.
void Send (KTN::OrderPod &order, int action)
Sends an order with the specified action to the Raptor2 object.
void SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > &hdg)
Sends a hedge instruction with the specified order request ID and hedge to the Raptor2 object.
void SendOrderWithHedge (OrderWithHedge &oh)
Sends an order with hedge to the Raptor2 object.
void BankTas (std::string secgrp, vector< KTN::OrderPod > ords)
Banks the TAS orders with the specified security group and orders.
void BankHedgeOrders (uint64_t ordereqid, const vector< KTN::OrderPod > &ords)
Banks the hedge orders with the specified order request ID and orders.
void AlgoJson (std::string json, ExchCmd::Enum cmd)
Sends an algorithm JSON command with the specified JSON and command to the Raptor2 object.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Public Member Functions inherited from MenuCallback
MenuCallback ()
Constructs a MenuCallback object.
virtual ~MenuCallback ()
Destroys the MenuCallback object.
Public Member Functions inherited from IExchangeSender
IExchangeSender ()
Default constructor.
virtual ~IExchangeSender ()
Destructor.
Detailed Description
Represents the Raptor2 Main Exchange Handler class that extends NamedThread, MenuCallback, and IExchangeSender.
Constructor & Destructor Documentation
Raptor2()
Raptor2::Raptor2 (const string & settingsfile)
Constructs a Raptor2 object with the specified settings file.
Parameters
settingsfile The path to the settings file.
~Raptor2()
Raptor2::~Raptor2 () [virtual]
Destroys the Raptor2 object.
Member Function Documentation
AlgoJson()
void Raptor2::AlgoJson (std::string json, ExchCmd::Enum cmd) [virtual]
Sends an algorithm JSON command with the specified JSON and command to the Raptor2 object.
Parameters
json The JSON command.
cmd The command to perform.
Implements IExchangeSender.
BankHedgeOrders()
void Raptor2::BankHedgeOrders (uint64_t ordereqid, const vector< KTN::OrderPod > & ords) [virtual]
Banks the hedge orders with the specified order request ID and orders.
Parameters
ordereqid The order request ID.
ords The orders to bank.
Implements IExchangeSender.
BankTas()
void Raptor2::BankTas (std::string secgrp, vector< KTN::OrderPod > ords) [virtual]
Banks the TAS orders with the specified security group and orders.
Parameters
secgrp The security group.
ords The orders to bank.
Implements IExchangeSender.
Run()
void Raptor2::Run () [override], [virtual]
Runs the Raptor2 object.
Implements NamedThread.
References KTN::ExchangeManager::onCommand().
Send()
void Raptor2::Send (KTN::OrderPod & order, int action) [virtual]
Sends an order with the specified action to the Raptor2 object.
Parameters
order The order to send.
action The action to perform on the order.
Implements IExchangeSender.
References KTN::ExchangeManager::onCommand().
SendHedgeInstruction()
void Raptor2::SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > & hdg) [virtual]
Sends a hedge instruction with the specified order request ID and hedge to the Raptor2 object.
Parameters
ordereqid The order request ID.
hdg The hedge to send.
Implements IExchangeSender.
References KTN::ExchangeManager::onCommand().
SendOrderWithHedge()
void Raptor2::SendOrderWithHedge (OrderWithHedge & oh) [virtual]
Sends an order with hedge to the Raptor2 object.
Parameters
oh The order with hedge to send.
Implements IExchangeSender.
References KTN::ExchangeManager::onCommand(), and KTN::OrderPod::orderReqId.
Stop()
void Raptor2::Stop ()
Stops the Raptor2 object.
References KTN::ExchangeManager::onCommand(), KTN::ORD::OrderHandlerZmqV6::Stop(), and KTN::AlgoServiceBrokerV3::StopAllAlgos().
Subscribe()
int Raptor2::Subscribe (SessionCallback * cb) [virtual]
Subscribes a session callback to the Raptor2 object.
Parameters
cb The session callback to subscribe.
Returns
The subscription ID.
Implements IExchangeSender.
The documentation for this class was generated from the following files:
Raptor2.hpp
Raptor2.cpp