rapidxml::xml_document< Ch > Class Template Reference
#include <rapidxml.hpp>
Public Member Functions
xml_document ()
Constructs empty XML document.
template<int Flags>
void parse (Ch *text)
void clear ()
Public Member Functions inherited from rapidxml::xml_node< char >
xml_node (node_type type)
node_type type () const
void type (node_type type)
xml_document< char > * document () const
xml_node< char > * first_node (const char *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_node< char > * last_node (const char *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_node< char > * previous_sibling (const char *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_node< char > * next_sibling (const char *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_attribute< char > * first_attribute (const char *name=0, std::size_t name_size=0, bool case_sensitive=true) const
xml_attribute< char > * last_attribute (const char *name=0, std::size_t name_size=0, bool case_sensitive=true) const
void prepend_node (xml_node< char > *child)
void append_node (xml_node< char > *child)
void insert_node (xml_node< char > *where, xml_node< char > *child)
void remove_first_node ()
void remove_last_node ()
void remove_node (xml_node< char > *where)
Removes specified child from the node.
void remove_all_nodes ()
Removes all child nodes (but not attributes).
void prepend_attribute (xml_attribute< char > *attribute)
void append_attribute (xml_attribute< char > *attribute)
void insert_attribute (xml_attribute< char > *where, xml_attribute< char > *attribute)
void remove_first_attribute ()
void remove_last_attribute ()
void remove_attribute (xml_attribute< char > *where)
void remove_all_attributes ()
Removes all attributes of node.
Public Member Functions inherited from rapidxml::xml_base< char >
char * name () const
void name (const char *name, std::size_t size)
void name (const char *name)
std::size_t name_size () const
char * value () const
void value (const char *value, std::size_t size)
void value (const char *value)
std::size_t value_size () const
xml_node< char > * parent () const
Public Member Functions inherited from rapidxml::memory_pool< char >
memory_pool ()
Constructs empty pool with default allocator functions.
~memory_pool ()
xml_node< char > * allocate_node (node_type type, const char *name=0, const char *value=0, std::size_t name_size=0, std::size_t value_size=0)
xml_attribute< char > * allocate_attribute (const char *name=0, const char *value=0, std::size_t name_size=0, std::size_t value_size=0)
char * allocate_string (const char *source=0, std::size_t size=0)
xml_node< char > * clone_node (const xml_node< char > *source, xml_node< char > *result=0)
void clear ()
void set_allocator (alloc_func *af, free_func *ff)
Additional Inherited Members
Static Protected Member Functions inherited from rapidxml::xml_base< char >
static char * nullstr ()
Protected Attributes inherited from rapidxml::xml_base< char >
char * m_name
char * m_value
std::size_t m_name_size
std::size_t m_value_size
xml_node< char > * m_parent
Detailed Description
template<class Ch = char>
class rapidxml::xml_document< Ch >
This class represents root of the DOM hierarchy. It is also an xml_node and a memory_pool through public inheritance. Use parse() function to build a DOM tree from a zero-terminated XML text string. parse() function allocates memory for nodes and attributes by using functions of xml_document, which are inherited from memory_pool. To access root node of the document, use the document itself, as if it was an xml_node.
Parameters
Ch Character type to use.
Constructor & Destructor Documentation
xml_document()
template<class Ch = char>
rapidxml::xml_document< Ch >::xml_document () [inline]
Constructs empty XML document.
Member Function Documentation
clear()
template<class Ch = char>
void rapidxml::xml_document< Ch >::clear () [inline]
Clears the document by deleting all nodes and clearing the memory pool. All nodes owned by document pool are destroyed.
References rapidxml::memory_pool< Ch >::clear(), rapidxml::xml_node< char >::remove_all_attributes(), and rapidxml::xml_node< char >::remove_all_nodes().
parse()
template<class Ch = char>
template<int Flags>
void rapidxml::xml_document< Ch >::parse (Ch * text) [inline]
Parses zero-terminated XML string according to given flags. Passed string will be modified by the parser, unless rapidxml::parse_non_destructive flag is used. The string must persist for the lifetime of the document. In case of error, rapidxml::parse_error exception will be thrown.
 If you want to parse contents of a file, you must first load the file into the memory, and pass pointer to its beginning. Make sure that data is zero-terminated.
 Document can be parsed into multiple times. Each new call to parse removes previous nodes and attributes (if any), but does not clear memory pool.
Parameters
text XML data to parse; pointer is non-const to denote fact that this data may be modified by the parser.
References rapidxml::xml_node< char >::append_node(), rapidxml::xml_node< char >::remove_all_attributes(), and rapidxml::xml_node< char >::remove_all_nodes().
The documentation for this class was generated from the following file:
C:/Users/sgaer/source/repos/katanafinancial/OccamCME4/OccamCME4/src/external/rapidxml/rapidxml.hpp