KTN::ALGO::OrderLoader Class Reference
The OrderLoader class is responsible for loading orders from a file and providing various order-related functionalities.
#include <OrderLoader.hpp>
Public Member Functions
vector< KTN::Order > GetOrders (string filename, string tag, string strat, string source, string guid, UserInfo info)
GetOrders loads orders from a file based on the provided parameters.
std::string NextId ()
NextId generates the next ID for an order.
vector< KTN::Order > LoadFile (string filename)
LoadFile loads orders from a file.
KTN::Order NewOrderBuilder (KTN::Order orig)
NewOrderBuilder builds a new order based on the provided original order.
Detailed Description
The OrderLoader class is responsible for loading orders from a file and providing various order-related functionalities.
Constructor & Destructor Documentation
OrderLoader()
OrderLoader::OrderLoader ()
~OrderLoader()
OrderLoader::~OrderLoader () [virtual]
Member Function Documentation
GetOrders()
vector< KTN::Order > OrderLoader::GetOrders (string filename, string tag, string strat, string source, string guid, UserInfo info)
GetOrders loads orders from a file based on the provided parameters.
Parameters
filename The name of the file to load orders from.
tag The tag associated with the orders.
strat The strategy associated with the orders.
source The source of the orders.
guid The GUID associated with the orders.
info The user information associated with the orders.
Returns
A vector of orders loaded from the file.
References LoadFile().
LoadFile()
vector< KTN::Order > OrderLoader::LoadFile (string filename)
LoadFile loads orders from a file.
Parameters
filename The name of the file to load orders from.
Returns
A vector of orders loaded from the file.
References NewOrderBuilder(), and StringSplitter::Split().
Referenced by GetOrders().
NewOrderBuilder()
KTN::Order OrderLoader::NewOrderBuilder (KTN::Order orig)
NewOrderBuilder builds a new order based on the provided original order.
Parameters
orig The original order.
Returns
The new order built based on the original order.
References UserInfo::groupname, NextId(), UserInfo::org, and UserInfo::user.
Referenced by LoadFile().
NextId()
std::string OrderLoader::NextId ()
NextId generates the next ID for an order.
Returns
The next ID for an order.
Referenced by NewOrderBuilder().
The documentation for this class was generated from the following files:
AlgoEngines/OrderLoader.hpp
AlgoEngines/OrderLoader.cpp