CustomHFTMap Class Reference
CustomHFTMap class represents a custom ultra low latency hash map implementation.
#include <CustomHFTMap.hpp>
Public Member Functions
CustomHFTMap ()
Default constructor for CustomHFTMap.
void insert (uint64_t key, OrderPod *value)
Inserts a key-value pair into the map.
OrderPod * get (uint64_t key)
Retrieves the value associated with the given key.
bool find (uint64_t key)
Checks if the given key exists in the map.
int size ()
Returns the number of key-value pairs in the map.
OrderPod * at (size_t index)
Returns the value at the specified index.
void clear ()
Clears the map, removing all key-value pairs.
void cleardead ()
Clears the map, removing all key-value pairs with dead keys.
void erase (uint64_t key)
Removes the key-value pair with the given key from the map.
OrderPod & operator[] (uint64_t key)
Overloaded [] operator for assignment and creation.
Detailed Description
CustomHFTMap class represents a custom ultra low latency hash map implementation.
Constructor & Destructor Documentation
CustomHFTMap()
CustomHFTMap::CustomHFTMap ()
Default constructor for CustomHFTMap.
Member Function Documentation
at()
OrderPod * CustomHFTMap::at (size_t index) [inline]
Returns the value at the specified index.
Parameters
index The index of the value to retrieve.
Returns
A pointer to the value at the specified index, or a new OrderPod object if the index is out of range.
clear()
void CustomHFTMap::clear ()
Clears the map, removing all key-value pairs.
Referenced by OrderManagerV5::Clear().
cleardead()
void CustomHFTMap::cleardead ()
Clears the map, removing all key-value pairs with dead keys.
Referenced by OrderManagerV5::ClearDeadOrders().
erase()
void CustomHFTMap::erase (uint64_t key)
Removes the key-value pair with the given key from the map.
Parameters
key The key to remove.
find()
bool CustomHFTMap::find (uint64_t key)
Checks if the given key exists in the map.
Parameters
key The key to search for.
Returns
True if the key exists, false otherwise.
Referenced by OrderManagerV5::Exists().
get()
OrderPod * CustomHFTMap::get (uint64_t key)
Retrieves the value associated with the given key.
Parameters
key The key to search for.
Returns
A pointer to the value associated with the key, or nullptr if the key is not found.
Referenced by OrderManagerV5::GetOrder(), OrderManagerV5::minOrderExecSpreadLeg(), OrderManagerV5::minOrderExecution(), OrderManagerV5::UpdateExecution(), and OrderManagerV5::UpdateSpreadLegExecution().
insert()
void CustomHFTMap::insert (uint64_t key, OrderPod * value)
Inserts a key-value pair into the map.
Parameters
key The key to insert.
value The value to insert.
operator[]()
OrderPod & CustomHFTMap::operator[] (uint64_t key)
Overloaded [] operator for assignment and creation.
Parameters
key The key to access.
Returns
A reference to the value associated with the key.
size()
int CustomHFTMap::size () [inline]
Returns the number of key-value pairs in the map.
Returns
The size of the map.
Referenced by OrderManagerV5::Count().
The documentation for this class was generated from the following files:
Maps/CustomHFTMap.hpp
Maps/CustomHFTMap.cpp