KTN::Skewer Class Reference
The Skewer class represents an implementation of an order book skew trading algorithm.
#include <Skewer.hpp>
Public Member Functions
Skewer (AlgoInitializer p)
Constructs a Skewer object.
virtual ~Skewer ()
Destroys the Skewer object.
void onJson (std::string json) override
Handles the JSON input for the Skewer algorithm.
void onLaunch (std::string json) override
Handles the launch of the Skewer algorithm.
void onCalculate () override
Performs the calculation for the Skewer algorithm.
void onMktData (int index) override
Handles the market data for the Skewer algorithm.
void minOrderExecution (KTN::OrderPod &ord, bool hedgeSent) override
Executes the minimum order for the Skewer algorithm.
void Enable (bool bEnable) override
Enables or disables the Skewer algorithm.
void ResetPosition () override
Resets the position for the Skewer algorithm.
void Print () override
Prints the status of the Skewer algorithm.
void ToggleCommand (int id) override
Toggles a command for the Skewer algorithm.
void Restart () override
Restarts the Skewer algorithm.
void onTimerStateChange (TimerState::Enum state)
Handles the state change of the timer for the Skewer algorithm.
void onTimerInterval (TimerInterval::Enum interval)
Handles the interval change of the timer for the Skewer algorithm.
vector< string > Symbols ()
Retrieves the symbols used in the Skewer algorithm.
Public Member Functions inherited from KTN::AlgoBaseV3
AlgoBaseV3 (AlgoInitializer params)
Constructs a new AlgoBaseV3 object.
virtual ~AlgoBaseV3 ()
Destructor for AlgoBaseV3.
std::string GUID ()
Returns the globally unique identifier (GUID) of the algorithm.
void Poll ()
Polls the system for events.
virtual void onEngineJson (EngineCommand &cmd)
Processes algo engine-specific commands.
virtual void onTrade (int index, double price, double size, int aggressor)
Handles a trade event.
virtual void onHeartbeat (int msgseqnum)
Handles session heartbeat events.
virtual void onSessionStatus (std::string exch, int mktsegid, int protocol, std::string desc, std::string state)
Handles session status updates.
void onSpreadLegOrderExecution (KTN::Order &ord)
Executes spread leg orders.
virtual void minOrderAck (KTN::OrderPod &ord) override
This method is called when a minimum order acknowledgement is received.
virtual void minOrderCancel (KTN::OrderPod &ord) override
This method is called when a minimum order cancellation is received.
virtual void minOrderModify (KTN::OrderPod &ord) override
This method is called when a minimum order modification is received.
virtual void minOrderReject (KTN::OrderPod &ord, const std::string &text)
Handles order rejection events.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const std::string &text)
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const std::string &text)
virtual void onHedgeOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price9, uint16_t instindex)
Handles hedge order sent events.
virtual void onOrderSent (char *clordid, uint64_t reqid, int32_t secid, KOrderSide::Enum side, uint32_t qty, int32_t price, KOrderAlgoTrigger::Enum trig)
Handles order sent events.
virtual void Shutdown ()
Shuts down the algorithm.
void shutdownHandler ()
Shuts down the algorithm handler.
virtual void onMktDataBidAsk (const algomd &md)
Handles bid-ask market data updates.
virtual void onMktDataTrade (const algomd &md)
Handles trade market data updates.
Public Member Functions inherited from KTN::AlgoMktDataCallback
AlgoMktDataCallback ()
Default constructor for AlgoMktDataCallback.
virtual ~AlgoMktDataCallback ()
Virtual destructor for AlgoMktDataCallback.
virtual void onStateChange (int state)
This method is called when the state of the algorithm changes.
Public Member Functions inherited from KTN::SessionCallback
virtual void onSessionStatus (string exch, int mktsegid, int protocol, string desc, string state)=0
This method is called when the session status changes.
virtual void minOrderReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order rejection is received.
virtual void minOrderCancelReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancellation rejection is received.
virtual void minOrderCancelReplaceReject (KTN::OrderPod &ord, const string &text)=0
This method is called when a minimum order cancel/replace rejection is received.
Public Member Functions inherited from TimerCallback
Additional Inherited Members
Public Attributes inherited from KTN::AlgoBaseV3
std::vector< instrument > _LEGS
Protected Member Functions inherited from KTN::AlgoBaseV3
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
void Notify (std::string msg, MsgLevel::Enum level, MsgType::Enum msgtype)
void PrintMdMap ()
void PrintBookMap ()
void PrintBook (instrument inst)
void UpdateMetaParams (algometa meta)
void ChangeQuoteState (const QuoteState::Enum &newstate)
void ChangeHedgeState (const HedgeState::Enum &newstate)
void RegisterCallbackId ()
void RegisterParams (std::string json)
void RegisterCmeSecId (instrument &inst)
algomd & GetQuote (const instrument &inst)
bool GetQuote (const instrument &inst, algomd &md)
bool GetQuoteByIndex (int index, algomd &md)
bookmd & GetBook (const instrument &inst)
bool GetBook (const instrument &inst, bookmd &book)
bool RiskCheckQty (int qty, int totalqty, int execqty, KOrderSide::Enum side)
void SendOrder (KTN::OrderPod &ord, instrument &inst)
void SendOrderWithHedge (OrderWithHedge &oh, instrument &inst)
int GetBid (int index)
int GetAsk (int index)
void GetBid (int index, atomicquote &qt)
void GetAsk (int index, atomicquote &qt)
bool isValidSecId (uint32_t secid)
const algomd & findBySecId (int id) const
int indexBySecId (int id)
void GenIds (std::string prefix)
void AddReportingMsg (std::string msg, std::string msgtype)
void AddCmeSymbol (std::string symbol)
std::string getCertSymbol (long secid)
int32_t getCertSecId (std::string symbol)
int32_t getProdSecIdFromCert (long secid)
Protected Attributes inherited from KTN::AlgoBaseV3
std::atomic< bool > _ACTIVE
IExchangeSender * _ordersender
KtnCmeMdpV4 * _mdh
CmeMsgw _msgw
OrderManagerV5 _Ords
PerformanceTracker _trk
AlgoHelpers helpers
Slacker _SLACK
AlgoV3Reporter * _algorpt
genericstats _mystats
LogMsg _LOG
algometa _PARAMS
int _NUMLEGS
algomd _MD [8]
std::unordered_map< std::string, instrument > _LEGMAP
std::unordered_map< int, instrument > _SECIDMAP
std::unordered_map< long, std::string > _certIdMap
std::unordered_map< std::string, long > _certIdSymbolMap
QuoteState::Enum _QuotingState
HedgeState::Enum _HedgingState
Settings settings_
volatile bool stopped_
int _EXCH_CALLBACK_ID
bool _CME_BY_SECID
bool _bQuoteInFlight
std::string _GUID
std::string _ORG
bool _MEASURE
bool _CERTNR
int _MKT_DATA_CPU
bool _MKT_DATA_OK
bool _GOT_DATA
long _DATA_TRIES
bool _WATCH_TRADES
bool _WATCH_VOLUME
bool _USEAUDIT
bool _ENABLED
bool _CAN_TRADE
bool _HANDLER_STARTED
double _NETPOS
double _TOTALEXEC
bool _USE_REPORTING_MSGS
volatile bool _RPT_ACTIVE
bool _USE_STOPS
bool _CME_MKT_DATA_STARTED
bool _ALLSYMBOLS
std::string _BASE
int _CNT
int _TESTID
int _GROUPCNT
std::string _SPRDID
int _CORE
bool _VERBOSE
std::string m_Name
Detailed Description
The Skewer class represents an implementation of an order book skew trading algorithm.
Constructor & Destructor Documentation
Skewer()
KTN::Skewer::Skewer (AlgoInitializer p)
Constructs a Skewer object.
Parameters
p The AlgoInitializer object.
References KTN::notify::Slacker::InitAndRun(), and KtnCmeMdpV4::SetHandleDepth().
~Skewer()
KTN::Skewer::~Skewer () [virtual]
Destroys the Skewer object.
References KTN::ALGO::IntervalTimer::Started(), and KTN::ALGO::IntervalTimer::Stop().
Member Function Documentation
Enable()
void KTN::Skewer::Enable (bool bEnable) [override], [virtual]
Enables or disables the Skewer algorithm.
Parameters
bEnable A boolean indicating if the algorithm should be enabled.
Implements KTN::AlgoBaseV3.
References OrderManagerV5::ClearDeadOrders(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, instrument::lastSentSellPrice, KTN::ALGO::IntervalTimer::Pause(), and KTN::ALGO::IntervalTimer::Started().
Referenced by minOrderExecution(), onJson(), and ResetPosition().
minOrderExecution()
void KTN::Skewer::minOrderExecution (KTN::OrderPod & ord, bool hedgeSent) [override], [virtual]
Executes the minimum order for the Skewer algorithm.
Parameters
ord The OrderPod object.
hedgeSent A boolean indicating if the hedge order is sent.
Reimplemented from KTN::AlgoBaseV3.
References KTN::OrderPod::exchordid, KTN::notify::slackmsg::color, Enable(), KTN::OrderPod::lastpx, KTN::OrderPod::lastqty, OrderManagerV5::minOrderExecSpreadLeg(), OrderManagerV5::minOrderExecution(), KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdFillType, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdState, KTN::notify::slackmsg::preview, KTN::OrderPod::secid, KTN::notify::Slacker::Send(), KTN::ALGO::IntervalTimer::Started(), KTN::ALGO::IntervalTimer::Stop(), and KTN::notify::slackmsg::text.
onCalculate()
void KTN::Skewer::onCalculate () [override], [virtual]
Performs the calculation for the Skewer algorithm.
Implements KTN::AlgoBaseV3.
onJson()
void KTN::Skewer::onJson (std::string json) [override], [virtual]
Handles the JSON input for the Skewer algorithm.
Parameters
json The JSON input string.
Implements KTN::AlgoBaseV3.
References instrument::activeQuoting, Enable(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, instrument::lastSentSellPrice, KTN::ALGO::IntervalTimer::Pause(), ResetPosition(), KTN::ALGO::IntervalTimer::Start(), KTN::ALGO::IntervalTimer::Started(), and KTN::ALGO::IntervalTimer::UpdateInterval().
Referenced by onLaunch().
onLaunch()
void KTN::Skewer::onLaunch (std::string json) [override], [virtual]
Handles the launch of the Skewer algorithm.
Parameters
json The JSON input string.
Implements KTN::AlgoBaseV3.
References onJson(), and SkewerParams::parse().
onMktData()
void KTN::Skewer::onMktData (int index) [override], [virtual]
Handles the market data for the Skewer algorithm.
Parameters
index The index of the market data.
Reimplemented from KTN::AlgoBaseV3.
onTimerInterval()
void KTN::Skewer::onTimerInterval (TimerInterval::Enum interval) [virtual]
Handles the interval change of the timer for the Skewer algorithm.
Parameters
interval The TimerInterval enumeration value.
Implements TimerCallback.
onTimerStateChange()
void KTN::Skewer::onTimerStateChange (TimerState::Enum state) [virtual]
Handles the state change of the timer for the Skewer algorithm.
Parameters
state The TimerState enumeration value.
Implements TimerCallback.
Print()
void KTN::Skewer::Print () [override], [virtual]
Prints the status of the Skewer algorithm.
Reimplemented from KTN::AlgoBaseV3.
References PerformanceTracker::clear(), msgstats::mods, msgstats::news, KTN::AlgoBaseV3::Print(), OrderManagerV5::Print(), PerformanceTracker::printMeasurements(), instrument::symbol, and instrument::totalexec.
ResetPosition()
void KTN::Skewer::ResetPosition () [override], [virtual]
Resets the position for the Skewer algorithm.
Reimplemented from KTN::AlgoBaseV3.
References instrument::effective, Enable(), algometa::Enabled, instrument::lastAsk, instrument::lastBid, instrument::lastSentBuyPrice, instrument::lastSentSellPrice, instrument::position, KTN::ALGO::IntervalTimer::Stop(), and instrument::totalexec.
Referenced by onJson().
Restart()
void KTN::Skewer::Restart () [override], [virtual]
Restarts the Skewer algorithm.
Reimplemented from KTN::AlgoBaseV3.
Symbols()
vector< string > KTN::Skewer::Symbols ()
Retrieves the symbols used in the Skewer algorithm.
Returns
A vector of strings representing the symbols.
References instrument::symbol.
ToggleCommand()
void KTN::Skewer::ToggleCommand (int id) [override], [virtual]
Toggles a command for the Skewer algorithm.
Parameters
id The ID of the command to toggle.
Reimplemented from KTN::AlgoBaseV3.
The documentation for this class was generated from the following files:
Algos/Skewer.hpp
Algos/Skewer.cpp