CmeSettingsHelper Class Reference
Static Public Member Functions
static bool GetBool (const string &key)
static int GetInt (const string &key)
static string GetString (const string &key)
static long GetLong (const string &key)
Detailed Description
Member Function Documentation
GetBool()
static bool CmeSettingsHelper::GetBool (const string & key) [inline], [static]
Retrieves a boolean setting value from the Cme File.
Parameters
key The key of the setting.
Returns
The boolean value of the setting.
References Settings::getBoolean().
Referenced by KTN::AlgoBaseV3::AlgoBaseV3(), and KTN::ORD::OrderHandlerZmqV6::OrderHandlerZmqV6().
GetInt()
static int CmeSettingsHelper::GetInt (const string & key) [inline], [static]
Retrieves an integer setting value from the Cme File.
Parameters
key The key of the setting.
Returns
The integer value of the setting.
References Settings::getInteger().
GetLong()
static long CmeSettingsHelper::GetLong (const string & key) [inline], [static]
Retrieves a long setting value from the Cme File.
Parameters
key The key of the setting.
Returns
The long value of the setting.
References Settings::getLong().
GetString()
static string CmeSettingsHelper::GetString (const string & key) [inline], [static]
Retrieves a string setting value from the Cme File.
Parameters
key The key of the setting.
Returns
The string value of the setting.
References Settings::get().
The documentation for this class was generated from the following file:
exchsupport/cme/CmeSettingsHelper.hpp