LegParamParser Class Reference
The LegParamParser class provides methods to parse and retrieve leg parameters.
#include <LegParamParser.hpp>
Static Public Member Functions
static vector< instrument > ParseSpreadLegs (string json)
Parses the spread legs from the given JSON string.
static std::unordered_map< string, bool > GetActiveQuoteSetting (Document &d)
Retrieves the active quote settings from the given JSON document.
static instrument GetCmeLeg (string symbol, KOrderProdType::Enum prodtype, int index)
Retrieves the CME leg for the given symbol, product type, and index.
Detailed Description
The LegParamParser class provides methods to parse and retrieve leg parameters.
Member Function Documentation
GetActiveQuoteSetting()
std::unordered_map< string, bool > LegParamParser::GetActiveQuoteSetting (Document & d) [static]
Retrieves the active quote settings from the given JSON document.
Parameters
d The JSON document.
Returns
An unordered map with the active quote settings.
GetCmeLeg()
instrument LegParamParser::GetCmeLeg (string symbol, KOrderProdType::Enum prodtype, int index) [static]
Retrieves the CME leg for the given symbol, product type, and index.
Parameters
symbol The symbol of the leg.
prodtype The product type of the leg.
index The index of the leg.
Returns
The CME leg instrument.
References instrument::activeQuoting, instrument::exch, instrument::index, instrument::iscme, instrument::iside, instrument::lastAsk, instrument::lastBid, instrument::pricemult, instrument::prodtype, instrument::spreadmult, instrument::symbol, and instrument::tickvalue.
ParseSpreadLegs()
vector< instrument > LegParamParser::ParseSpreadLegs (string json) [static]
Parses the spread legs from the given JSON string.
Parameters
json The JSON string containing the spread legs.
Returns
A vector of instrument objects representing the spread legs.
References instrument::activeQuoting, instrument::exch, instrument::index, instrument::iscme, instrument::iside, instrument::lastAsk, instrument::lastBid, instrument::pricemult, instrument::Print(), instrument::prodtype, instrument::spreadmult, instrument::squeeze, instrument::symbol, and instrument::tickvalue.
Referenced by AlgoFactory::LaunchAlgo(), KTN::MultiSpreaderV3::onJson(), and AlgoFactory::ParseLegs().
The documentation for this class was generated from the following files:
AlgoParams/LegParamParser.hpp
AlgoParams/LegParamParser.cpp