KTN::Core::SimpleMap< K, T > Class Template Reference
A simple map implementation that associates keys with values.
#include <SimpleMap.hpp>
Public Member Functions
SimpleMap (size_t capacity)
Constructs a SimpleMap object with the specified capacity.
void insert (K key, T *value)
Inserts a key-value pair into the map.
T * get (K key)
Retrieves the value associated with the specified key.
bool find (K key)
Checks if the map contains the specified key.
int size () const
Gets the number of elements in the map.
T * at (int index) const
Retrieves the value at the specified index.
void clear ()
Clears the map, removing all elements.
void cleardead ()
Clears any dead elements from the map.
void erase (K key)
Removes the element with the specified key from the map.
T & operator[] (K key)
Retrieves the value associated with the specified key.
Detailed Description
template<typename K, typename T>
class KTN::Core::SimpleMap< K, T >
A simple map implementation that associates keys with values.
Template Parameters
K The type of the keys.
T The type of the values.
Constructor & Destructor Documentation
SimpleMap()
template<typename K , typename T >
KTN::Core::SimpleMap< K, T >::SimpleMap (size_t capacity) [inline]
Constructs a SimpleMap object with the specified capacity.
Parameters
capacity The maximum number of elements the map can hold.
Member Function Documentation
at()
template<typename K , typename T >
T * KTN::Core::SimpleMap< K, T >::at (int index) const [inline]
Retrieves the value at the specified index.
Parameters
index The index of the value to retrieve.
Returns
A pointer to the value at the specified index, or nullptr if the index is out of bounds.
References KTN::Core::AllocatorBase< T >::get().
clear()
template<typename K , typename T >
void KTN::Core::SimpleMap< K, T >::clear () [inline]
Clears the map, removing all elements.
cleardead()
template<typename K , typename T >
void KTN::Core::SimpleMap< K, T >::cleardead () [inline]
Clears any dead elements from the map.
Implement logic to clear dead elements if needed.
erase()
template<typename K , typename T >
void KTN::Core::SimpleMap< K, T >::erase (K key) [inline]
Removes the element with the specified key from the map.
Parameters
key The key of the element to remove.
References KTN::Core::AllocatorBase< T >::get().
find()
template<typename K , typename T >
bool KTN::Core::SimpleMap< K, T >::find (K key) [inline]
Checks if the map contains the specified key.
Parameters
key The key to search for.
Returns
true if the key is found, false otherwise.
get()
template<typename K , typename T >
T * KTN::Core::SimpleMap< K, T >::get (K key) [inline]
Retrieves the value associated with the specified key.
Parameters
key The key to search for.
Returns
A pointer to the value associated with the key, or nullptr if the key is not found.
References KTN::Core::AllocatorBase< T >::get().
Referenced by KTN::Core::SimpleMap< K, T >::operator[]().
insert()
template<typename K , typename T >
void KTN::Core::SimpleMap< K, T >::insert (K key, T * value) [inline]
Inserts a key-value pair into the map.
Parameters
key The key to insert.
value A pointer to the value to insert.
References KTN::Core::AllocatorBase< T >::get().
Referenced by KTN::Core::SimpleMap< K, T >::operator[]().
operator[]()
template<typename K , typename T >
T & KTN::Core::SimpleMap< K, T >::operator[] (K key) [inline]
Retrieves the value associated with the specified key.
If the key is not found, a new value is created and associated with the key.
Parameters
key The key to search for.
Returns
A reference to the value associated with the key.
References KTN::Core::SimpleMap< K, T >::get(), and KTN::Core::SimpleMap< K, T >::insert().
size()
template<typename K , typename T >
int KTN::Core::SimpleMap< K, T >::size () const [inline]
Gets the number of elements in the map.
Returns
The number of elements in the map.
The documentation for this class was generated from the following file:
Maps/SimpleMap.hpp