KTN::REPORTER::OrderReporterV5 Class Reference
The OrderReporterV5 class is responsible for reporting orders.
#include <OrderReporterV5.hpp>
Public Member Functions
OrderReporterV5 (string owner)
Constructs an OrderReporterV5 object with the specified owner.
~OrderReporterV5 ()
Destroys the OrderReporterV5 object.
void Report (const KTN::OrderPod &ord)
Reports the specified order.
virtual void DoWork () override
Performs the work of the OrderReporterV5 object.
void StopWork ()
Stops the work of the OrderReporterV5 object.
void UpdateMetaParams (const algometa &meta, bool certnr)
Updates the meta parameters with the specified values.
void UpdateUGOMap (uint64_t reqid, UserInfo ugo)
Updates the UGO map with the specified request ID and user info.
void UpdateTagMap (uint64_t reqid, string tag)
Updates the tag map with the specified request ID and tag.
Detailed Description
The OrderReporterV5 class is responsible for reporting orders.
Constructor & Destructor Documentation
OrderReporterV5()
OrderReporterV5::OrderReporterV5 (string owner)
Constructs an OrderReporterV5 object with the specified owner.
Parameters
owner The owner of the OrderReporterV5 object.
References Settings::get(), and KTN::REPORTER::ReporterBase::Start().
~OrderReporterV5()
OrderReporterV5::~OrderReporterV5 ()
Destroys the OrderReporterV5 object.
Member Function Documentation
DoWork()
void OrderReporterV5::DoWork () [override], [virtual]
Performs the work of the OrderReporterV5 object.
Implements KTN::REPORTER::ReporterBase.
References KTN::Core::SPSCRingBuffer< T >::empty(), KTN::REPORTER::ReporterBase::LogMe(), KTN::OrderPod::OrdExch, KTN::OrderPod::secid, KTN::REPORTER::ReporterBase::SendJson(), KTN::OrderPod::timestamp, and KTN::Core::SPSCRingBuffer< T >::try_pop().
Report()
void OrderReporterV5::Report (const KTN::OrderPod & ord)
Reports the specified order.
Parameters
ord The order to be reported.
References KTN::Core::SPSCRingBuffer< T >::push().
StopWork()
void OrderReporterV5::StopWork ()
Stops the work of the OrderReporterV5 object.
References KTN::REPORTER::ReporterBase::Stop().
UpdateMetaParams()
void OrderReporterV5::UpdateMetaParams (const algometa & meta, bool certnr)
Updates the meta parameters with the specified values.
Parameters
meta The meta parameters to be updated.
certnr A flag indicating whether to update the certificate number.
UpdateTagMap()
void OrderReporterV5::UpdateTagMap (uint64_t reqid, string tag)
Updates the tag map with the specified request ID and tag.
Parameters
reqid The request ID.
tag The tag.
UpdateUGOMap()
void OrderReporterV5::UpdateUGOMap (uint64_t reqid, UserInfo ugo)
Updates the UGO map with the specified request ID and user info.
Parameters
reqid The request ID.
ugo The user info.
The documentation for this class was generated from the following files:
Reporters/OrderReporterV5.hpp
Reporters/OrderReporterV5.cpp