KTN::ORD::OrderHandlerZmqV6 Class Reference
The OrderHandlerZmqV6 class handles the ZMQ communication for order handling. It implements the SessionCallback and IZmqSubscriber interfaces.
#include <OrderHandlerZmqV6.hpp>
Public Member Functions
OrderHandlerZmqV6 (IExchangeSender &exch, int cbid)
Constructs an OrderHandlerZmqV6 object.
virtual ~OrderHandlerZmqV6 ()
Destroys the OrderHandlerZmqV6 object.
virtual void RegisterOrderTemplate (Order &ord)
Registers an order template.
void Stop ()
Stops the order handler.
void Print ()
Prints the order handler.
void LoadTasOrders ()
Loads TAS orders.
void Clear ()
Clears the order handler.
Public Member Functions inherited from KTN::SessionCallback
Public Member Functions inherited from IZmqSubscriber
virtual void onPubMsg (string topic, string payload)=0
Called when a message is received.
Detailed Description
The OrderHandlerZmqV6 class handles the ZMQ communication for order handling. It implements the SessionCallback and IZmqSubscriber interfaces.
Constructor & Destructor Documentation
OrderHandlerZmqV6()
KTN::OrderHandlerZmqV6::OrderHandlerZmqV6 (IExchangeSender & exch, int cbid)
Constructs an OrderHandlerZmqV6 object.
Parameters
exch The exchange sender object.
cbid The callback ID.
References Settings::get(), CmeSettingsHelper::GetBool(), Settings::getBoolean(), Settings::getInteger(), KT01::MSGW::CmeMsgw::LoadProductGatewayFile(), algometa::Strategy, algometa::StratId, algometa::UniqueId, and OrderManagerV5::UpdateMetaParams().
~OrderHandlerZmqV6()
KTN::OrderHandlerZmqV6::~OrderHandlerZmqV6 () [virtual]
Destroys the OrderHandlerZmqV6 object.
References OrderManagerV5::Stop().
Member Function Documentation
Clear()
void KTN::ORD::OrderHandlerZmqV6::Clear () [inline]
Clears the order handler.
LoadTasOrders()
void KTN::OrderHandlerZmqV6::LoadTasOrders ()
Loads TAS orders.
References IExchangeSender::BankTas(), KTN::OrderPod::callbackid, KTN::OrderPod::cert, Settings::get(), Settings::getInteger(), KT01::MSGW::CmeMsgw::getProdSegId(), UserInfo::groupname, KTN::OrderPod::isManual, KTN::OrderPod::leavesqty, KTN::OrderPod::mktsegid, OrderManagerV5::onSentOrderOrdbook(), KTN::OrderPod::OrdAction, KTN::OrderPod::OrdAlgoTrig, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdExch, KTN::OrderPod::OrdSide, KTN::OrderPod::OrdStatus, KTN::OrderPod::OrdTif, KTN::OrderPod::OrdType, UserInfo::org, KTN::OrderPod::price, KTN::OrderPod::quantity, FileOrderLoaderV3::ReadFile(), KTN::OrderPod::secid, KTN::OrderPod::stratid, and UserInfo::user.
Print()
void KTN::OrderHandlerZmqV6::Print ()
Prints the order handler.
References OrderManagerV5::Print().
RegisterOrderTemplate()
void KTN::OrderHandlerZmqV6::RegisterOrderTemplate (Order & ord) [virtual]
Registers an order template.
Parameters
ord The order template to register.
Stop()
void KTN::OrderHandlerZmqV6::Stop ()
Stops the order handler.
Referenced by Raptor2::Stop().
The documentation for this class was generated from the following files:
Orders/OrderHandlerZmqV6.hpp
Orders/OrderHandlerZmqV6.cpp