KTN::ALGO::IntervalTimer Class Reference
The IntervalTimer class represents a timer that triggers at regular intervals.
#include <IntervalTimer.hpp>
Public Member Functions
IntervalTimer (TimerCallback &cb)
Constructs an IntervalTimer object.
~IntervalTimer ()
Destroys the IntervalTimer object.
void Test ()
Test function for the IntervalTimer.
void Pause (bool paused)
Pauses or resumes the timer.
void Start (const std::string &startTime, const std::string &endTime, int intervalsecs, int maxworksecs)
Starts the timer with the specified parameters.
void Stop ()
Stops the timer.
void UpdateInterval (int intervalsecs)
Updates the interval at which the timer triggers.
void ResetInterval ()
Resets the timer interval.
bool Triggered ()
Checks if the timer has been triggered.
bool Started ()
Checks if the timer has started.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
The IntervalTimer class represents a timer that triggers at regular intervals.
Constructor & Destructor Documentation
IntervalTimer()
IntervalTimer::IntervalTimer (TimerCallback & cb)
Constructs an IntervalTimer object.
Parameters
cb The TimerCallback object to be called when the timer triggers.
~IntervalTimer()
IntervalTimer::~IntervalTimer ()
Destroys the IntervalTimer object.
Member Function Documentation
Pause()
void IntervalTimer::Pause (bool paused)
Pauses or resumes the timer.
Parameters
paused True to pause the timer, false to resume.
Referenced by KTN::Skewer::Enable(), KTN::SkewTrader::Enable(), KTN::Twap::Enable(), KTN::Skewer::onJson(), KTN::SkewTrader::onJson(), and KTN::Twap::onJson().
ResetInterval()
void KTN::ALGO::IntervalTimer::ResetInterval () [inline]
Resets the timer interval.
Start()
void IntervalTimer::Start (const std::string & startTime, const std::string & endTime, int intervalsecs, int maxworksecs)
Starts the timer with the specified parameters.
Parameters
startTime The start time of the timer in string format.
endTime The end time of the timer in string format.
intervalsecs The interval in seconds at which the timer triggers.
maxworksecs The maximum duration in seconds for the timer to perform its work.
References NamedThread::CreateAndRun(), Started(), and UpdateInterval().
Referenced by KTN::Skewer::onJson(), KTN::SkewTrader::onJson(), KTN::Twap::onJson(), and Test().
Started()
bool KTN::ALGO::IntervalTimer::Started () [inline]
Checks if the timer has started.
Returns
True if the timer has started, false otherwise.
Referenced by KTN::Skewer::Enable(), KTN::SkewTrader::Enable(), KTN::Twap::Enable(), KTN::Skewer::minOrderExecution(), KTN::SkewTrader::minOrderExecution(), KTN::Twap::minOrderExecution(), KTN::Skewer::onJson(), KTN::SkewTrader::onJson(), KTN::Twap::onJson(), Start(), KTN::Skewer::~Skewer(), KTN::SkewTrader::~SkewTrader(), and KTN::Twap::~Twap().
Stop()
void IntervalTimer::Stop ()
Stops the timer.
Referenced by KTN::Skewer::minOrderExecution(), KTN::SkewTrader::minOrderExecution(), KTN::Twap::minOrderExecution(), KTN::Skewer::ResetPosition(), KTN::SkewTrader::ResetPosition(), KTN::Twap::ResetPosition(), KTN::Skewer::~Skewer(), KTN::SkewTrader::~SkewTrader(), and KTN::Twap::~Twap().
Test()
void IntervalTimer::Test ()
Test function for the IntervalTimer.
References Start().
Triggered()
bool KTN::ALGO::IntervalTimer::Triggered () [inline]
Checks if the timer has been triggered.
Returns
True if the timer has been triggered, false otherwise.
UpdateInterval()
void IntervalTimer::UpdateInterval (int intervalsecs)
Updates the interval at which the timer triggers.
Parameters
intervalsecs The new interval in seconds.
Referenced by KTN::Skewer::onJson(), and Start().
The documentation for this class was generated from the following files:
AlgoCalculators/IntervalTimer.hpp
AlgoCalculators/IntervalTimer.cpp