PLMonitor Class Reference
Class responsible for monitoring and managing profit and loss calculations for positions.
#include <PLMonitor.hpp>
Public Member Functions
PLMonitor (AlgoPLCallback &sender, string guid)
Constructor for PLMonitor class.
virtual ~PLMonitor ()
Destructor for PLMonitor class.
void Start ()
Starts the PLMonitor.
void Stop ()
Stops the PLMonitor.
void Register (Position &pos)
Registers a position for profit and loss monitoring.
void DeRegister (Position &pos)
Deregisters a position from profit and loss monitoring.
void AdjustRisk (EngineCommand cmd)
Adjusts the risk for the positions.
void onMarketData (const algomd &md)
Handles market data updates.
bool Running ()
Checks if the PLMonitor is running.
void Print ()
Prints the current positions.
Detailed Description
Class responsible for monitoring and managing profit and loss calculations for positions.
Constructor & Destructor Documentation
PLMonitor()
PLMonitor::PLMonitor (AlgoPLCallback & sender, string guid)
Constructor for PLMonitor class.
Parameters
sender The AlgoPLCallback object used for sending profit and loss updates.
guid The unique identifier for the PLMonitor instance.
~PLMonitor()
PLMonitor::~PLMonitor () [virtual]
Destructor for PLMonitor class.
Member Function Documentation
AdjustRisk()
void PLMonitor::AdjustRisk (EngineCommand cmd)
Adjusts the risk for the positions.
Parameters
cmd The EngineCommand object containing the risk adjustment command.
Referenced by KTN::PLWatcher::onEngineJson().
DeRegister()
void PLMonitor::DeRegister (Position & pos)
Deregisters a position from profit and loss monitoring.
Parameters
pos The Position object to deregister.
onMarketData()
void PLMonitor::onMarketData (const algomd & md)
Handles market data updates.
Parameters
md The algomd object containing the market data.
Referenced by KTN::PLWatcher::onMktData().
Print()
void PLMonitor::Print ()
Prints the current positions.
Referenced by KTN::PLWatcher::Print().
Register()
void PLMonitor::Register (Position & pos)
Registers a position for profit and loss monitoring.
Parameters
pos The Position object to register.
Referenced by KTN::PLWatcher::onJson().
Running()
bool PLMonitor::Running () [inline]
Checks if the PLMonitor is running.
Returns
True if the PLMonitor is running, false otherwise.
Start()
void PLMonitor::Start ()
Starts the PLMonitor.
Referenced by KTN::PLWatcher::onLaunch().
Stop()
void PLMonitor::Stop ()
Stops the PLMonitor.
Referenced by KTN::PLWatcher::~PLWatcher().
The documentation for this class was generated from the following files:
AlgoEngines/PLMonitor.hpp
AlgoEngines/PLMonitor.cpp