ZmqSubscriber Class Reference
The ZmqSubscriber class represents a ZMQ subscriber.
#include <ZmqSubscriber.h>
Public Member Functions
ZmqSubscriber ()
ZmqSubscriber constructor.
virtual ~ZmqSubscriber ()
ZmqSubscriber destructor.
bool Init (std::string szServerPort, std::vector< string > vTopics, std::string name, void *(*fpSubCallback)(string, string))
Initializes the ZmqSubscriber with the specified server port, topics, name, and callback function.
vector< string > Init (std::string szServerPort, std::string filename, std::string key, std::string name, void *(*fpSubCallback)(string, string))
Initializes the ZmqSubscriber with the specified server port, filename, key, name, and callback function.
bool AddTopic (std::string szTopic)
Adds a topic to the list of subscribed topics.
void LoadTopics (const std::string &filename, const std::string &key)
Loads topics from a file using the specified filename and key.
Detailed Description
The ZmqSubscriber class represents a ZMQ subscriber.
Constructor & Destructor Documentation
ZmqSubscriber()
ZmqSubscriber::ZmqSubscriber ()
ZmqSubscriber constructor.
~ZmqSubscriber()
ZmqSubscriber::~ZmqSubscriber () [virtual]
ZmqSubscriber destructor.
Member Function Documentation
AddTopic()
bool ZmqSubscriber::AddTopic (std::string szTopic)
Adds a topic to the list of subscribed topics.
Parameters
szTopic The topic to add.
Returns
True if the topic is successfully added, false otherwise.
Init() [1/2]
vector< string > ZmqSubscriber::Init (std::string szServerPort, std::string filename, std::string key, std::string name, void *(* fpSubCallback)(string, string))
Initializes the ZmqSubscriber with the specified server port, filename, key, name, and callback function.
Parameters
szServerPort The server port to connect to.
filename The name of the file containing the topics to subscribe to.
key The key to access the topics in the file.
name The name of the subscriber.
fpSubCallback The callback function to be called when a new message is received.
Returns
A vector of topics that were successfully added.
References Settings::getListCsv(), and Init().
Init() [2/2]
bool ZmqSubscriber::Init (std::string szServerPort, std::vector< string > vTopics, std::string name, void *(* fpSubCallback)(string, string))
Initializes the ZmqSubscriber with the specified server port, topics, name, and callback function.
Parameters
szServerPort The server port to connect to.
vTopics The vector of topics to subscribe to.
name The name of the subscriber.
fpSubCallback The callback function to be called when a new message is received.
Returns
True if initialization is successful, false otherwise.
Referenced by Init().
LoadTopics()
void ZmqSubscriber::LoadTopics (const std::string & filename, const std::string & key)
Loads topics from a file using the specified filename and key.
Parameters
filename The name of the file containing the topics.
key The key to access the topics in the file.
References Settings::getListCsv().
The documentation for this class was generated from the following files:
ZMQ/ZmqSubscriber.h
ZMQ/ZmqSubscriber.cpp