KTN::Core::AllocatorBase< T > Class Template Reference
The AllocatorBase class is a generic allocator class that provides different allocator types based on the selected options.
#include <AllocatorBase.hpp>
Public Types
using AllocatorType = std::allocator<T>
Public Member Functions
AllocatorBase (size_t capacity)
Constructs an AllocatorBase object with the specified capacity.
T * get ()
Returns a pointer to the allocated memory.
~AllocatorBase ()=default
Destroys the AllocatorBase object.
Detailed Description
template<typename T>
class KTN::Core::AllocatorBase< T >
The AllocatorBase class is a generic allocator class that provides different allocator types based on the selected options.
Template Parameters
T The type of the elements to be allocated.
Member Typedef Documentation
AllocatorType
template<typename T >
using KTN::Core::AllocatorBase< T >::AllocatorType = std::allocator<T>
Constructor & Destructor Documentation
AllocatorBase()
template<typename T >
KTN::Core::AllocatorBase< T >::AllocatorBase (size_t capacity) [inline]
Constructs an AllocatorBase object with the specified capacity.
Parameters
capacity The capacity of the allocator.
Member Function Documentation
get()
template<typename T >
T * KTN::Core::AllocatorBase< T >::get () [inline]
Returns a pointer to the allocated memory.
Returns
T* A pointer to the allocated memory.
Referenced by KTN::Core::SimpleMap< K, T >::at(), KTN::Core::SimpleMap< K, T >::erase(), KTN::Core::SimpleMap< K, T >::get(), and KTN::Core::SimpleMap< K, T >::insert().
The documentation for this class was generated from the following file:
Maps/AllocatorBase.hpp