KTN::REPORTER::ReporterBase Class Reference
The base class for all reporters.
#include <ReporterBase.hpp>
Public Member Functions
ReporterBase (string name, int sleepms)
Constructs a ReporterBase object with the given name and sleep time.
virtual ~ReporterBase ()
Destructor for the ReporterBase object.
void Stop ()
Stops the reporter.
void Start ()
Starts the reporter.
Protected Member Functions
virtual void DoWork ()=0
Performs the work of the reporter.
void SendJson (string json)
Sends the given JSON string.
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
Logs the given message.
string getTimeString ()
Gets the current time as a string.
uint64_t getSsboeUs ()
Gets the current system time in microseconds since the epoch.
Protected Attributes
std::atomic< bool > _ACTIVE
Detailed Description
The base class for all reporters.
Constructor & Destructor Documentation
ReporterBase()
ReporterBase::ReporterBase (string name, int sleepms)
Constructs a ReporterBase object with the given name and sleep time.
Parameters
name The name of the reporter.
sleepms The sleep time in milliseconds.
~ReporterBase()
ReporterBase::~ReporterBase () [virtual]
Destructor for the ReporterBase object.
References Stop().
Member Function Documentation
DoWork()
void ReporterBase::DoWork () [protected], [pure virtual]
Performs the work of the reporter.
Implemented in KTN::REPORTER::AlgoPLReporter, KTN::REPORTER::AlgoV3Reporter, KTN::REPORTER::GenericReporter, and KTN::REPORTER::OrderReporterV5.
References LogMe().
getSsboeUs()
uint64_t KTN::REPORTER::ReporterBase::getSsboeUs () [inline], [protected]
Gets the current system time in microseconds since the epoch.
Returns
The current system time in microseconds since the epoch.
Referenced by KTN::REPORTER::AlgoPLReporter::DoWork(), and KTN::REPORTER::AlgoV3Reporter::DoWork().
getTimeString()
string KTN::REPORTER::ReporterBase::getTimeString () [inline], [protected]
Gets the current time as a string.
Returns
The current time as a string.
Referenced by KTN::REPORTER::AlgoPLReporter::DoWork(), and KTN::REPORTER::AlgoV3Reporter::DoWork().
LogMe()
void ReporterBase::LogMe (std::string szMsg, int iColor = LOG_WHITE) [protected]
Logs the given message.
Parameters
szMsg The message to log.
iColor The color of the log message.
Referenced by KTN::REPORTER::OrderReporterV5::DoWork(), and DoWork().
SendJson()
void KTN::REPORTER::ReporterBase::SendJson (string json) [protected]
Sends the given JSON string.
Parameters
json The JSON string to send.
Referenced by KTN::REPORTER::AlgoPLReporter::DoWork(), KTN::REPORTER::GenericReporter::DoWork(), KTN::REPORTER::OrderReporterV5::DoWork(), and KTN::REPORTER::AlgoV3Reporter::SendMessage().
Start()
void ReporterBase::Start ()
Starts the reporter.
References Settings::get(), and Settings::getInteger().
Referenced by KTN::REPORTER::AlgoPLReporter::AlgoPLReporter(), KTN::REPORTER::AlgoV3Reporter::AlgoV3Reporter(), KTN::REPORTER::GenericReporter::GenericReporter(), and KTN::REPORTER::OrderReporterV5::OrderReporterV5().
Stop()
void ReporterBase::Stop ()
Stops the reporter.
Referenced by KTN::REPORTER::AlgoPLReporter::StopWork(), KTN::REPORTER::AlgoV3Reporter::StopWork(), KTN::REPORTER::GenericReporter::StopWork(), KTN::REPORTER::OrderReporterV5::StopWork(), and ~ReporterBase().
Member Data Documentation
_ACTIVE
std::atomic<bool> KTN::REPORTER::ReporterBase::_ACTIVE [protected]
The documentation for this class was generated from the following files:
Reporters/ReporterBase.hpp
Reporters/ReporterBase.cpp