KTN::CME::CmeAlgo Class Reference
Public Member Functions
CmeAlgo (tbb::concurrent_queue< KTN::OrderPod > &qords, const std::string &settingsfile, const std::string &source)
void Start ()
void Stop ()
Stops the exchange.
void ClearMaps ()
Clears the maps.
void Reset ()
Resets the exchange.
void Command (Instruction cmd)
Executes a command.
void PrintLatencies (bool clear)
Prints the latencies.
void Poll ()
Polls the exchange.
uint16_t onRecv (byte_ptr data, int len, int segid, int index) override
This method is called when 8-bit data is received over TCP.
void on_rx_cb (char *buf, int len) override
Received packet callback.
void AddChannelFilter (const CmeSecDef &secdef)
void AddSymbol (string symb)
void Send (KTN::OrderPod &ord, int action)
Sends an order.
void SendMassAction (KTN::Order &)
Sends a mass action.
void SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > &hdg)
void BankTas (std::string secgrp, vector< KTN::OrderPod > &ords)
void BankHedgeOrders (uint64_t ordereqid, const vector< KTN::OrderPod > &ords)
void AlgoJson (string json, ExchCmd::Enum cmd)
void SendWarm (int index)
void PrintSessionMap (ConnState(&conns)[4])
Public Member Functions inherited from KTN::ExchangeBase2
ExchangeBase2 (const std::string &settingsfile, const std::string &source, const std::string &exchname)
Constructor for ExchangeBase2.
virtual ~ExchangeBase2 ()
Destructor for ExchangeBase2.
const std::string & Name () const
Gets the name of the exchange.
virtual void SendHedgeInstruction (uint64_t ordereqid, const std::vector< SpreadHedgeV3 > &hdg)
Sends a hedge instruction.
virtual void AlgoJson (std::string json, ExchCmd::Enum cmd)
Sends an algorithmic command in JSON format.
virtual void PrintMsgRatios ()
Prints the message ratios.
std::string SettFile ()
Gets the settings file path.
Public Member Functions inherited from KTN::NET::EFVIUdpV4
EFVIUdpV4 (std::string feed, bool hwtimestamping, std::string name, bool useCertNrConfigFile=false)
bool apply_filter (const string &connid, const string &ipaddr, int port, bool isA)
void poll ()
void EfPrintStats ()
void RefillRing ()
void testticket ()
int Source ()
Public Member Functions inherited from KTN::TCP::TcpCallback8t
Additional Inherited Members
Public Types inherited from KTN::NET::EFVIUdpV4
enum class FilterIPProto : int { UDP = ::IPPROTO_UDP
, TCP = ::IPPROTO_TCP
 }
typedef i01::core::Timestamp Timestamp
Protected Member Functions inherited from KTN::ExchangeBase2
void LogMe (const std::string &szMsg, int iColor=LOG_WHITE)
Logs a message.
void ChangeName (const std::string &owner, const std::string &source)
Changes the name of the exchange.
void ReportStatus (SessionStatus s)
Reports the status of the session.
void MsgSent (const std::string &symb, int cnt, int volume, int event)
Logs a message indicating that a message was sent.
void StopBase ()
Stops the base exchange.
void fastCopy2 (char *dest, const char *src, size_t length)
Fast copy function for copying memory.
bool needhb ()
Checks if a heartbeat is needed.
Protected Attributes inherited from KTN::ExchangeBase2
ExchState _State
LogSvc * _logsvc
std::unordered_map< std::string, msgrate > _msgratio
std::unordered_map< std::string, msgevents > _msgevents
HashMap< uint64_t, std::vector< KTN::OrderPod >, 1000 > _hedgeOrds
SpreadHedgeCircBuff _hedgeMap
PerformanceTracker _trk
Detailed Description
Constructor & Destructor Documentation
CmeAlgo()
CmeAlgo::CmeAlgo (tbb::concurrent_queue< KTN::OrderPod > & qords, const std::string & settingsfile, const std::string & source) [explicit]
Parameters
qords
settingsfile
source
References LogSvc::ChangeName(), KTN::Core::SPSCRingBuffer< T >::enqueue(), AlgoState::EXCH_CALLBACK_ID, Settings::get(), Settings::getBoolean(), Settings::getInteger(), Settings::getLong(), AlgoState::HedgingState, KTN::CME::IL3::SessionMessageFactory::Init(), AuditTrailWriterV3::InitFileForSeg(), CmeSessionSettings::Load(), KT01::MSGW::CmeMsgw::Load(), KTN::ExchangeBase2::LogMe(), OrderNums::NextOrderId(), OrderNums::NextReqIdEncoded(), algometa::Source, StringSplitter::Split(), and AuditTrailWriterV3::Start().
~CmeAlgo()
CmeAlgo::~CmeAlgo () [virtual]
Member Function Documentation
AddChannelFilter()
void CmeAlgo::AddChannelFilter (const CmeSecDef & secdef)
AddSymbol()
void CmeAlgo::AddSymbol (string symb)
AlgoJson()
void CmeAlgo::AlgoJson (string json, ExchCmd::Enum cmd)
BankHedgeOrders()
void CmeAlgo::BankHedgeOrders (uint64_t ordereqid, const vector< KTN::OrderPod > & ords)
BankTas()
void CmeAlgo::BankTas (std::string secgrp, vector< KTN::OrderPod > & ords)
ClearMaps()
void CmeAlgo::ClearMaps () [virtual]
Clears the maps.
Reimplemented from KTN::ExchangeBase2.
References HashMap< Key, Value, TableSize >::clear(), SpreadHedgeCircBuff::clear(), and KTN::ExchangeBase2::LogMe().
Command()
void CmeAlgo::Command (Instruction command) [virtual]
Executes a command.
Parameters
command The command to execute.
Reimplemented from KTN::ExchangeBase2.
References KTN::ExchangeBase2::LogMe(), and KTN::Core::SPSCRingBuffer< T >::push().
on_rx_cb()
void CmeAlgo::on_rx_cb (char * data, int len) [override], [virtual]
Received packet callback.
Implements KTN::NET::EFVIUdpV4.
onRecv()
uint16_t CmeAlgo::onRecv (byte_ptr data, int len, int segid, int index) [override], [virtual]
This method is called when 8-bit data is received over TCP.
Parameters
data The received data.
len The length of the received data.
segid The segment ID.
index The index.
Returns
The response code.
Implements KTN::TCP::TcpCallback8t.
References KTN::ExchangeBase2::LogMe(), PerformanceTracker::startMeasurement(), PerformanceTracker::stopMeasurement(), and AuditTrailWriterV3::Write().
Poll()
void CmeAlgo::Poll () [virtual]
Polls the exchange.
Reimplemented from KTN::ExchangeBase2.
PrintLatencies()
void CmeAlgo::PrintLatencies (bool clear) [virtual]
Prints the latencies.
Parameters
clear Indicates whether to clear the latencies after printing.
Reimplemented from KTN::ExchangeBase2.
References algomd::ask, algomd::asksize, algomd::bid, algomd::bidsize, PerformanceTracker::clear(), algomd::last, algomd::lastagressor, algomd::lastsize, KTN::ExchangeBase2::LogMe(), OrderManagerV5::Print(), PerformanceTracker::printMeasurements(), and algomd::secid.
PrintSessionMap()
void CmeAlgo::PrintSessionMap (ConnState(&) conns[4])
Reset()
void CmeAlgo::Reset () [virtual]
Resets the exchange.
Reimplemented from KTN::ExchangeBase2.
Send()
void CmeAlgo::Send (KTN::OrderPod & order, int action) [virtual]
Sends an order.
Parameters
order The order to send.
action The action to perform.
Implements KTN::ExchangeBase2.
References KTN::ConnState::connectionState, KTN::CME::IL3::EnumSessionState::Established, KTN::Core::BufferPool::get(), KTN::OrderPod::isManual, KTN::ExchangeBase2::LogMe(), KTN::OrderPod::mktsegid, KTN::OrderPod::OrdAction, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdSide, KTN::OrderPod::price, KTN::Core::BufferPool::put(), KTN::OrderPod::quantity, KTN::OrderPod::secid, KTN::TCP::EFVITcpV5::SendFastPath(), SessionStateManager::SeqOutAndAdvance(), KTN::ConnState::sessmgr, PerformanceTracker::startMeasurement(), PerformanceTracker::stopMeasurement(), KTN::ConnState::tcpHandler, and AuditTrailWriterV3::Write().
SendHedgeInstruction()
void CmeAlgo::SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > & hdg)
SendMassAction()
void CmeAlgo::SendMassAction (KTN::Order & order) [virtual]
Sends a mass action.
Parameters
order The order to send.
Implements KTN::ExchangeBase2.
References KTN::Core::SPSCRingBuffer< T >::push().
SendWarm()
void CmeAlgo::SendWarm (int index)
Start()
void CmeAlgo::Start ()
Stop()
void CmeAlgo::Stop () [virtual]
Stops the exchange.
Implements KTN::ExchangeBase2.
References KTN::ExchangeBase2::LogMe(), and KTN::Core::SPSCRingBuffer< T >::push().
The documentation for this class was generated from the following files:
ExchangeHandlers2/CmeAlgo.hpp
ExchangeHandlers2/CmeAlgo.cpp