KTN::CME::CmeGT5 Class Reference
CmeGT5 class represents the 5th Generation CmeHandler. Low latency order template creation; memory pool usage and custom maps and memory management. It provides better, faster, and stronger functionality for handling CME exchange iLink3 Messages.
#include <CmeGT5.hpp>
Public Member Functions
CmeGT5 (tbb::concurrent_queue< KTN::OrderPod > &qords, const std::string &settingsfile, const std::string &source)
Constructor for CmeGT5 class.
virtual ~CmeGT5 ()
Destructor for CmeGT5 class.
void Start ()
Start the CmeGT5 handler.
void Stop ()
Stop the CmeGT5 handler.
void ClearMaps ()
Clear the maps used by the CmeGT5 handler.
void Reset ()
Reset the CmeGT5 handler.
void Command (Instruction cmd)
Execute a command on the CmeGT5 handler.
void PrintLatencies (bool clear)
Print the latencies.
void Poll ()
Poll for new messages.
void ProcessingThread ()
Processing thread for handling messages.
uint16_t onRecv (byte_ptr data, int len, int segid, int index) override
Callback function for receiving data.
void Send (KTN::OrderPod &ord, int action)
Send an order.
void SendMassAction (KTN::Order &ord)
Send a mass action.
void SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > &hdg)
Send a hedge instruction.
void SendWarm (int index)
Send a warm message.
void PrintSessionMap (ConnState(&conns)[4])
Print the session map.
Public Member Functions inherited from KTN::ExchangeBase2
ExchangeBase2 (const std::string &settingsfile, const std::string &source, const std::string &exchname)
Constructor for ExchangeBase2.
virtual ~ExchangeBase2 ()
Destructor for ExchangeBase2.
const std::string & Name () const
Gets the name of the exchange.
virtual void SendHedgeInstruction (uint64_t ordereqid, const std::vector< SpreadHedgeV3 > &hdg)
Sends a hedge instruction.
virtual void AlgoJson (std::string json, ExchCmd::Enum cmd)
Sends an algorithmic command in JSON format.
virtual void PrintMsgRatios ()
Prints the message ratios.
std::string SettFile ()
Gets the settings file path.
Public Member Functions inherited from KTN::TCP::TcpCallback8t
Additional Inherited Members
Protected Member Functions inherited from KTN::ExchangeBase2
void LogMe (const std::string &szMsg, int iColor=LOG_WHITE)
Logs a message.
void ChangeName (const std::string &owner, const std::string &source)
Changes the name of the exchange.
void ReportStatus (SessionStatus s)
Reports the status of the session.
void MsgSent (const std::string &symb, int cnt, int volume, int event)
Logs a message indicating that a message was sent.
void StopBase ()
Stops the base exchange.
void fastCopy2 (char *dest, const char *src, size_t length)
Fast copy function for copying memory.
bool needhb ()
Checks if a heartbeat is needed.
Protected Attributes inherited from KTN::ExchangeBase2
ExchState _State
LogSvc * _logsvc
std::unordered_map< std::string, msgrate > _msgratio
std::unordered_map< std::string, msgevents > _msgevents
HashMap< uint64_t, std::vector< KTN::OrderPod >, 1000 > _hedgeOrds
SpreadHedgeCircBuff _hedgeMap
PerformanceTracker _trk
Detailed Description
CmeGT5 class represents the 5th Generation CmeHandler. Low latency order template creation; memory pool usage and custom maps and memory management. It provides better, faster, and stronger functionality for handling CME exchange iLink3 Messages.
Constructor & Destructor Documentation
CmeGT5()
CmeGT5::CmeGT5 (tbb::concurrent_queue< KTN::OrderPod > & qords, const std::string & settingsfile, const std::string & source) [explicit]
Constructor for CmeGT5 class.
Parameters
qords The concurrent queue for order pods.
settingsfile The path to the settings file.
source The source of the CME exchange.
qords
settingsfile
source
References LogSvc::ChangeName(), KTN::Core::SPSCRingBuffer< T >::enqueue(), Settings::get(), Settings::getBoolean(), Settings::getInteger(), Settings::getLong(), KTN::CME::IL3::SessionMessageFactory::Init(), AuditTrailWriterV3::InitFileForSeg(), CmeSessionSettings::Load(), KT01::MSGW::CmeMsgw::Load(), KTN::ExchangeBase2::LogMe(), OrderNums::NextOrderId(), OrderNums::NextReqIdEncoded(), ProcessingThread(), StringSplitter::Split(), AuditTrailWriterV3::Start(), and Start().
~CmeGT5()
CmeGT5::~CmeGT5 () [virtual]
Destructor for CmeGT5 class.
Member Function Documentation
ClearMaps()
void CmeGT5::ClearMaps () [virtual]
Clear the maps used by the CmeGT5 handler.
Reimplemented from KTN::ExchangeBase2.
References HashMap< Key, Value, TableSize >::clear(), SpreadHedgeCircBuff::clear(), and KTN::ExchangeBase2::LogMe().
Command()
void CmeGT5::Command (Instruction cmd) [virtual]
Execute a command on the CmeGT5 handler.
Parameters
cmd The instruction command to execute.
Reimplemented from KTN::ExchangeBase2.
References KTN::ExchangeBase2::LogMe(), and KTN::Core::SPSCRingBuffer< T >::push().
onRecv()
uint16_t CmeGT5::onRecv (byte_ptr data, int len, int segid, int index) [override], [virtual]
Callback function for receiving data.
Parameters
data The received data.
len The length of the data.
segid The segment ID.
index The index.
Returns
The number of bytes processed.
Implements KTN::TCP::TcpCallback8t.
References KTN::ExchangeBase2::LogMe(), PerformanceTracker::startMeasurement(), PerformanceTracker::stopMeasurement(), and AuditTrailWriterV3::Write().
Poll()
void CmeGT5::Poll () [virtual]
Poll for new messages.
Poll the Tcp connection for events Note: We've offloaded some event checking etc to the ProcessingThread function
Reimplemented from KTN::ExchangeBase2.
PrintLatencies()
void CmeGT5::PrintLatencies (bool clear) [virtual]
Print the latencies.
Parameters
clear Flag indicating whether to clear the latencies after printing.
Reimplemented from KTN::ExchangeBase2.
References PerformanceTracker::clear(), KTN::ExchangeBase2::LogMe(), and PerformanceTracker::printMeasurements().
PrintSessionMap()
void CmeGT5::PrintSessionMap (ConnState(&) conns[4])
Print the session map.
Parameters
conns The array of connection states.
References KTN::CME::IL3::EnumSessionState::Disconnected, KTN::CME::IL3::EnumSessionState::Established, and KTN::ExchangeBase2::LogMe().
ProcessingThread()
void CmeGT5::ProcessingThread ()
Processing thread for handling messages.
References KTN::ExchangeBase2::LogMe().
Referenced by CmeGT5().
Reset()
void CmeGT5::Reset () [virtual]
Reset the CmeGT5 handler.
Reimplemented from KTN::ExchangeBase2.
Send()
void CmeGT5::Send (KTN::OrderPod & ord, int action) [virtual]
Send an order.
Parameters
ord The order to send.
action The action to perform.
Implements KTN::ExchangeBase2.
References KTN::ConnState::connectionState, KTN::CME::IL3::EnumSessionState::Established, KTN::Core::BufferPool::get(), KTN::OrderPod::isManual, KTN::ExchangeBase2::LogMe(), KTN::OrderPod::mktsegid, KTN::OrderPod::OrdAction, KTN::OrderPod::ordernum, KTN::OrderPod::orderReqId, KTN::OrderPod::OrdSide, KTN::OrderPod::price, KTN::Core::BufferPool::put(), KTN::OrderPod::quantity, KTN::OrderPod::secid, KTN::TCP::EFVITcpV5::SendFastPath(), SessionStateManager::SeqOutAndAdvance(), KTN::ConnState::sessmgr, PerformanceTracker::startMeasurement(), PerformanceTracker::stopMeasurement(), KTN::ConnState::tcpHandler, and AuditTrailWriterV3::Write().
SendHedgeInstruction()
void CmeGT5::SendHedgeInstruction (uint64_t ordereqid, const vector< SpreadHedgeV3 > & hdg)
Send a hedge instruction.
Parameters
ordereqid The order request ID.
hdg The vector of spread hedge instructions.
References KTN::ExchangeBase2::LogMe(), PerformanceTracker::startMeasurement(), and PerformanceTracker::stopMeasurement().
SendMassAction()
void CmeGT5::SendMassAction (KTN::Order & ord) [virtual]
Send a mass action.
Parameters
ord The order to perform the mass action on.
Implements KTN::ExchangeBase2.
References KTN::Core::SPSCRingBuffer< T >::push().
SendWarm()
void CmeGT5::SendWarm (int index)
Send a warm message.
Parameters
index The index.
References KTN::TCP::EFVITcpV5::SendWarm(), and KTN::ConnState::tcpHandler.
Start()
void CmeGT5::Start ()
Start the CmeGT5 handler.
References KTN::ConnState::connectionState, KTN::CME::IL3::EnumSessionState::Disconnected, KTN::ConnState::index, KTN::ExchangeBase2::LogMe(), KTN::ConnState::segid, and KTN::ConnState::tcpHandler.
Referenced by CmeGT5().
Stop()
void CmeGT5::Stop () [virtual]
Stop the CmeGT5 handler.
Implements KTN::ExchangeBase2.
References KTN::ExchangeBase2::LogMe(), and KTN::Core::SPSCRingBuffer< T >::push().
The documentation for this class was generated from the following files:
ExchangeHandlers2/CmeGT5.hpp
ExchangeHandlers2/CmeGT5.cpp