i01::net::SFCPktBuf Class Reference
Represents a packet buffer used in the SFC network library.
#include <SFCPktBuf.hpp>
Classes
struct SFCPktBufPOD
Represents the Packet Buffer POD (Plain Old Data) structure.
Public Member Functions
ef_addr & addr ()
Returns the address of the packet buffer.
int pool_id ()
Returns the pool ID of the packet buffer.
size_t size ()
Returns the size of the packet buffer.
const char * data () const
Returns a constant pointer to the data in the packet buffer.
char * data ()
Returns a pointer to the data in the packet buffer.
const char * data2 () const
Returns a constant pointer to the secondary data in the packet buffer.
char * data2 ()
Returns a pointer to the secondary data in the packet buffer.
const char * operator[] (int n) const
Returns a constant pointer to the data at the specified index in the packet buffer.
char * operator[] (int n)
Returns a pointer to the data at the specified index in the packet buffer.
Static Public Member Functions
static constexpr size_t prefix_size ()
Returns the size of the prefix in the packet buffer.
static constexpr size_t capacity ()
Returns the capacity of the packet buffer.
static constexpr size_t alloc_size ()
Returns the allocation size of the packet buffer.
Public Attributes
struct i01::net::SFCPktBuf::SFCPktBufPOD m_pod
Detailed Description
Represents a packet buffer used in the SFC network library.
Member Function Documentation
addr()
ef_addr & i01::net::SFCPktBuf::addr () [inline]
Returns the address of the packet buffer.
Returns
The address of the packet buffer.
References i01::net::SFCPktBuf::SFCPktBufPOD::m_addr.
alloc_size()
static constexpr size_t i01::net::SFCPktBuf::alloc_size () [inline], [static], [constexpr]
Returns the allocation size of the packet buffer.
Returns
The allocation size of the packet buffer.
Referenced by KTN::TCP::EFVITcpV2::EFVI_TCP_Start().
capacity()
static constexpr size_t i01::net::SFCPktBuf::capacity () [inline], [static], [constexpr]
Returns the capacity of the packet buffer.
Returns
The capacity of the packet buffer.
References prefix_size().
data() [1/2]
char * i01::net::SFCPktBuf::data () [inline]
Returns a pointer to the data in the packet buffer.
Returns
A pointer to the data in the packet buffer.
data() [2/2]
const char * i01::net::SFCPktBuf::data () const [inline]
Returns a constant pointer to the data in the packet buffer.
Returns
A constant pointer to the data in the packet buffer.
Referenced by operator[](), and operator[]().
data2() [1/2]
char * i01::net::SFCPktBuf::data2 () [inline]
Returns a pointer to the secondary data in the packet buffer.
Returns
A pointer to the secondary data in the packet buffer.
data2() [2/2]
const char * i01::net::SFCPktBuf::data2 () const [inline]
Returns a constant pointer to the secondary data in the packet buffer.
Returns
A constant pointer to the secondary data in the packet buffer.
operator[]() [1/2]
char * i01::net::SFCPktBuf::operator[] (int n) [inline]
Returns a pointer to the data at the specified index in the packet buffer.
Parameters
n The index of the data.
Returns
A pointer to the data at the specified index in the packet buffer.
References data().
operator[]() [2/2]
const char * i01::net::SFCPktBuf::operator[] (int n) const [inline]
Returns a constant pointer to the data at the specified index in the packet buffer.
Parameters
n The index of the data.
Returns
A constant pointer to the data at the specified index in the packet buffer.
References data().
pool_id()
int i01::net::SFCPktBuf::pool_id () [inline]
Returns the pool ID of the packet buffer.
Returns
The pool ID of the packet buffer.
prefix_size()
static constexpr size_t i01::net::SFCPktBuf::prefix_size () [inline], [static], [constexpr]
Returns the size of the prefix in the packet buffer.
Returns
The size of the prefix.
Referenced by capacity().
size()
size_t i01::net::SFCPktBuf::size () [inline]
Returns the size of the packet buffer.
Returns
The size of the packet buffer.
The documentation for this class was generated from the following file:
C:/Users/sgaer/source/repos/katanafinancial/OccamCME4/OccamCME4/src/i01_net/SFCPktBuf.hpp