KTN::ALGO::PRICING::SpreadPricer Class Reference
The SpreadPricer class is a pricing strategy for calculating spread prices.
#include <SpreadPricer.hpp>
Public Member Functions
SpreadPricer ()
Constructs a new SpreadPricer object.
virtual ~SpreadPricer ()
Destroys the SpreadPricer object.
void LoadOrders (int cbid, algometa meta)
Loads orders for the SpreadPricer.
void CalculateSide2 (LittleImpSide &imp, int index, int spmult, bool isBid, double edge, int ticks, const algomd *prices, bool testmode)
Calculates the side 2 for the SpreadPricer.
void CalculateSide3 (LittleImpSide &imp, int index, int spmult, bool isBid, double edge, int ticks, const algomd *prices, bool testmode)
Calculates the side 3 for the SpreadPricer.
void CalculateSimple (LittleImpSide &imp, int index, int spmult, bool isBid, double edge, int ticks, const algomd *prices, bool testmode)
Calculates the simple spread for the SpreadPricer.
Public Member Functions inherited from KTN::ALGO::PRICING::PricingStrategyBase
PricingStrategyBase ()
Default constructor.
virtual ~PricingStrategyBase ()
Destructor.
void Load (instrument *legs, int len, bool certnr)
Load the pricing strategy with the given legs.
Additional Inherited Members
Protected Member Functions inherited from KTN::ALGO::PRICING::PricingStrategyBase
void LogMe (std::string szMsg, int iColor=LOG_WHITE)
Log a message.
int roundToTick (int value, int MINTICK, int side)
Round a value to the nearest tick.
float priceRoundConvert (float px, int tickprecision, float mintick, bool roundUp=false)
Round and convert a price value.
int32_t getCertSecId (string symbol)
Get the certificate security ID for the given symbol.
Protected Attributes inherited from KTN::ALGO::PRICING::PricingStrategyBase
instrument _legs [24]
int _numLegs
bool _priceround
bool _CERTNR
tr1::unordered_map< string, long > _certIdMap
Detailed Description
The SpreadPricer class is a pricing strategy for calculating spread prices.
Constructor & Destructor Documentation
SpreadPricer()
SpreadPricer::SpreadPricer ()
Constructs a new SpreadPricer object.
~SpreadPricer()
SpreadPricer::~SpreadPricer () [virtual]
Destroys the SpreadPricer object.
Member Function Documentation
CalculateSide2()
void SpreadPricer::CalculateSide2 (LittleImpSide & imp, int index, int spmult, bool isBid, double edge, int ticks, const algomd * prices, bool testmode)
Calculates the side 2 for the SpreadPricer.
Calculate the quote for a given side as well as all leg prices for hedges, taking into account the current market pricing for each leg and the respective multipliers. See comments inline for more info.
Parameters
imp The LittleImpSide object.
index The index value.
spmult The spmult value.
isBid The isBid flag.
edge The edge value.
ticks The ticks value.
prices The array of algomd objects.
testmode The testmode flag.
imp Hedging Instructions struct to pass to handler/hedger
index Inst index in the prices array index of leg to be quoted
spmult Spread Multiplier for leg to be quoted.
isBid Quick boolean value if this spread is a bid or ask
edge Spread edge
ticks Discretionary ticks for hedge prices - see note inline
prices array of most current prices from MD Handler
testmode
References algomd::ask, algomd::bid, KTN::Core::ObjectPool< T >::get(), instrument::index, instrument::mktsegid, instrument::pricemult, instrument::secid, and instrument::spreadmult.
CalculateSide3()
void SpreadPricer::CalculateSide3 (LittleImpSide & imp, int index, int spmult, bool isBid, double edge, int ticks, const algomd * prices, bool testmode)
Calculates the side 3 for the SpreadPricer.
Parameters
imp The LittleImpSide object.
index The index value.
spmult The spmult value.
isBid The isBid flag.
edge The edge value.
ticks The ticks value.
prices The array of algomd objects.
testmode The testmode flag.
References algomd::ask, algomd::bid, KTN::Core::ObjectPool< T >::get(), instrument::index, instrument::mintick, instrument::mktsegid, instrument::pricemult, KTN::ALGO::PRICING::PricingStrategyBase::roundToTick(), instrument::secid, instrument::spreadmult, and instrument::squeeze.
CalculateSimple()
void SpreadPricer::CalculateSimple (LittleImpSide & imp, int index, int spmult, bool isBid, double edge, int ticks, const algomd * prices, bool testmode)
Calculates the simple spread for the SpreadPricer.
Parameters
imp The LittleImpSide object.
index The index value.
spmult The spmult value.
isBid The isBid flag.
edge The edge value.
ticks The ticks value.
prices The array of algomd objects.
testmode The testmode flag.
References algomd::ask, algomd::bid, instrument::pricemult, and instrument::spreadmult.
LoadOrders()
void SpreadPricer::LoadOrders (int cbid, algometa meta)
Loads orders for the SpreadPricer.
Parameters
cbid The cbid value.
meta The algometa object.
The documentation for this class was generated from the following files:
AlgoEngines/SpreadPricer.hpp
AlgoEngines/SpreadPricer.cpp