KtnCmeMbo Class Reference
Represents a class that handles CME market by order (MBO) data.
#include <KtnCmeMbo.hpp>
Public Types
using UpdateAlgoCallback = void (*)(const algomd&)
Public Types inherited from KTN::NET::EFVIUdpV4
enum class FilterIPProto : int { UDP = ::IPPROTO_UDP
, TCP = ::IPPROTO_TCP
 }
typedef i01::core::Timestamp Timestamp
Public Member Functions
KtnCmeMbo (string name, int core, bool handletrades)
Constructs a KtnCmeMbo object.
virtual ~KtnCmeMbo ()
Destroys the KtnCmeMbo object.
void Start ()
Starts the KtnCmeMbo object.
void Stop ()
Stops the KtnCmeMbo object.
void Reset ()
Resets the KtnCmeMbo object.
void PrintStats ()
Prints the statistics of the KtnCmeMbo object.
void AddSymbols (vector< string > symbols)
Adds a list of symbols to the KtnCmeMbo object.
void AddSymbols (vector< instrument > legs)
Adds a list of instruments to the KtnCmeMbo object.
void AddSymbol (string symb)
Adds a symbol to the KtnCmeMbo object.
void AddBookDepth (string symb)
Adds book depth for a symbol to the KtnCmeMbo object.
void AddMbo (string symb)
Adds market by order (MBO) data for a symbol to the KtnCmeMbo object.
void AddChannelFilter (const CmeSecDef &secdef, const string &feedtype)
Adds a channel filter for a CME security definition and feed type to the KtnCmeMbo object.
void Subscribe (AlgoMktDataCallback *subscriber)
Subscribes an AlgoMktDataCallback object to the KtnCmeMbo object.
void Print (bool verbose)
Prints the KtnCmeMbo object.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Public Member Functions inherited from KTN::NET::EFVIUdpV4
EFVIUdpV4 (std::string feed, bool hwtimestamping, std::string name, bool useCertNrConfigFile=false)
bool apply_filter (const string &connid, const string &ipaddr, int port, bool isA)
void poll ()
void EfPrintStats ()
void RefillRing ()
void testticket ()
int Source ()
Public Attributes
algomd _algomds [16]
bookmd _bookmds [16]
std::vector< string > _FILTERS
int _SECIDS [16]
int _NUMSECS
vector< CmeSecDef > _DEFS
tr1::unordered_map< int, string > _SYMBMAP
Detailed Description
Represents a class that handles CME market by order (MBO) data.
Member Typedef Documentation
UpdateAlgoCallback
using KtnCmeMbo::UpdateAlgoCallback = void (*)(const algomd&)
Constructor & Destructor Documentation
KtnCmeMbo()
KtnCmeMbo::KtnCmeMbo (string name, int core, bool handletrades) [explicit]
Constructs a KtnCmeMbo object.
Parameters
name The name of the KtnCmeMbo object.
core The core number to run the KtnCmeMbo object on.
handletrades A flag indicating whether to handle trades.
~KtnCmeMbo()
KtnCmeMbo::~KtnCmeMbo () [virtual]
Destroys the KtnCmeMbo object.
Member Function Documentation
AddBookDepth()
void KtnCmeMbo::AddBookDepth (string symb)
Adds book depth for a symbol to the KtnCmeMbo object.
Parameters
symb The symbol to add book depth for.
References AddChannelFilter(), bookmd::index, and bookmd::secid.
AddChannelFilter()
void KtnCmeMbo::AddChannelFilter (const CmeSecDef & secdef, const string & feedtype)
Adds a channel filter for a CME security definition and feed type to the KtnCmeMbo object.
Parameters
secdef The CME security definition.
feedtype The feed type.
Referenced by AddBookDepth(), and AddSymbol().
AddMbo()
void KtnCmeMbo::AddMbo (string symb)
Adds market by order (MBO) data for a symbol to the KtnCmeMbo object.
Parameters
symb The symbol to add MBO data for.
AddSymbol()
void KtnCmeMbo::AddSymbol (string symb)
Adds a symbol to the KtnCmeMbo object.
Parameters
symb The symbol to add.
References AddChannelFilter(), algomd::hasImpliedEnabled, algomd::index, and algomd::secid.
Referenced by AddSymbols(), and AddSymbols().
AddSymbols() [1/2]
void KtnCmeMbo::AddSymbols (vector< instrument > legs)
Adds a list of instruments to the KtnCmeMbo object.
Parameters
legs The list of instruments to add.
References AddSymbol().
AddSymbols() [2/2]
void KtnCmeMbo::AddSymbols (vector< string > symbols)
Adds a list of symbols to the KtnCmeMbo object.
Parameters
symbols The list of symbols to add.
References AddSymbol().
Print()
void KtnCmeMbo::Print (bool verbose)
Prints the KtnCmeMbo object.
Parameters
verbose A flag indicating whether to print verbose information.
PrintStats()
void KtnCmeMbo::PrintStats ()
Prints the statistics of the KtnCmeMbo object.
References PerformanceTracker::printMeasurements().
Start()
void KtnCmeMbo::Start ()
Starts the KtnCmeMbo object.
References NamedThread::CreateAndRun().
Stop()
void KtnCmeMbo::Stop ()
Stops the KtnCmeMbo object.
Subscribe()
void KtnCmeMbo::Subscribe (AlgoMktDataCallback * subscriber)
Subscribes an AlgoMktDataCallback object to the KtnCmeMbo object.
Parameters
subscriber The AlgoMktDataCallback object to subscribe.
Member Data Documentation
_algomds
algomd KtnCmeMbo::_algomds[16]
_bookmds
bookmd KtnCmeMbo::_bookmds[16]
_DEFS
vector<CmeSecDef> KtnCmeMbo::_DEFS
_FILTERS
std::vector<string> KtnCmeMbo::_FILTERS
_NUMSECS
int KtnCmeMbo::_NUMSECS
_SECIDS
int KtnCmeMbo::_SECIDS[16]
_SYMBMAP
tr1::unordered_map<int, string> KtnCmeMbo::_SYMBMAP
The documentation for this class was generated from the following files:
exchsupport/cme/KtnCmeMbo.hpp
exchsupport/cme/KtnCmeMbo.cpp