AuditTrailWriterV3 Class Reference
Represents a ultra low latency class for writing audit trail logs using SPSC RingBuffer Queues.
#include <AuditTrailWriterV3.hpp>
Public Member Functions
AuditTrailWriterV3 ()
Default constructor for AuditTrailWriterV3.
virtual ~AuditTrailWriterV3 ()
Destructor for AuditTrailWriterV3.
void Start (string dir, string sessid, string firmid, int core)
Starts the audit trail writer.
void InitFileForSeg (int segid)
Initializes the audit trail file for a specific segment.
void CreateAuditFile (string sessid, string firmid, int segid)
Creates an audit trail file for a specific session, firm, and segment.
void Write (KTNBuf *msg)
Writes a message to the audit trail.
void Write (char *buf, int msgtype, int segid)
Writes a message to the audit trail.
int Size ()
Gets the size of the audit trail writer.
Public Member Functions inherited from NamedThread
NamedThread ()
Default constructor.
virtual ~NamedThread ()
Destructor.
void CreateAndRun (string name, int core)
Creates and runs the named thread on the specified core.
void Join ()
Joins the named thread.
Detailed Description
Represents a ultra low latency class for writing audit trail logs using SPSC RingBuffer Queues.
Constructor & Destructor Documentation
AuditTrailWriterV3()
AuditTrailWriterV3::AuditTrailWriterV3 ()
Default constructor for AuditTrailWriterV3.
~AuditTrailWriterV3()
AuditTrailWriterV3::~AuditTrailWriterV3 () [virtual]
Destructor for AuditTrailWriterV3.
Member Function Documentation
CreateAuditFile()
void AuditTrailWriterV3::CreateAuditFile (string sessid, string firmid, int segid)
Creates an audit trail file for a specific session, firm, and segment.
Parameters
sessid The session ID.
firmid The firm ID.
segid The segment ID.
Referenced by InitFileForSeg().
InitFileForSeg()
void AuditTrailWriterV3::InitFileForSeg (int segid)
Initializes the audit trail file for a specific segment.
Parameters
segid The segment ID.
References CreateAuditFile().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
Size()
int AuditTrailWriterV3::Size () [inline]
Gets the size of the audit trail writer.
Returns
The size of the audit trail writer.
References KTN::Core::SPSCRingBuffer< T >::empty().
Start()
void AuditTrailWriterV3::Start (string dir, string sessid, string firmid, int core)
Starts the audit trail writer.
Parameters
dir The directory path for storing the audit trail files.
sessid The session ID.
firmid The firm ID.
core The core number.
References NamedThread::CreateAndRun(), and KTN::CME::IL3::META::IL3MetaMap::init().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), and KTN::CME::CmeGT5::CmeGT5().
Write() [1/2]
void AuditTrailWriterV3::Write (char * buf, int msgtype, int segid)
Writes a message to the audit trail.
Parameters
buf The buffer containing the message.
msgtype The message type.
segid The segment ID.
References KTN::Core::SPSCRingBuffer< T >::push().
Write() [2/2]
void AuditTrailWriterV3::Write (KTNBuf * msg)
Writes a message to the audit trail.
Parameters
msg The message to write.
Referenced by KTN::CME::CmeAlgo::onRecv(), KTN::CME::CmeGT5::onRecv(), KTN::CME::CmeAlgo::Send(), and KTN::CME::CmeGT5::Send().
The documentation for this class was generated from the following files:
Loggers/AuditTrailWriterV3.hpp
Loggers/AuditTrailWriterV3.cpp