PerformanceCounter Class Reference
Public Types
typedef timespec Count
Represents a high-resolution performance counter value.
typedef long long Span
Static Public Member Functions
static void setToUndefinedValue (Count *value)
Sets the given performance counter value to an undefined state.
static bool isUndefinedValue (Count &value)
Checks if the given performance counter value is in an undefined state.
static Count current ()
Retrieves the current value of the high-resolution performance counter.
static void current (Count *result)
Retrieves the current value of the high-resolution performance counter.
static Span nsSpan (const PerformanceCounter::Count &stop, const PerformanceCounter::Count &start)
Calculates the time span in nanoseconds between two performance counter values.
static Span usSpan (const PerformanceCounter::Count &stop, const PerformanceCounter::Count &start)
Calculates the time span in microseconds between two performance counter values.
static Span elapsedNanoseconds (const PerformanceCounter::Count &start)
Calculates the elapsed time in nanoseconds since the given performance counter value.
static Span elapsedMicroseconds (const PerformanceCounter::Count &start)
Calculates the elapsed time in microseconds since the given performance counter value.
Detailed Description
Member Typedef Documentation
Count
timespec PerformanceCounter::Count
Represents a high-resolution performance counter value.
Span
long long PerformanceCounter::Span
Member Function Documentation
current() [1/2]
PerformanceCounter::Count PerformanceCounter::current () [inline], [static]
Retrieves the current value of the high-resolution performance counter.
Returns
The current performance counter value.
References current().
Referenced by current(), elapsedMicroseconds(), and elapsedNanoseconds().
current() [2/2]
void PerformanceCounter::current (PerformanceCounter::Count * result) [inline], [static]
Retrieves the current value of the high-resolution performance counter.
Parameters
result The variable to store the current performance counter value.
elapsedMicroseconds()
Span PerformanceCounter::elapsedMicroseconds (const PerformanceCounter::Count & start) [inline], [static]
Calculates the elapsed time in microseconds since the given performance counter value.
Parameters
start The start performance counter value.
Returns
The elapsed time in microseconds.
References current(), and usSpan().
elapsedNanoseconds()
Span PerformanceCounter::elapsedNanoseconds (const PerformanceCounter::Count & start) [inline], [static]
Calculates the elapsed time in nanoseconds since the given performance counter value.
Parameters
start The start performance counter value.
Returns
The elapsed time in nanoseconds.
References current(), and nsSpan().
isUndefinedValue()
bool PerformanceCounter::isUndefinedValue (Count & value) [inline], [static]
Checks if the given performance counter value is in an undefined state.
Parameters
value The performance counter value to check.
Returns
true if the performance counter value is undefined, false otherwise.
nsSpan()
Span PerformanceCounter::nsSpan (const PerformanceCounter::Count & stop, const PerformanceCounter::Count & start) [inline], [static]
Calculates the time span in nanoseconds between two performance counter values.
Parameters
stop The stop performance counter value.
start The start performance counter value.
Returns
The time span in nanoseconds.
Referenced by elapsedNanoseconds().
setToUndefinedValue()
void PerformanceCounter::setToUndefinedValue (Count * value) [inline], [static]
Sets the given performance counter value to an undefined state.
Parameters
value The performance counter value to set.
usSpan()
Span PerformanceCounter::usSpan (const PerformanceCounter::Count & stop, const PerformanceCounter::Count & start) [inline], [static]
Calculates the time span in microseconds between two performance counter values.
Parameters
stop The stop performance counter value.
start The start performance counter value.
Returns
The time span in microseconds.
Referenced by elapsedMicroseconds().
The documentation for this class was generated from the following file:
Core/PerformanceCounter.h