CmeSessionSettings Struct Reference
Represents the settings for a CME session.
#include <CmeSessionSettings.hpp>
Public Member Functions
void Load (const string &filename)
Loads the session settings from the specified file.
Public Attributes
std::string TraderId
string SessionId
string FirmId
string AccessKey
string SecretKey
uint64_t SelfMatchId
int Port
int BackupPort
int PartyListId
int KeepAliveSecs
bool FaultTolerance
std::string Source
std::string ExchName
std::string Org
std::string Account
int CustOrdCapacity
std::string Location
std::string Tag50_Manual
std::string Tag50_Auto
bool CertNr
std::string SystemName
std::string SystemVersionId
std::string SystemVendor
bool UseFeed_A
int Affinity
string Filename
Public Attributes inherited from SessionSettings
string Filename
Detailed Description
Represents the settings for a CME session.
Member Function Documentation
Load()
void CmeSessionSettings::Load (const string & filename) [inline]
Loads the session settings from the specified file.
Parameters
filename The name of the file containing the session settings.
References Settings::get(), Settings::getBoolean(), Settings::getInteger(), and Settings::getLong().
Referenced by KTN::CME::CmeAlgo::CmeAlgo(), KTN::CME::CmeGT5::CmeGT5(), and KTN::CME::IL3::SessionMessageFactory::Init().
Member Data Documentation
AccessKey
string CmeSessionSettings::AccessKey
Account
std::string CmeSessionSettings::Account
Affinity
int CmeSessionSettings::Affinity
BackupPort
int CmeSessionSettings::BackupPort
CertNr
bool CmeSessionSettings::CertNr
CustOrdCapacity
int CmeSessionSettings::CustOrdCapacity
ExchName
std::string CmeSessionSettings::ExchName
FaultTolerance
bool CmeSessionSettings::FaultTolerance
Filename
string CmeSessionSettings::Filename
FirmId
string CmeSessionSettings::FirmId
KeepAliveSecs
int CmeSessionSettings::KeepAliveSecs
Location
std::string CmeSessionSettings::Location
Org
std::string CmeSessionSettings::Org
PartyListId
int CmeSessionSettings::PartyListId
Port
int CmeSessionSettings::Port
SecretKey
string CmeSessionSettings::SecretKey
SelfMatchId
uint64_t CmeSessionSettings::SelfMatchId
SessionId
string CmeSessionSettings::SessionId
Source
std::string CmeSessionSettings::Source
SystemName
std::string CmeSessionSettings::SystemName
SystemVendor
std::string CmeSessionSettings::SystemVendor
SystemVersionId
std::string CmeSessionSettings::SystemVersionId
Tag50_Auto
std::string CmeSessionSettings::Tag50_Auto
Tag50_Manual
std::string CmeSessionSettings::Tag50_Manual
TraderId
std::string CmeSessionSettings::TraderId
UseFeed_A
bool CmeSessionSettings::UseFeed_A
The documentation for this struct was generated from the following file:
exchsupport/cme/il3/CmeSessionSettings.hpp