WavesParams Struct Reference
Struct representing the parameters for the Waves algorithm.
#include <WavesParams.hpp>
Public Member Functions
void init ()
Initializes the curveMatrix with default values.
Static Public Member Functions
static WavesParams parse (const std::string &json_str)
Parses the WavesParams from a JSON string.
Public Attributes
EdgeStruct curveMatrix [MAX_SIZE][MAX_SIZE]
bool ValidJson
algometa meta
string subid
std::unordered_map< int, instrument > LegSecIdMap
instrument Legs [32]
int LegCount
combopath paths [MAX_SIZE][MAX_SIZE]
bool TestMode
bool Reset
string Product
string StartMonth
int StartYear
int NumMonths
int MinWidth
int MaxWidth
int OrderQty
int TotalQty
int TotalExec
int BidEdge
int AskEdge
bool SendBids
bool SendAsks
bool Doubles
bool Triples
bool Quads
double WavgThreshold
double SqueezeRatio
int SqueezeQty
Static Public Attributes
static const int MAX_SIZE = 24
Detailed Description
Struct representing the parameters for the Waves algorithm.
Member Function Documentation
init()
void WavesParams::init () [inline]
Initializes the curveMatrix with default values.
References LegPrices::ask, LegPrices::bid, EdgeStruct::exists, EdgeStruct::index, EdgeStruct::istas, and EdgeStruct::prices.
Referenced by parse().
parse()
WavesParams WavesParams::parse (const std::string & json_str) [static]
Parses the WavesParams from a JSON string.
Parameters
json_str The JSON string to parse.
Returns
The parsed WavesParams object.
References algometa::Enabled, UserInfo::groupname, init(), UserInfo::org, algometa::Source, algometa::Strategy, algometa::Tag, algometa::TemplateName, algometa::UniqueId, UserInfo::user, and algometa::userinfo.
Referenced by KTN::Waves::onLaunch().
Member Data Documentation
AskEdge
int WavesParams::AskEdge
BidEdge
int WavesParams::BidEdge
curveMatrix
EdgeStruct WavesParams::curveMatrix[MAX_SIZE][MAX_SIZE]
Doubles
bool WavesParams::Doubles
LegCount
int WavesParams::LegCount
Legs
instrument WavesParams::Legs[32]
LegSecIdMap
std::unordered_map<int, instrument> WavesParams::LegSecIdMap
MAX_SIZE
const int WavesParams::MAX_SIZE = 24 [static]
MaxWidth
int WavesParams::MaxWidth
meta
algometa WavesParams::meta
MinWidth
int WavesParams::MinWidth
NumMonths
int WavesParams::NumMonths
OrderQty
int WavesParams::OrderQty
paths
combopath WavesParams::paths[MAX_SIZE][MAX_SIZE]
Product
string WavesParams::Product
Quads
bool WavesParams::Quads
Reset
bool WavesParams::Reset
SendAsks
bool WavesParams::SendAsks
SendBids
bool WavesParams::SendBids
SqueezeQty
int WavesParams::SqueezeQty
SqueezeRatio
double WavesParams::SqueezeRatio
StartMonth
string WavesParams::StartMonth
StartYear
int WavesParams::StartYear
subid
string WavesParams::subid
TestMode
bool WavesParams::TestMode
TotalExec
int WavesParams::TotalExec
TotalQty
int WavesParams::TotalQty
Triples
bool WavesParams::Triples
ValidJson
bool WavesParams::ValidJson
WavgThreshold
double WavesParams::WavgThreshold
The documentation for this struct was generated from the following files:
AlgoParams/WavesParams.hpp
AlgoParams/WavesParams.cpp