#Exchange
Exchange.Name = cme
Exchange.Active = True
Exchange.Protocol = 5ALGO

#Primary/Secondary
IL3.UsePrimary = True

#Organization
IL3.Org = AKL
IL3.Account = 12345678
IL3.CustOrdCapacity = 1 #<< MEMBER FIRM=1 CUSTOMER = 4; CONSULT YOUR GAM AND CME HELPDESK
IL3.PartyListId = 17
IL3.Automated = AKLATS
IL3.Manual = AKLMAN

#System - THIS WILL CHANGE ONCE WE REGISTER WITH CME
IL3.SystemVendor=AKL
IL3.SystemName=Edge
IL3.SystemVersionId=1.0.0

#Session
IL3.ConfigDir = config/
IL3.SessionFile = ALU-NR.conf
IL3.InSeqNum = 0
IL3.OutSeqNum = 0
IL3.SEGLIST = 64,80,84

#General
IL3.Verbose = False
IL3.LogMessagesToScreen = False
IL3.MeasureLatency = True
IL3.CertNr = True
IL3.CertNrMktData = False
IL3.UseEfvi = True
IL3.PollerMax = 100000

#Audit
IL3.UseAuditTrail = True
IL3.AuditTrailDirectory = audit/
IL3.AuditCore = 1

#Logging
IL3.UseStateFile = True
IL3.StateFileDirectory = MsgStorage
IL3.UseStateLog = True

#Housekeeping
IL3.FaultTolerance = False
IL3.KeepAliveInterval = 50
IL3.KeepAliveBufferMS = 100
IL3.RetransOnNewUUID = True

#Debug Prints
IL3.DebugHmac = False
IL3.DebugRecvBytes = True
IL3.DebugSession = True
IL3.DebugAppMsgs = True
IL3.DebugSessMsgs = True
IL3.DebugGapDetection = True

#Net
IL3.UseFeedA = True
IL3.SendingThreadAffinity = 4
IL3.ReceivingThreadAffinity = 4

