#Exchange
Exchange.Name = OSE
Exchange.Active = True
Exchange.Protocol = OMNET

#Organization
OSE.Org = AKL
OSE.Account = 086Z4

#Session
OSE.ConfigDir = config/ose/
OSE.SessionFile = sessions/AKL01.conf

#Threading
OSE.WorkerCount = 1
OSE.WorkerAffinity = 4
OSE.BdxAffinity = 5
OSE.SendingThreadAffinity = 4
OSE.BdxPollIntervalUs = 0

#Behavior
OSE.ForceLogin = True
OSE.AutoCancellation = True
OSE.KeepAliveInterval = 5
OSE.MeasureLatency = True

#Audit
OSE.UseAuditTrail = True
OSE.AuditTrailDirectory = audit/
OSE.AuditCore = 2

#Logging
OSE.UseStateFile = True
OSE.StateFileDirectory = MsgStorage
OSE.UseStateLog = True

#Debug Prints
OSE.DebugSession = True
OSE.DebugAppMsgs = True
OSE.DebugRecvBytes = True
